### ISSUE TITLE
aterm error

### ISSUE THREAD

**Issue by Wjsfj51najdk** [termux/x11-packages#10]
CANNOT LINK EXECUTABLE: library "libSM.so.6" not found
page record for 0x7f94c94010 was not found (block_size=64)

I reinstalled libsm but the same problem again.I don't want to reinstall termux cos I 've installed a lot of package.How can I fix this?

**Comment by xeffyr** [comment]
Currently fix this by executing:
```
cd $PREFIX/lib
ln -s libSM.so libSM.so.6
```

**Comment by xeffyr** [comment]
Should be fixed now.

**Comment by Wjsfj51najdk** [comment]
Fixed now . Thanks.
