### ISSUE TITLE
xrdb, libxmu: library libXmuu.so.1 not found

### ISSUE THREAD

**Issue by smaslovski** [termux/x11-packages#101]
**Problem description**

$ xrdb
CANNOT LINK EXECUTABLE "xrdb": library "libXmuu.so.1" not found
Aborted

$ dpkg -S libXmuu.so
libxmu: /data/data/com.termux/files/usr/lib/libXmuu.so
$ dpkg -S libXmuu.so.1
dpkg-query: no path found matching pattern *libXmuu.so.1*

**Steps to reproduce**
1. Install xorg-xrdb with its dependencies.
2. Run xrdb.

**Expected behavior**
xrdb runs OK

**System information**

$ termux-info
Updatable packages:
openssl/stable 1.1.1c aarch64 [upgradable from: 1.1.1b-3]
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://hax4us.github.io/termux-x x11-stable/main
https://hax4us.github.io/termux-x x11-stable/main
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.71-15759240 #1 SMP PREEMPT Thu Apr 4 14:01:51 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-T820

**Comment by smaslovski** [comment]
Here is the workaround:

$ pkg install patchelf
$ cd $PREFIX/lib
$ ln -s libXmuu.so libXmuu.so.1
$ patchelf --set-rpath $PREFIX/lib ../bin/xrdb

**Comment by smaslovski** [comment]
Oops, I just now realized that xorg-xrdb comes from another repository (https://hax4us.github.io/termux-x), so the rpath issue belongs to hax4us...

**Comment by xeffyr** [comment]
3 things:

* xorg-xrdb is not part of my repository.
* xorg-xrdb should be fixed (rebuilt) instead, not libxmu
* packages from hax4us repo may be incompatible because of different version/code/patch base.

**Comment by xeffyr** [comment]
These symlinks are not needed on Android OS and latest autotools know this. That is why it missing.
