### ISSUE TITLE
[package request] OpenTTD 

### ISSUE THREAD

**Issue by Auxilus** [termux/x11-packages#102]
**Package description**

OpenTTD is an open source simulation game based upon the popular Microprose game "Transport Tycoon Deluxe"

**Link to home page and sources**
1. https://www.openttd.org
2. Source code: https://github.com/OpenTTD/OpenTTD

**Comment by Auxilus** [comment]
here is the installation steps:

1 download the source
2 modify src/3rdparty/squirrel/squirrel/sqvm.cpp   as

       ```
*** sqvm_original.cpp   Mon Jun  3 15:57:14 2019
--- sqvm.cpp    Mon Jun  3 15:20:47 2019
***************
*** 6,12 ****
--- 6,15 ----

  #include <squirrel.h>
  #include "sqpcheader.h"
+ #pragma push_macro("type")
+ #undef type
  #include <math.h>
+ #pragma pop_macro("type")
  #include "sqopcodes.h"
  #include "sqfuncproto.h"
  #include "sqvm.h"
```

3 configure, make, install
4 download opengfx, opensfx, openmsx
https://binaries.openttd.org/extra/opengfx/0.5.5/opengfx-0.5.5-all.zip
https://binaries.openttd.org/extra/opensfx/0.2.3/opensfx-0.2.3-all.zip
https://binaries.openttd.org/extra/openmsx/0.3.1/openmsx-0.3.1-all.zip

5 unzip to $HOME/.openttd/baseset

**Comment by Auxilus** [comment]
any update on this?

**Comment by xeffyr** [comment]
Just added. Install it with:
```
pkg install openttd
```

**Comment by Auxilus** [comment]
Thanks!
