### ISSUE TITLE
[Package Request] fvwm

### ISSUE THREAD

**Issue by geometryof** [termux/x11-packages#104]
**Package description**
ICCCM-compliant multiple virtual desktop window manager for X
(twm on steroids)

**Link to home page and sources**
1. Home page: http://www.fvwm.org/
2. Source code: https://github.com/fvwmorg/fvwm/releases

**Comment by xeffyr** [comment]
Package is now available.

**Comment by geometryof** [comment]
Finally had a chance to try fvwm.  Installed fine -- but wouldn't start.

First problem: missing libXft.so.
Easy fix: install libxft, which should presumably be added to dependencies.

Second problem: missing libcairo-gobject.so.  I'm currently stuck there,
as libcairo is installed, and libcairo-gobject does not appear to exist.

Possibly related:
xournal also gives a cairo error:
  cannot locate symbol "cairo_xlib_surface_set_size"
  referenced by "/data/data/com.termux/files/usr/lib/libgdk-x11-2.0.so"...

Suggestions?

Thanks as always for developing/maintaining Termux.

TD

**Comment by xeffyr** [comment]
@geometryof It works, if all packages are up-to-date.

**Comment by geometryof** [comment]
Ouch.  Thought I had, but update via had failed.  Had some trouble with the unstable source list, but was eventually able to upgrade.  Both fvwm and xournal now appear to be working (although icons may be missing in xournal).  My bad; thanks again.  (I'm using Android 9.)
