### ISSUE TITLE
[Package Request] luit

### ISSUE THREAD

**Issue by chocobo-recluse** [termux/x11-packages#105]
This utility is the only solution when working with non-utf8 character set in UTF-8 terminal

Luit is a filter that can be run between an arbitrary application and a UTF-8 terminal emulator. It will convert application output from the locale's encoding into UTF-8, and convert terminal input from UTF-8 into the locale's encoding. It is mainly used to support xterm.

Homepage: https://invisible-island.net/luit/
Source code: https://invisible-island.net/datafiles/release/luit.tar.gz

**Additional information**
Have you compiled or tried to compile the package on device?

No

**Comment by xeffyr** [comment]
Moved to x11-packages due to dependencies (libfontenc & xorg-util-macros).

Package is now available, use these commands to install it:
```
pkg install x11-repo
pkg install luit
```

**Comment by LeapofAzzam** [comment]
But when i install it, APT says package not found, when i already installed `x11-repo` package to be provide X11 packages
```bash
$ pkg install luit
Ign:1 https://yadominjinta.github.io/files termux InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Hit:3 https://yadominjinta.github.io/files termux Release
Ign:4 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Hit:5 https://termux.net stable InRelease
Ign:6 https://yadominjinta.github.io/files termux Release.gpg
Ign:7 https://dl.bintray.com/xeffyr/x11-packages-21 x11 InRelease
Get:8 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:8 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:10 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:10 https://dl.bintray.com/grimler/science-packages-21 science Release
Get:12 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release [6055 B]
Hit:12 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
17 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'extras/binary-arm/Packages' as repository 'https://yadominjinta.github.io/files termux InRelease' doesn't support architecture 'arm'
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package luit
$ 
```

**Comment by chocobo-recluse** [comment]
The package name should be xorg-luit
Try "pkg install xorg-luit"
