### ISSUE TITLE
st (simple terminal)

### ISSUE THREAD

**Issue by fproverbio** [termux/x11-packages#106]
**Package description**

very lightweight terminal emulator, goes well with other "suckless" tools.

**Link to home page and sources**
1. Home page: https://st.suckless.org/
2. Source code: https://git.suckless.org/st/files.html

**Comment by RossComputerGuy** [comment]
I got st working myself yesterday so I can fork this repo and submit a pull request, there isn't much needed to get it working.

**Comment by fproverbio** [comment]
> I got st working myself yesterday so I can fork this repo and submit a pull request, there isn't much needed to get it working.

i succesfully built it skipping libutil. doing so creates problems when the window manager that i use (dwm) calls for it (specifically for st). the keybing associated with it doesn't work, and termux outputs:

"error 146: BadPicture request 143 minor 8 serial XXX" where XXX are numbers from 74 to 222
"open terminal failed: not a terminal"

st opens fine when called by dmenu, but keeps telling error 146.

**Comment by RossComputerGuy** [comment]
I think the one built in the repo fixes that, @xeffyr would know since he added a libutil patch.

**Comment by xeffyr** [comment]
Package is now available.

Use this command to install it:
```
pkg install st
```
