### ISSUE TITLE
DWM (dynamic window manager)

### ISSUE THREAD

**Issue by fproverbio** [termux/x11-packages#107]
**Package description**

Tiling window manager from suckless.org using X. The default companion for "st" terminal emulator.

**Link to home page and sources**
1. Home page: https://dwm.suckless.org/
2. Source code: https://git.suckless.org/dwm/files.html

**Comment by RossComputerGuy** [comment]
I'll get to work adding this today, it shouldnt be too hard.

**Comment by xeffyr** [comment]
Package is now available.

Use this command to install it:
```
pkg install dwm
```

**Comment by fproverbio** [comment]
thanks for the package. since the WM is configured via config.h, how can i modify the default configuration? do i have to manually build the termux package with the modified config.h? previously i had to build dwm, st and dmenu from git to get them working with the default keybindings, now they work out of the box with the package but i cannot modify it because there's no config.h file.
thanks

**Comment by xeffyr** [comment]
> how can i modify the default configuration?
do i have to manually build the termux package with the modified config.h?

DWM can be configured through "config.h" header file at compile-time only, so you will need to rebuild package in order to apply configuration changes.

**Comment by donihalim** [comment]
How to compile dwm from source on termux? What dependencies ? Thank you

**Comment by Grimler91** [comment]
@donihalim `apt show dwm` and look for the "Depends:" field.

**Comment by donihalim** [comment]
Already installed those depends, but still got this error
`dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -I@TERMUX_PREFIX@/include -I@TERMUX_PREFIX@/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=6.2 -DXINERAMA
LDFLAGS  = -L@TERMUX_PREFIX@/lib -lX11 -lXinerama -lfontconfig -lXft
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -I@TERMUX_PREFIX@/include -I@TERMUX_PREFIX@/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="6.2" -DXINERAMA drw.c
In file included from drw.c:6:
/data/data/com.termux/files/usr/include/X11/Xft/Xft.h:39:10: fatal error:
      'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~                                                  1 error generated.
make: *** [Makefile:18: drw.o] Error 1`

**Comment by Grimler91** [comment]
> -I@TERMUX_PREFIX@/include

That does not look correct. Replace all `@TERMUX_PREFIX@` with `/data/data/com.termux/files/usr`, using sed or perl or something else

**Comment by donihalim** [comment]
Fixed, thank you very much

**Comment by donihalim** [comment]
[Detail]
Problem solved after changing all `@TERMUX_PREFIX@` to `/data/data/com.termux/files/usr` as suggested by @Grimler91. Thank you.
