### ISSUE TITLE
Qemu bus error past ndk 20

### ISSUE THREAD

**Issue by Auxilus** [termux/x11-packages#109]
**Problem description**

qemu is failing with bus error with even the most simplest bootable

**System information**

Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.14.62-16294683 #1 SMP PREEMPT Tue Jun 25 09:24:36 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-A505F

**Comment by Auxilus** [comment]
latest qemu update seems to be working. Is there more to it? or I can close the issue.

**Comment by xeffyr** [comment]
QEMU is downgraded to 3.1.0.
