### ISSUE TITLE
Can't open emacs

### ISSUE THREAD

**Issue by IntyLab** [termux/x11-packages#120]
This morning, I ran pkg upgrade.  One of the packages upgraded was librsvg.  Then when I tried to open emacs, I got the message:

CANNOT LINK EXECUTABLE "emacs": cannot locate symbol "__clzsi2" referenced by "/data/data/com.termux/files/usr/lib/librsvg-2.so"...

$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.71-13955230 #1 SMP PREEMPT Tue Jun 11 16:12:13 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G935P

**Comment by tomty89** [comment]
There's a commit which is seemingly related: https://github.com/GNOME/librsvg/commit/449fdccaffd316eddb394589008310c327eb31bb#diff-c949f93d03f44a4217d7a138f9e2e54a
The OP it addresses occurs during compile time though. Also it seem to claim that it shouldn't be necessary with rust 1.36. Still we can try it and see.

**Comment by xeffyr** [comment]
> Also it seem to claim that it shouldn't be necessary with rust 1.36. Still we can try it and see.

Isn't Termux already using Rust v1.36 ?

**Comment by Joseph-Riad** [comment]
Same issue here.

$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.112-15805288 #2 SMP PREEMPT Mon Jun 3 14:37:58 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-N960U1

**Comment by tomty89** [comment]
> Isn't Termux already using Rust v1.36 ?
Yes apparently. So either I misunderstood the commit message or the issue wasn't fixed in Rust v1.36 (or perhaps they missed the cross-compiling scenarios or something like that). That's why I suggested that we give the commit a go and see if it helps.

**Comment by xeffyr** [comment]
I have applied this patch on librsvg and it solved problem.
Closing.
