### ISSUE TITLE
Fractional Display Scaling for 1080p Laptops

### ISSUE THREAD

**Issue by CountryfiedLinux** [termux/x11-packages#122]
Fractional display scaling is not available in display settings. For people with 1080p laptop screens everything looks tiny without being able to scale to 125%. For now the best option is to lower the display resolution.

**Comment by xeffyr** [comment]
Where you found display settings ?

**Comment by CountryfiedLinux** [comment]
I searched display in the Whisker menu. There's no options for scaling at all.

**Comment by xeffyr** [comment]
> I searched display in the Whisker menu.

Whisker menu is not available here.
