### ISSUE TITLE
Can't open wm2

### ISSUE THREAD

**Issue by IntyLab** [termux/x11-packages#123]
First, thank you for handling the issue with emacs-x.

I have an old obscure window manager called wm2 which I had previously used back in 1998, and had managed to get compiled and running on my tablet.  I never bothered with a package request for it, since it's an abandoned project.  It is available at http://www.all-day-breakfast.com/wm2/

The other day, I tried to launch it, and I got this error message:

CANNOT LINK EXECUTABLE: could not load library "libXmu.so" needed by "wm2"; caused by could not load library "libXt.so.6" needed by "libXmu.so"; caused by library "libXt.so.6" not found

Meanwhile, I modified my X script to launch Fluxbox instead, so there's no hurry.  I appreciate all your help with these issues.

Here is my termux-info:

Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://its-pointless.github.io/files termux/extras
https://its-pointless.github.io/files termux/extras
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.49-ga5dcd91-00038-g982d285 #1 SMP PREEMPT Thu Mar 9 12:47:14 KST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
5.0.1
Device manufacturer:
LGE
Device model:
LGLK430

**Comment by xeffyr** [comment]
1. `pkg upgrade`
2. Your `wm2` probably should be recompiled.

**Comment by IntyLab** [comment]
Well, that explains why I couldn't compile it for my phone.  Now it won't compile for my tablet either for the same reason.  I guess I can't use it anymore, unless there's a substitute for libXt.so.6.

**Comment by RossComputerGuy** [comment]
Just symlink libXf.so to libXf.so.6On Jul 22, 2019 1:07 PM, Michael Hayes <notifications@github.com> wrote:Well, that explains why I couldn't compile it for my phone.  Now it won't compile for my tablet either for the same reason.  I guess I can't use it anymore, unless there's a substitute for libXt.so.6.

**Comment by IntyLab** [comment]
Perfect.  That did the trick.  Thank you very much!

I guess I should go through the source files and replace all references to libXt.so.6, and then run the Make script again.  I already had to make a few changes to get it to compile in the first place.
