### ISSUE TITLE
Can't run qemu-system-x86_64

### ISSUE THREAD

**Issue by IntyLab** [termux/x11-packages#126]
I installed qemu-system-x86_64 and tried to run it, only to get the error:

CANNOT LINK EXECUTABLE: could not load library "libnettle.so.6" needed by "qemu-system-x86_64"; caused by library "libnettle.so.6" not found

I went to ~/../usr/lib and found libnettle.so.7.0 out there, so I tried doing a symlink, but then qemu gave me this error:

util/cacheinfo.c:179: void init_cache_info(void): assertion "(isize & (isize - 1)) == 0" failed
Aborted

termux-info:

Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://its-pointless.github.io/files termux/extras
https://its-pointless.github.io/files termux/extras
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.49-ga5dcd91-00038-g982d285 #1 SMP PREEMPT Thu Mar 9 12:47:14 KST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
5.0.1
Device manufacturer:
LGE
Device model:
LGLK430

**Comment by xeffyr** [comment]
While libnettle problem can be solved, the 
```
util/cacheinfo.c:179: void init_cache_info(void): assertion "(isize & (isize - 1)) == 0" failed
```
cannot be, at least for now. Thats a know problem and happens on specific devices.

**Comment by strook** [comment]
Well, no my Xeons the cachesize is 64 just:
`     /* There's only a single sysctl for both I/D cache line sizes.  */
     long size;
     size_t len = sizeof(size);

  //   if(!__sysctl_args("hw.cachelinesize", 16, &size, &len, NULL, 0, NULL)) {
         *isize = *dsize = 64;//size;
  //   }
   
     /*
# ifdef _SC_LEVEL1_ICACHE_LINESIZE
    int tmp_isize = (int) sysconf(_SC_LEVEL1_ICACHE_LINESIZE);
    if (tmp_isize > 0) {
        *isize = tmp_isize;
    }
# endif
# ifdef _SC_LEVEL1_DCACHE_LINESIZE
    int tmp_dsize = (int) sysconf(_SC_LEVEL1_DCACHE_LINESIZE);
    if (tmp_dsize > 0) {
        *dsize = tmp_dsize;
    }
# endif
*/`

**Comment by strook** [comment]
for that POSSIX function for arch linux.
