### ISSUE TITLE
Qt5 still not working

### ISSUE THREAD

**Issue by DickyQi** [termux/x11-packages#130]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**System information**

**Comment by DickyQi** [comment]
CANNOT LINK EXECUTABLE "qtplugininfo": cannot locate symbol "_ZN31QInotifyFileSystemWatcherEngine6createEP7QObject" referenced by "/data/data/com.termux/files/usr/lib/libQt5Core.so.5.11.3"...
any qt base app will reproducing

**Comment by xeffyr** [comment]
Should be fixed now - `pkg upgrade`.
