### ISSUE TITLE
Amiwm

### ISSUE THREAD

**Issue by KevinBlue18** [termux/x11-packages#131]
**Package description**
Amiga-styled window manager for retro-videogame enthusiasts.
I love the Amiga but was not old enough to use when it was released. So, I would love to have it.
 
**Link to home page and sources**
1. Home page: https://www.lysator.liu.se/~marcus/amiwm.html
2. Source code: https://github.com/redsPL/amiwm

**Comment by xeffyr** [comment]
One problem here - this package has **non-free** license which is not allowed by hoster (Bintray). Added as disabled package.
