### ISSUE TITLE
[PACKAGE REQUEST] LXDE,  Firefox, Iceweasel,  Midori, Zenity

### ISSUE THREAD

**Issue by LeapofAzzam** [termux/x11-packages#133]
So you already included OpenBox for WM/DE packages, but we want lxde that uses OpenBox too. 
For browsing in Termux, i must using terminal console (aterm) and w3m/lynx. So please include too Firefox,  Iceweasel, and Midori. In case, an X11 program requires Zenity for showing dialog window. Please include too Zenity package.

**Comment by RossComputerGuy** [comment]
Midori is already being worked on, until some things are sorted out midori will not be available.

**Comment by xeffyr** [comment]
Regarding firefox/iceweasel - these packages unlikely to be available in near future.

**Comment by LeapofAzzam** [comment]
Xfce4 already included in xorg  repo

**Comment by LeapofAzzam** [comment]
But LXDE still not in repo
