### ISSUE TITLE
SVG icon theme not works

### ISSUE THREAD

**Issue by 12101111** [termux/x11-packages#139]
**Problem description**

I tried to install some SVG icon theme (for example Papirus or Numix Circle), although I can find and set them in Xfce Appearance, but they doesn't work, the icon theme fallback to Adwaita.
I notice `librsvg` is installed automaticly.
![图片](https://user-images.githubusercontent.com/8438475/63213728-74050880-c142-11e9-9fa1-3f7d3f06f728.png)
PNG icon theme works (Paper)
![图片](https://user-images.githubusercontent.com/8438475/63213474-6732e580-c13f-11e9-8b9a-86bc3a0e8f6c.png)

**Steps to reproduce**

- Download Papirus icon theme from Ubuntu [ppa](https://launchpad.net/~papirus/+archive/ubuntu/papirus/+packages?field.name_filter=papirus-icon-theme)
- Use `dpkg -X` to extract files and move them to `$PREFIX/share/icons`
- Run `gtk-update-icon-cache $PREFIX/share/icons/Papirus-Dark`
- Open Xfce settings -> Appearance -> icons, set to Papirus-Dark
- Icon theme is still Adwaita, nothing changed
- Do same thing for Paper theme, it works.

source of icon theme:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme
https://github.com/snwh/paper-icon-theme

**Expected behavior**

icon should change to Papirus-Dark when select it
**System information**

```output
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://yadominjinta.github.io/files termux/extras
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.14.83-perf #1 SMP PREEMPT Wed Aug 14 20:27:00 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
asus
Device model:
ASUS_I001DA
```

**Comment by xeffyr** [comment]
Should work now, if librsvg and gdk-pixbuf are up to date.

![Screenshot of localhost:1 () at 2020-01-14 00:59:58](https://user-images.githubusercontent.com/25881154/72299414-6f00a280-3669-11ea-8b76-1be5fef8dff1.png)
