### ISSUE TITLE
dbus tries using /tmp to create sockets

### ISSUE THREAD

**Issue by RossComputerPerson** [termux/x11-packages#140]
**Problem description**

**Steps to reproduce**

1. Launch dbus
2. If you try connecting, it wont work. `dbus-cleanup-sockets` proves /tmp is used

**Expected behavior**

Dbus launches

**System information**

This affects all devices regardless of hardware.

**Comment by RossComputerGuy** [comment]
I believe `--with-session-socket-dir=dirname` is needed in the configure lines, Im testing this right now.

**Comment by xeffyr** [comment]
Thanks, I will look on that.

**Comment by RossComputerGuy** [comment]
Running `dbus-monitor --system` with a system bus running results in an error:

```
Failed to open connection to system bus: Failed to connect to socket /data/data/com.termux/files/usr/var/run/dbus/system_bus_socket: No such file or directory
```

Grepped for DBUS variables:
```
DBUS_SESSION_BUS_ADDRESS='unix:abstract=/data/data/com.termux/files/usr/tmp/dbus-Z4vKZzlZvM,guid=387de185fc9658c0f10fa9845d59950b'
DBUS_SESSION_BUS_PID=14689
DBUS_SESSION_BUS_WINDOWID=2097153
```

**Comment by RossComputerGuy** [comment]
Listing contents of $PREFIX/tmp results in showing nothing

**Comment by xeffyr** [comment]
> Failed to open connection to system bus: Failed to connect to socket /data/data/com.termux/files/usr/var/run/dbus/system_bus_socket: No such file or directory

Probably postinst script will be needed.
Or create directory manually.

>unix:abstract=/data/data/com.termux/files/usr/tmp/dbus-Z4vKZzlZvM

> Listing contents of $PREFIX/tmp results in showing nothing

Abstract sockets **invisible**.

**Comment by RossComputerGuy** [comment]
This needs to be fixed too which can be done by configure:

```
dbus-daemon[18381]: Failed to start message bus: Could not get UID and GID for username "messagebus"
```

**Comment by xeffyr** [comment]
> This needs to be fixed too which can be done by configure:

This can't be done by configure.
Switching UID/GID require root.

**Comment by RossComputerGuy** [comment]
I though I saw a thing in configure that sets the message bus user to use.

**Comment by xeffyr** [comment]
There is such option, but it specifies a user to which dbus will drop privileges.
System-wide dbus intended to be launched as root user, then it drops to `messagebus` or `dbus` (like on my OS).

**Comment by RossComputerGuy** [comment]
Ah so then we need to go with patching that.

**Comment by RossComputerGuy** [comment]
If the socket file does exist then using stat should show it exists? I wrote this little thing which gets the path to the socket `echo $DBUS_SESSION_BUS_ADDRESS | cut -f2 -d'=' | cut -f1 -d','`, I put it through stat and stat said it doesn't exist.

**Comment by xeffyr** [comment]
Abstract unix socket is not a file.
You need to use `netstat`.

**Comment by RossComputerGuy** [comment]
I tried the snippet on my server and desktop and it worked without netstat. Running it like this `netstat | grep $(echo $DBUS_SESSION_BUS_ADDRESS | cut -f2 -d'=' | cut -f1 -d',')` shows the socket does not exist.

**Comment by xeffyr** [comment]
```
[xeffyr]:~:$ echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/1000/bus
```

Your was:
```
DBUS_SESSION_BUS_ADDRESS='unix:abstract=/data/data/com.termux/files/usr/tmp/dbus-Z4vKZzlZvM,guid=387de185fc9658c0f10fa9845d59950b'
```

There is a difference between `unix:path` and `unix:abstract`.

**Comment by xeffyr** [comment]
```
unix  2      [ ACC ]     SEQPACKET  LISTENING     16464    -                    /dev/socket/logdr
unix  2      [ ACC ]     STREAM     LISTENING     14923412 12042/dbus-daemon    @/data/data/com.termux/files/usr/tmp/dbus-V7bDwSKzm5
unix  2      [ ACC ]     STREAM     LISTENING     22886    -                    /dev/socket/netd
```

Notice the `@` at path prefix.

**Comment by RossComputerGuy** [comment]
That makes sense but why is it not showing up in netstat even though the daemon is running?

**Comment by xeffyr** [comment]
Try to execute some dbus commands, e.g.:
```
~ $ dbus-send --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
```

For me it shows:
```
method return time=1566156393.549244 sender=org.freedesktop.DBus -> destination=:1.4 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string ":1.4"
   ]
```

**Comment by RossComputerGuy** [comment]
I get this:

```
method return time=1566156532.629367 sender=org.freedesktop.DBus -> destination=:1.0 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string ":1.0"
   ]
```

My code in https://github.com/ronixos/rochell/blob/master/src/main.c must be wrong bc it says its trying to connect to dbus but it never connects.

**Comment by RossComputerGuy** [comment]
And I fixed my code, so everything seems to work (mostly).
