### ISSUE TITLE
feh throwing "Bad System Call" exception

### ISSUE THREAD

**Issue by IntyLab** [termux/x11-packages#148]
I'm suddenly getting the error "Bad System Call" when I try to run feh.  I tried running my program that uses SDL and it's working fine.  I checked .bash_profile and my call to feh in my scripts, but I don't see anything wrong.  I don't know whether it's feh or my environment at this point.

termux_info:
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.71-13955230 termux/termux-packages#1 SMP PREEMPT Tue Jun 11 16:12:13 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G935P

**Comment by IntyLab** [comment]
"feh --bg-max -z *.jpg"

"log" is posted here:
https://drive.google.com/file/d/1-DzfajSGcgX2KRZq831Ehw0Q_ng4tDlu/view?usp=drivesdk

**Comment by xeffyr** [comment]
Ok, thanks.

Again shmget problem:
```
shmget(IPC_PRIVATE, 1458000, IPC_CREAT|0666 <unfinished ...>
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x700237ecf0, si_syscall=__NR_shmget, si_arch=AUDIT_ARCH_AARCH64} ---
```

**Comment by xeffyr** [comment]
Do `pkg upgrade` and check whether `feh` still crashes or not.

**Comment by IntyLab** [comment]
Okay, it's working again now.  Thank you.
