### ISSUE TITLE
Lyx What you see is what you mean LaTeX editor

### ISSUE THREAD

**Issue by lukas-buergi** [termux/x11-packages#152]
**Package description**

What you see is what you mean LaTeX editor. Very powerful for quickly writing LaTeX documents. The main thing that's missing from Termux for me.

Its gui is QT and the other main dependency is LaTeX, both of which are already packaged. But there is probably still a handful of missing dependencies.

**Link to home page and sources**
1. Home page: https://www.lyx.org/
2. Source code: git://git.lyx.org/lyx or https://www.lyx.org/Download for tarballs of stable versions.

**Comment by TT44bb** [comment]
I tried copying the build.sh of qgit hoping that way the qt-dependency would already be resolved but couldn't make it work so far:
```
TERMUX_PKG_HOMEPAGE=https://www.lyx.org
TERMUX_PKG_DESCRIPTION="Lyx is a LaTeX editor"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER=""
TERMUX_PKG_VERSION=2.3.3
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://ftp.lip6.fr/pub/lyx/stable/2.3.x/lyx-2.3.3.tar.gz
TERMUX_PKG_SHA256=ec8027a0ee8d4d35d2d02e9c8edefb0e873e09347fbc11f6734cebca998d7d48
TERMUX_PKG_DEPENDS="qt5-base"
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_configure() {
    export QTDIR="${TERMUX_PREFIX}/lib/cmake/Qt5"
    ./configure --host="${TERMUX_ARCH}" --enable-qt5 --prefix="${TERMUX_PREFIX}"
}
```
but this fails with

> configure: error: cannot compile a simple Qt executable. Check you have the right $QTDIR.

(using the provided docker image, on x86 Debian)

**Comment by TT44bb** [comment]
Gave it another go. Realized there is actually a log file generated by configure (big shock, yes).

config.log: https://gist.github.com/TT44bb/f77b7c4b47c537aeb7c1ab489337663a

After some trial and error and creating some symlinks
`ln -s qt Qt; for f in qt/Qt*; do ln -s $f; done`
(which I realize I very likely shouldn't need to create)

I managed to go from QT headers not found to a linker error:
```
configure:10933: g++ -o conftest  -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/Qt -I/data/data/com.termux/files/usr/incl
ude/QtCore -I/data/data/com.termux/files/usr/include/QtGui -I/data/data/com.termux/files/usr/include/QtWidgets -I/data/data/com.termux/files/usr/include/QtSvg
-I/data/data/com.termux/files/usr/include/QtConcurrent -I/data/data/com.termux/files/usr/include/QtMacExtras -L/data/data/com.termux/files/usr/lib     conftest
.cpp  -lSM -lICE   -lX11  -framework QtCore -framework QtGui >&5                                                                                               /data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: -f may not be used without -shared                                                               clang-8: error: linker command failed with exit code 1 (use -v to see invocation)                                                                              configure:10933: $? = 1
```

But still the same overall error.

**Comment by xeffyr** [comment]
I'm in doubt that option `-framework` is supported by binutils.

**Comment by xeffyr** [comment]
There another error related to qt:
```
g++ -o conftest  -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/Qt -I/data/data/com.termux/files/usr/include/QtCore -I/data/data/com.termux/files/usr/include/QtGui -I/data/data/com.termux/files/usr/include/QtWidgets -I/data/data/com.termux/files/usr/include/QtSvg -I/data/data/com.termux/files/usr/include/QtConcurrent -I/data/data/com.termux/files/usr/include/QtMacExtras -L/data/data/com.termux/files/usr/lib     conftest.cpp  -lSM -lICE   -lX11  -lQt5Widgets >&5
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/conftest-b9e59a.o: undefined reference to symbol '_ZN10QArrayData10deallocateEPS_mm@@Qt_5'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/lib/libQt5Core.so.5: error adding symbols: DSO missing from command line
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cargocultprog** [comment]
If you choose to install Arch Linux ARM into Termux, then the Texworks, TeXMaker, and TeXStudio GUI apps work. I do not know about Lyx. Note that Termux has texlive, and Arch has texlive. In Termux (as of today) there is no GUI for texlive. Arch has the GUI, but needs its own texlive (it cannot use the one in Termux, AFAIK). In Arch, you can also view the PDF with Evince.

**Comment by librehat** [comment]
@xeffyr this can be closed now

**Comment by lukas-buergi** [comment]
@librehat Many thanks, I'm going to try using it soon.
