### ISSUE TITLE
emacs-x does not start gui in vnc connection

### ISSUE THREAD

**Issue by cl4rknova** [termux/x11-packages#153]
**Problem description**
emacs-x executed from within vnc connection does not start a gui.
If I start it via rofi oder dmenu nothing happens.
While starting via cli emacs it show emacs loading libraries until
"Loading /data/data/com.termux/files/usr/share/emacs/26.3/lisp/emacs-lisp/site-in"
From there nothing happens. Gui is not opening.

**Steps to reproduce**
install emacs-x, start vncserver, connect via vncclient, open termial, execute "emacs" in terminal
**Expected behavior**
emacs shall open with gui
**System information**
Samsung S9, aarch64, termux with emacs-x installed.

I also recompiled the package with x11-packages - but with the same issue

**Comment by KoraggKnightWolf** [comment]
I can confirm this issue on my own device, a Samsung Galaxy A7 (2018) aarch64 architecture. non rooted, no custom rom nor kernel

**Comment by KoraggKnightWolf** [comment]
The only other GUI IRC client, loqui, has no issues either connecting, they are specifically limited to HexChat on Termux

**Comment by cl4rknova** [comment]
For me this is working again since x11-repo has been updated yesterday.
