### ISSUE TITLE
Text garbled in X programs

### ISSUE THREAD

**Issue by igavronski** [termux/x11-packages#155]
**Problem description**

Text labels and boxes for X programs (for example, gvim) are showing weird characters.
See screenshot:
![Annotation 2019-10-10 181016](https://user-images.githubusercontent.com/14096908/66607057-c9c9c000-eb89-11e9-9390-8d972c669afa.jpg)

**Steps to reproduce**

I am using aterm to a display in my Windows 10 computer running VcXsrv X Server. See the logfile here:

[VCXSrv.0.log](https://github.com/termux/x11-packages/files/3714657/VCXSrv.0.log)

**Expected behavior**

Text showing normally (as of July...)

**System information**

```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.141-perf+ #1 SMP PREEMPT Fri Aug 16 20:58:16 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
asus
Device model:
ASUS_X017DA
$ 

```

**Comment by xeffyr** [comment]
Is text shown properly when using TigerVNC/XSDL/etc... ?

There 2 suspicious things in your log:
```
Warning: Locale not supported by X, falling back to 'C' locale.
```
```
winMultiWindowWMProc - Error code: 3 (Window), ID: 0x00300142, Major opcode: 18 (ChangeProperty), Minor opcode: 0 ((null))
winMultiWindowWMProc - Error code: 3 (Window), ID: 0x00300142, Major opcode: 19 (DeleteProperty), Minor opcode: 0 ((null))
```

**Comment by xeffyr** [comment]
I also should note that fonts are used directly by X server. So if your server can't find necessary fonts, you will probably experience issues.

**Comment by igavronski** [comment]
Problem persists in XSDL
Tried using 'aterm' with the standard font. Same problems.
Any other log or information I can provide you to help with the debugging?

**Comment by adi1090x** [comment]
I'm also having similar issue, right after installing aterm. I'm using vnc viewer btw.
![S91014-021109](https://user-images.githubusercontent.com/26059688/66722191-319d3680-ee28-11e9-9321-2609c578c61a.jpg)

**Comment by adi1090x** [comment]
Fixed it, after installing all xorg-fonts bins & ttf-dejavu, not sure what fixed it, but... Done!
![S91014-023101](https://user-images.githubusercontent.com/26059688/66722437-24ce1200-ee2b-11e9-84de-39c8d7d8f5d2.jpg)

**Comment by xeffyr** [comment]
It just seems GTK is no longer use xorg-fonts and requires TTF fonts to be present. I'll add `ttf-dejavu` as dependency to gtk so issue will no longer happen.

**Comment by xeffyr** [comment]
Fixed.
