### ISSUE TITLE
[Package request] xorg-xeyes

### ISSUE THREAD

**Issue by LeapofAzzam** [termux/x11-packages#157]
**Package description**

xeyes - a follow the mouse X demo, using the X SHAPE extension
xeyes is a graphical computer program showing two googly eyes which follow the cursor movements on the screen as if they were watching it.

**Link to home page and sources**
1. Home page: https://www.x.org/wiki/UserDocumentation/GettingStarted/#xeyes
2. Source code: https://github.com/xyproto/xeyes

**Comment by xeffyr** [comment]
Something that don't have real reason to be included in X11 repository - we have enough "demos" (xclock and xcalc). You can compile xeyes manually if you really need it.
