### ISSUE TITLE
glew

### ISSUE THREAD

**Issue by Alto1772** [termux/x11-packages#159]
**Package description**
Dependency of Mesa3d's Collection of Demos _(and others??? mabye?)_

**Link to the home page**
http://glew.sourceforge.net

**Additional info**
I compiled this for myself and got so many `undefined reference to` errors, can you help me fix this?

**Comment by xeffyr** [comment]
Undefined references can be fixed with https://linx.li/termux-glew-support.patch.

**Comment by xeffyr** [comment]
Package is now available.

Use this command to install it:
```
pkg install glew
```

**Comment by mlocati** [comment]
I'm can't install glew...

![Screenshot_20210112-232300_Termux](https://user-images.githubusercontent.com/928116/104381816-5b627300-552d-11eb-9762-a36adf5339e4.jpg)

**Comment by mlocati** [comment]
Sorry, I forgot to run `pkg install x11-repo`
