### ISSUE TITLE
Problems connecting to VNC

### ISSUE THREAD

**Issue by freetnt5852** [termux/x11-packages#16]
I followed the guide in wiki and started up vnc server and exported the DISPLAY variable and installed aterm, then i tried to connect through the vnc viewer app and everything went fine until after i entered password the connection got disconnected unexpectedly here's logs output from `~/.vnc/localhost:1.log`

```InitConnectionLimits: MaxClients = 2048

Xvnc TigerVNC 1.9.0 - built Oct 28 2018 20:05:34
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12003000, The X.Org Foundation


Tue Oct 30 21:29:07 2018
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
Sync Extension 3.1
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/misc/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/TTF/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/OTF/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/Type1/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/100dpi/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/75dpi/, removing from list!
Popen: `"/data/data/com.termux/files/usr/bin/xkbcomp" -w 1 "-R/data/data/com.termux/files/usr/share/X11/xkb" -xkm "-" -em1 "The XKEYBOARD keymap compiler (xkbcomp) reports:" -emp "> " -eml "Errors from xkbcomp are not fatal to the X server" "/data/data/com.termux/files/usr/tmp/server-1.xkm"', fp = 0xb652fccc
Pclose: fp = 0xb652fccc
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
Errors from xkbcomp are not fatal to the X server
Loaded XKB keymap /data/data/com.termux/files/usr/tmp/server-1.xkm, defined=0x7f
client(0): Reserved pid(32315).
client(0): Reserved cmdname(/data/data/com.termux/files/usr/bin/Xvnc) and cmdargs(:1 -auth /data/data/com.termux/files/home/.Xauthority -desktop localhost:1 () -geometry 1024x768 -pn -rfbauth /data/data/com.termux/files/home/.vnc/passwd -rfbport 5901 -rfbwait 30000).
/data/data/com.termux/files/home/.vnc/xstartup: 11: /data/data/com.termux/files/home/.vnc/xstartup: twm: not found
client(200000): Reserved pid(32325).
client(200000): Reserved cmdname(aterm) and cmdargs(-geometry 80x24+10+10 -ls).
AllocNewConnection: client index = 1, socket fd = 9
aterm: can't load font "7x14"

Tue Oct 30 21:29:28 2018
 Connections: accepted: 127.0.0.1::33405
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
(EE) Segmentation fault at address 0xe
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
XIO:  fatal IO error 11 (Try again) on X server ":1"
      after 1465 requests (1452 known processed) with 0 events remaining.
```

Any ideas? btw I'm on Android 5.1.1

**Comment by xeffyr** [comment]
Can't reproduce this on AArch64/Oreo.

Whats your architecture (`uname -m`) ?

**Comment by freetnt5852** [comment]
@xeffyr armv7l

**Comment by Grimler91** [comment]
I ran into the same error on arm android 7.1. It worked a moment ago though, before I accidently started a second vncserver (but I'm not sure that was the root cause)

**Comment by Grimler91** [comment]
Doesn't work after a device reboot either so I'm guessing the vncserver that worked for me had been running for a couple of days and that some update has broken it since then (so that when I start a new one it doesn't work)

**Comment by xeffyr** [comment]
Got same error on ARM/Android 6.

**Comment by xeffyr** [comment]
Just tried to run it under gdb - got illegal instruction in `libcrypto.so.1.1`.

**Comment by Grimler91** [comment]
@xeffyr That's probably not the reason for the crash, see https://github.com/termux/termux-packages/issues/1660 (arm is annoying)

**Comment by xeffyr** [comment]
To fix that issue, I will had to completely disable GLX. This means that OpenGL won't be available here.

Specifically, these commits should be reverted:

* cd0f20c8bd6f01e7b55491a6009f2826db355a97 (mesa: enable glx via xlib)
* effb70f99fb7d0e3f3010dc926cec4e0ca612922 (tigervnc, xorg-server-xvfb: fix GLX extension by providing 'swrast_dri.so' for these packages)
* a954c554e02b2b8faae3a336101bf5539832c476 (xorg-server-xvfb: disable dri as it is unsupported now)
* bf945ba417bfd2ba661287fa1d4d25cf1da052d0 (mesa-swrast: install file 'dri_interface.h')

Currently, I don't have idea why it works on AArch64 and not on ARM: according to backtrace, there nothing wrong with mesa/glx, but it's configuration has effect somehow. Maybe I need to inspect source code and/or do a deeper debugging.

But current solution is only to disable GLX. If someone needs it, I can create a repository component `experimental` which will have features that considered as unstable.

**Comment by xeffyr** [comment]
Updated packages will be released soon.

**Comment by AnonymousxHacker** [comment]
Not sure what do.
Should we save the configuration files and run them as bash scripts?
