### ISSUE TITLE
mtpaint must be started with proot to avoid bad system call error

### ISSUE THREAD

**Issue by KoraggKnightWolf** [termux/x11-packages#164]
**Problem description**
When executing mtpaint it gives out Bad system call unless run with proot. Executing proot mtpaint leads to the application successfully launching and being fully useable

**Steps to reproduce**
1) startup vncserver -localhost 
2) Either manually start up a window manager e.g. fluxbox or have vncserver start it automatically on bootup via xstartup
3) Execute "mtpaint" in a terminal (without the quotes) and observe how the result is "Bad system call." (once again without the quotes)

**Expected behavior**
mtpaint itself should start up the application without the need of having to use proot mtpaint

**System information**
This issue might be a seccomp issue as the device in question is a Samsung Galaxy A7 2019 with Samsung's One UI for Android 9 (and with the stock OEM Android 9 firmware. Also no custom kernels etc are installed, and the device is not rooted).  This (seccomp) was also the cause of another bug for my device: https://github.com/termux/x11-packages/issues/163

termux-info results: 
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.111-16070901 #1 SMP PREEMPT Tue Aug 27 19:16:00 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-A750FN

**Comment by KoraggKnightWolf** [comment]
Issue appears to have been resolved by upgrading various x11 packages when updates were available. If the issue should reoccur I will reopen this issue but until the time being, it appears fixed.
Thanks a lot for Your time and effort.

Regards,

Koragg

**Comment by KoraggKnightWolf** [comment]
It appears the issue has resurfaced, even though temporarily it seemed resolved. An update of mtpaint has not been able to fix this issue yet again though, thus I am reopening this again.

**Comment by Auxilus** [comment]
@KoraggKnightWolf I'm getting `CANNOT LINK EXECUTABLE "mtpaint": library "libopenjp2.so" not found`.
seems like it's looking for library in system libs (/system/lib64/, /odm/lib64/, /vendor/lib64/).

issue is similar to #182

**Comment by macerg** [comment]
I'm still getting ' bad system call'

**Comment by xeffyr** [comment]
`bad system call` should be now fixed.

> I'm getting CANNOT LINK EXECUTABLE "mtpaint": library "libopenjp2.so" not found.

Linking errors should not happen unless you are mixing packages from repositories targeted at different Android versions.

I don't have `library "libopenjp2.so" not found`.

**Comment by HamidElhilali** [comment]
> @KoraggKnightWolf I'm getting `CANNOT LINK EXECUTABLE "mtpaint": library "libopenjp2.so" not found`.
> seems like it's looking for library in system libs (/system/lib64/, /odm/lib64/, /vendor/lib64/).
> 
> issue is similar to #182

You must install openjpeg, by running :
pkg install openjpeg
