### ISSUE TITLE
Docker : not found

### ISSUE THREAD

**Issue by ProfessorBrain** [termux/x11-packages#165]
I tried to run start-builder.sh and got this error
touch: cannot touch '/tmp/.termux-x11-builder.lck': No such file or directory

I fixed it with changing folder to /data/data/com.termux/files/usr/tmp/.termux-x11-builder.lck

And it worked, but now i have another error, that docker can't run:
./start-builder.sh: 40: ./start-builder.sh: docker: not found

**Comment by xeffyr** [comment]
Make sure you are trying to setup environment on Linux host with Docker installed.
_Note that Docker is not supported in Termux._

**Comment by SDRausty** [comment]
@ProfessorBrain  there is an alternative to docker that runs in Termux PRoot.  It is called udocker: https://www.google.com/search?q=TermuxArch+udocker
