### ISSUE TITLE
Need xhost for opening GUI apps installed in proot-env from termux vnc

### ISSUE THREAD

**Issue by CrackByte** [termux/x11-packages#167]
I was looking for a way to open gimp installed inside an alpinelinux proot-env from inside termux's default vnc when i found this :

https://help.ubuntu.com/community/BasicChroot

(check the "Accessing graphical applications inside the chroot" part)

But for this "xhost" is required which i couldn't find in the x11 packages. So does it exist under any package? if not then i guess this is a package request.

**Comment by xeffyr** [comment]
Are you sure that `xhost` is needed ?
Do you getting some error or just "following tutorial" ?

**Comment by CrackByte** [comment]
Pretty much just "following tutorial".

**Comment by xeffyr** [comment]
I will add a package, however it is not really necessary if you bind your home and tmp directories inside chroot.

**Comment by CrackByte** [comment]
Thanks! Also, how would i bind my home and temp dirs inside chroot though?

**Comment by CrackByte** [comment]
Proot to be specific, i am running a non-rooted phone

**Comment by xeffyr** [comment]
proot has option `-b`.

**Comment by xeffyr** [comment]
Closing as `xhost` is now available via package `xorg-xhost`.
If you decide to use `xhost` make sure that `DISPLAY` is set to `127.0.0.1:1` and vncserver is running with `-listen tcp`.

**Comment by CrackByte** [comment]
Okay, thanks

**Comment by CrackByte** [comment]
The proot command throws an error :

proot error: '/bin/sh' not found (root = /, cwd = /data/data/com.termux/files/home, $PATH=(null))
fatal error: see `proot --help`.

**Comment by xeffyr** [comment]
Your proot command is probably wrong.

I use something like
```
proot --link2symlink -b /dev:/dev -b /proc:/proc -b /sys:/sys -b $HOME:/root -b $PREFIX/tmp:/tmp -r ./alpine -w / -0 /bin/su -l
```

**Comment by CrackByte** [comment]
That worked, thanks
