### ISSUE TITLE
Package Request : RecordMyDesktop, Green-Recorder

### ISSUE THREAD

**Issue by CrackByte** [termux/x11-packages#169]
**Package description**

[ Description ] : Some screen recorders with relatively fewer number of dependencies.

[ Reason to port ] : Because we don't have any screen recorders.

**Link to home page and sources**

1. [ Green-Recorder ] Home page & Source code: https://github.com/mhsabbagh/green-recorder

2. [ RecordMyDesktop ] Home page & Source code: http://recordmydesktop.sourceforge.net/about.php

**Comment by xeffyr** [comment]
Package is now available.

Use this command to install it:
```
pkg install recordmydesktop
```
