### ISSUE TITLE
Tcl/tk and python-tkinter

### ISSUE THREAD

**Issue by segalion** [termux/x11-packages#172]
Could be great talk with androwish people to join efforts to get tcl/tk version inside termux, and then, python tkinter.

Python people are really lost in android world with kivy, p4a, and other projects around, dime if then closed source.

TCL/TK people are more centered (as usually) in a direct android integration, as you can see in androwish project. See i.e [borg](https://www.androwish.org/home/wiki?name=Android+facilities) where termux-api could get some great ideas... (specially bind for events).

**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page: http://tcl.sourceforge.net/

**Comment by xeffyr** [comment]
Added via https://github.com/termux/x11-packages/commit/1adcd790c85ed0fbf650aa85101adaebe6976a32 & https://github.com/termux/termux-packages/commit/5db59c96de6a5e5b446056aa94f8ec19e56f7d26.

**Comment by xeffyr** [comment]
Done.
```
pkg install python-tkinter
```

**Comment by Yuri006** [comment]
now it's not working

**Comment by xeffyr** [comment]
@Yuri006 Could you elaborate, what does it mean `"it's not working"` ? Provide error messages and information how you are trying to use it.

I should note that if you are not running Tkinter program in graphical environment it will not work and this is expected behavior.

**Comment by Yuri006** [comment]
pkg not found

**Comment by xeffyr** [comment]
@Yuri006 Then you are using legacy Termux version.

**Comment by Yuri006** [comment]
Last version

**Comment by xeffyr** [comment]
> Last version

v0.104+ ? If so, seek for mistakes on **your** side.
![Screenshot_20210113-003758_Termux](https://user-images.githubusercontent.com/25881154/104382930-ad0ffb00-5537-11eb-9eb0-3d719250eb44.png)
