### ISSUE TITLE
doesn't exist

### ISSUE THREAD

**Issue by seisdr** [termux/x11-packages#180]
$ pkg search x11
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:4 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:4 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:6 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:6 https://dl.bintray.com/grimler/science-packages-21 science Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Sorting... Done
Full Text Search... Done
$ pkg search x11
Sorting... Done
Full Text Search... Done
$ apt search x11
Sorting... Done
Full Text Search... Done
$ apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$

**Comment by xeffyr** [comment]
Repository **will be disabled** for Android 5 & 6 devices after 01.01.2020.

I no longer provide `x11-repo` package for Android 5 installations so newcomers will not use repository scheduled to be disabled.

**Comment by seisdr** [comment]
My android is 6.0 
Where's the repository ?

**Comment by xeffyr** [comment]
**I no longer provide x11-repo package for Android 5 & 6 (so-called "legacy") installations.**

**Comment by xeffyr** [comment]
You just no longer can install `x11-repo`.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/commit/4fcc7a1269bea751050b77930b5da9f049c63b42
