### ISSUE TITLE
dmenu cannot link"libX11.so"

### ISSUE THREAD

**Issue by JulesdeCube** [termux/x11-packages#182]
**Problem description**
when i want to execute `dmenu` the programe return error about library link.

**pakage install **
- X11
- i3
- xterm
- dmenu

**Steps to reproduce**
use https://wiki.termux.com/wiki/Graphical_Environment to install environent
in i3 open xterm and execute
```
$ dmenu
```
output:
```
CANNOT LINK EXECUTABLE "dmenu": library "libX11.so" not found
```

**Expected behavior**
open dmenu 😄 

**System information**
termux-info
Packages CPU architecture:                             aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main           # science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)                 deb https://dl.bintray.com/grimler/game-packages-24 games stable                                              # x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 mainUpdatable packages:
apt/stable 1.4.9-24 aarch64 [upgradable from: 1.4.9-22]
aterm/x11 1.0.1-15 aarch64 [upgradable from: 1.0.1-13] ca-certificates/stable 20191129 all [upgradable from: 20191016]
dialog/stable 1.3-20191110-0 aarch64 [upgradable from: 1.3-20190808-0]
git/stable 2.24.0 aarch64 [upgradable from: 2.23.0]    gnutls/stable 3.6.11.1 aarch64 [upgradable from: 3.6.10]
gpgv/stable 2.2.18 aarch64 [upgradable from: 2.2.17-1]
i3status/x11 2.13-6 aarch64 [upgradable from: 2.13]
libdrm/x11 2.4.100-2 aarch64 [upgradable from: 2.4.100]
libffi/stable 3.3 aarch64 [upgradable from: 3.2.1-5]
libfontenc/x11 1.1.4-5 aarch64 [upgradable from: 1.1.4-3]
libgnutls/stable 3.6.11.1 aarch64 [upgradable from: 3.6.10]
libice/x11 1.0.10-4 aarch64 [upgradable from: 1.0.10-2]
libidn2/stable 2.3.0 aarch64 [upgradable from: 2.2.0-1]
libnghttp2/stable 1.40.0 aarch64 [upgradable from: 1.39.2]
libsm/x11 1.2.3-8 aarch64 [upgradable from: 1.2.3-6]
libtiff/stable 4.1.0 aarch64 [upgradable from: 4.0.10-10]
libxdamage/x11 1.1.5-5 aarch64 [upgradable from: 1.1.5-3]
libxdmcp/stable 1.1.3-8 aarch64 [upgradable from: 1.1.3-7]
libxfixes/x11 5.0.3-9 aarch64 [upgradable from: 5.0.3-7]
libxfont2/x11 2.0.4-2 aarch64 [upgradable from: 2.0.4]
libxinerama/x11 1.1.4-8 aarch64 [upgradable from: 1.1.4-6]
libxkbcommon/x11 0.9.1-2 aarch64 [upgradable from: 0.9.1]
libxkbfile/x11 1.1.0-5 aarch64 [upgradable from: 1.1.0-3]
libxmu/x11 1.1.3-6 aarch64 [upgradable from: 1.1.3-4]
libxshmfence/x11 1.3-9 aarch64 [upgradable from: 1.3-7]
libxt/x11 1.2.0-5 aarch64 [upgradable from: 1.2.0-3]
libxxf86vm/x11 1.1.4-11 aarch64 [upgradable from: 1.1.4-9]
mesa/x11 17.3.9-14 aarch64 [upgradable from: 17.3.9-12]
nano/stable 4.6 aarch64 [upgradable from: 4.5]
pcre2/stable 10.34 aarch64 [upgradable from: 10.33-1]
psmisc/stable 23.3 aarch64 [upgradable from: 23.2-1]
python/stable 3.8.0-3 aarch64 [upgradable from: 3.8.0-2]
startup-notification/x11 0.12-10 aarch64 [upgradable from: 0.12-8]
tar/stable 1.32-5 aarch64 [upgradable from: 1.32-4]
xcb-util/x11 0.4.0-9 aarch64 [upgradable from: 0.4.0-7]
xcb-util-cursor/x11 0.1.3-8 aarch64 [upgradable from: 0.1.3-6]
xcb-util-image/x11 0.4.0-7 aarch64 [upgradable from: 0.4.0-5]
xcb-util-keysyms/x11 0.4.0-7 aarch64 [upgradable from: 0.4.0-5]
xcb-util-renderutil/x11 0.3.9-7 aarch64 [upgradable from: 0.3.9-5]
xcb-util-wm/x11 0.4.1-7 aarch64 [upgradable from: 0.4.1-5]
xcb-util-xrm/x11 1.3-8 aarch64 [upgradable from: 1.3-6]
xkeyboard-config/x11 2.28-2 all [upgradable from: 2.28]
xorg-font-util/x11 1.3.2-2 aarch64 [upgradable from: 1.3.2]
xorg-fonts-75dpi/x11 1.0.3-9 all [upgradable from: 1.0.3-7]
xorg-fonts-alias/x11 1.0.3-7 all [upgradable from: 1.0.3-5]
xorg-fonts-encodings/x11 1.0.5-4 all [upgradable from: 1.0.5-2]
xorg-mkfontscale/x11 1.2.1-7 aarch64 [upgradable from: 1.2.1-5]
xorg-xauth/x11 1.1-4 aarch64 [upgradable from: 1.1-2]
xorg-xkbcomp/x11 1.4.2-7 aarch64 [upgradable from: 1.4.2-5]
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.14-13712092-QB26321699 #1 SMP PREEMPT Tue Oct 1 10:32:21 KST 2019 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A520F

**Comment by Auxilus** [comment]
in repository version of dmenu is trying to find the ".so" in system libs, recompiled version doesn't have this issue
@xeffyr you may also add "xorgproto" as dependency.

here is strace of repo versio :
```
openat(AT_FDCWD, "/system/lib64/libX11.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/odm/lib64/libX11.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/vendor/lib64/libX11.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by xeffyr** [comment]
Fixed now.
