### ISSUE TITLE
proxychains when executed from vnc

### ISSUE THREAD

**Issue by Auxilus** [termux/x11-packages#186]
**Problem description**
proxychains fails to run given command when executed from vnc (from aterm/st etc.)

`CANNOT LINK EXECUTABLE "ftp": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch" not found`

**Steps to reproduce**
run proxychains from aterm/st

**System information**
android pie
aarch64

**Comment by xeffyr** [comment]
Why `ftp` tries to link with stuff from ruby and why \*.so file name is truncated ?

What is your `$LD_PRELOAD` ?

**Comment by Auxilus** [comment]
It's not just ftp, seems like proxychains fails with every program with same error, its not truncated, there is not '.so'.

$LD_PRELOAD for aterm
```
/data/data/com.termux/files/usr/lib/libtermux-exec.so:/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so:/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so
```

issue can be fixed by resetting LD_PRELOAD to `/data/data/com.termux/files/usr/lib/libtermux-exec.so:/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so`
for some reason there are 3 entries for bigdecimal.so in LD_PRELOAD for terminals in vnc

**Comment by xeffyr** [comment]
> for some reason there are multiple entries for bigdecimal.so in LD_PRELOAD for terminals in vnc

That's normal if you are setting LD_PRELOAD in ~/.bashrc - it loads each time while bash interactive shell is started (Termux + aterm, so 2 times).

**Comment by xeffyr** [comment]
Proxychains allows max 256 characters for LD_PRELOAD path buffer. I guess it can be safely extended to something like `PATH_MAX` to prevent such errors.

**Comment by xeffyr** [comment]
Should be fixed in https://github.com/termux/termux-packages/commit/0316725460e9e99f2842b6766e27da6f68053d9d.

**Comment by Auxilus** [comment]
thanks
