### ISSUE TITLE
xournal fails to run

### ISSUE THREAD

**Issue by Auxilus** [termux/x11-packages#188]
**Problem description**
xournal fails with "Bad system call" 

**System information**
aarch64 Android pie
![Screenshot_20191219-103928_Termux](https://user-images.githubusercontent.com/23075789/71146584-df272e80-224b-11ea-9925-af2537884ef7.jpg)

**Comment by Auxilus** [comment]
seems like issue originates in gtk, I compiled leafpad and got same error

**Comment by Auxilus** [comment]
any lead on this?

**Comment by xeffyr** [comment]
Try to upgrade all packages. It should be fixed by one of https://github.com/termux/x11-packages/commit/00c3cd56f0d54f7d9d89c04c5bcf183b44b2f9b1, https://github.com/termux/x11-packages/commit/a7d6637512c76bd4133670a89c48a9a583bb72ca.
