### ISSUE TITLE
Bad system call when running mtpaint.

### ISSUE THREAD

**Issue by macerg** [termux/x11-packages#189]
Whe running mtpaint I get "bad system call'.
Expected behaviour. mtpaint runs successfully.
My system:-
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Sat Dec 14 20:48:59 CST 2019 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003
![Screenshot_20191221-200814](https://user-images.githubusercontent.com/4559048/71313269-3be23f00-242e-11ea-8262-d8400a3aa00b.jpg)

**Comment by xeffyr** [comment]
No need to repost https://github.com/termux/x11-packages/issues/164.
