### ISSUE TITLE
xterm and aterm: bad system call on Android Pie

### ISSUE THREAD

**Issue by msiniscalchi** [termux/x11-packages#19]
The title says it all. Running up to date Termux and x11-repo with fluxbox and tigervnc, xterm and aterm crash immediately /do not launch. Happening both from the command line within Termux, where "Bad system call" is displayed, and when trying to launch aterm from the fluxbox menu. 

This is on a stock Pixel 3XL running Android Pie

Last few lines from 'strace xterm':

close(3)                                = 0     gettid()                                = 8941
prctl(PR_GET_DUMPABLE)                  = 1 (SUID_DUMP_USER)
prctl(PR_SET_DUMPABLE, SUID_DUMP_USER)  = 0     prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY) = -1 EINVAL (Invalid argument)                        clone(child_stack=0x7ca5becfe0, flags=CLONE_VM|CLONE_SIGHAND|CLONE_THREAD|CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID, child_tidptr=0x7ca5d49d04) = 8942                                            futex(0x7ca5d49d04, FUTEX_WAIT, 4294967295, NULL) = -1 EAGAIN (Try again)                       futex(0x7ca5d49d04, FUTEX_WAIT, 8942, NULL) = 0
prctl(PR_SET_DUMPABLE, SUID_DUMP_USER)  = 0     rt_sigaction(SIGSYS, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTART}, {sa_handler=0x7ca5c3e140, sa_mask=~[KILL STOP RTMIN RT_1 RT_2 RT_3], sa_flags=SA_ONSTACK|SA_RESTART|SA_SIGINFO}, 8) = 0
getpid()                                = 8941  gettid()                                = 8941
rt_tgsigqueueinfo(8941, 8941, SIGSYS, {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7ca5a71750, si_syscall=__NR_setresgid, si_arch=AUDIT_ARCH_AARCH64}) = 0
rt_sigreturn({mask=[]})                 = 4294967295
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7ca5a71750, si_syscall=__NR_io_setup, si_arch=0 /* AUDIT_ARCH_??? */} ---      +++ killed by SIGSYS +++
Bad system call

**Comment by xeffyr** [comment]
Should be fixed in https://github.com/termux/x11-packages/commit/21bd5cc7610540f4f7f4193fd81d812520b4bf95.

**Comment by msiniscalchi** [comment]
Perfect, it works! Thanks again!
