### ISSUE TITLE
x11-repo not working for android 10?? 

### ISSUE THREAD

**Issue by AnoRebel** [termux/x11-packages#195]
I'm on a OnePlus 6, Android 10 version 10.3.0, i updated 2 weeks ago, lately as i updated my packages, x11-repo kept failing with a not found error.. So i uninstalled the repo.. But now i wanna install some desktop components and packages but i cant without the repo and the repo isnt available, even when i search for it.. 
See image below: ![My termux](https://i.imgur.com/z5xlE0c.jpg)

**Comment by xeffyr** [comment]
Why you still use `termux.net` on Android 10 ? It is no longer supported as of 01.01.2020.
https://github.com/termux/termux-packages/issues/4467#issue-513023529

I do not provide packages for legacy environment.
