### ISSUE TITLE
QtQuick controls 2

### ISSUE THREAD

**Issue by vestineo** [termux/x11-packages#196]
Qtquick controls 2 is a qt5 module, part of qt5-base, but not available in termux's qt5-base.

**Comment by xeffyr** [comment]
It is intentionally disabled because it is quite problematic to get it built successfully.

**Comment by librehat** [comment]
I know this is a close issue but to add a bit more colour to it, QtQuick Controls 2 uses OpenGL to render. Termux doesn't have GPU enabled OpenGL so that'll have to go via the very old Mesa-17 package... I doubt it'll look smooth (if useable at all)

**Comment by xeffyr** [comment]
> that'll have to go via the very old Mesa-17 package

Mesa can't be updated because Android (API 24) lacks necessary pthread functionality.
