### ISSUE TITLE
Add qt-base packages

### ISSUE THREAD

**Issue by xeffyr** [termux/x11-packages#2]
_From @sr-tream on July 23, 2018 14:13_

It really to long build on android. Please add a binary packages qt-base for Qt5. 

_Copied from original issue: xeffyr/termux-extra-packages#25_

**Comment by Auxilus** [comment]
IIRC @vishalbiswas had compiled qt5 successfully, maybe he can jump in adding it to the repo..

**Comment by vishalbiswas** [comment]
I only did succeed on arm, and haven't been able to try newer versions.

**Comment by xeffyr** [comment]
I was able to get some basic qt5 libraries:
```
builder@83ae54759290:~/.termux-build/qt5/src$ file ./qtbase/lib/*.so
./qtbase/lib/libQt5Core.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, for GNU/Linux 2.6.28, with debug_info, not stripped
./qtbase/lib/libQt5Gui.so:  ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
./qtbase/lib/libQt5Sql.so:  ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
./qtbase/lib/libQt5Xml.so:  ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped
```

But build still fails with this error:
```
aarch64-linux-android-clang++ -c -Xclang -include-pch -Xclang .pch/Qt5Network/c++.pch -I/data/data/com.termux/files/usr/include -isystem /data/data/com.termux/files/usr/include/libandroid-support -I/home/builder/.termux-build/qt5/src/include -I/data/data/com.termux/files/usr/include/freetype2 -I/data/data/com.termux/files/usr/include/fontconfig -I/home/builder/termux-packages/packages/qt5 -Oz -DOPENSSL_API_COMPAT=0x10100000L -Os -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -D_REENTRANT -Wall -W -Wdate-time -fPIC -DQT_NO_USING_NAMESPACE -DQT_NO_FOREACH -DQT_USE_SYSTEM_PROXIES -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_FORCE_ASSERTS -DQT_CORE_LIB -I. -Ikernel -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.11.1 -I../../include/QtNetwork/5.11.1/QtNetwork -I../../include/QtCore/5.11.1 -I../../include/QtCore/5.11.1/QtCore -I../../include/QtCore -I.moc -I../../mkspecs/linux-termux-clang -o .obj/qdnslookup_unix.o kernel/qdnslookup_unix.cpp
kernel/qdnslookup_unix.cpp:73:34: error: unknown type name 'res_state'
typedef void (*res_nclose_proto)(res_state);
                                 ^
kernel/qdnslookup_unix.cpp:75:32: error: unknown type name 'res_state'
typedef int (*res_ninit_proto)(res_state);
                               ^
kernel/qdnslookup_unix.cpp:77:33: error: C++ requires a type specifier for all declarations
typedef int (*res_nquery_proto)(res_state, const char *, int, int, unsigned char *, int);
                                ^
kernel/qdnslookup_unix.cpp:86:26: error: cannot initialize a parameter of type 'int' with an lvalue of type 'struct __res_state *'
        local_res_nclose(pointer);
                         ^~~~~~~
kernel/qdnslookup_unix.cpp:142:24: error: variable has incomplete type 'struct __res_state'
    struct __res_state state;
                       ^
kernel/qdnslookup_unix.cpp:84:39: note: forward declaration of '__res_state'
    static inline void cleanup(struct __res_state *pointer)
                                      ^
kernel/qdnslookup_unix.cpp:170:38: error: use of undeclared identifier 'MAXNS'
            state._u._ext.nsmap[0] = MAXNS + 1;
```

**Comment by vishalbiswas** [comment]
@xeffyr res_state and MAXNS are from resolver library. These errors can be sidestepped by patching in defitions for the manually. (I believe these definitions were added from Nougat).
Maybe we can even use c-ares here.

**Comment by xeffyr** [comment]
Successfully compiled qt5 base libs for AArch64:
[qt5-base_5.11.1_aarch64.deb.gz](https://github.com/termux/x11-packages/files/2381000/qt5-base_5.11.1_aarch64.deb.gz)
[qt5-base-dev_5.11.1_aarch64.deb.gz](https://github.com/termux/x11-packages/files/2381001/qt5-base-dev_5.11.1_aarch64.deb.gz)

But it is still not ready.

**Comment by vishalbiswas** [comment]
@xeffyr in my disabled qt build.sh you will find a post_make_install section which forces a cross build. But there is still something wrong with the built cross tools

**Comment by xeffyr** [comment]
> there is still something wrong with the built cross tools

@vishalbiswas I got at least `illegal instruction` (moc) and `bad system call` (qmake), but thats now fixed. But there is another problem: qmake uses invalid path for mkspec directory (and possible others).

With help of `proot`, I compiled sample Qt program on device and it works:
![qt5_demo1](https://user-images.githubusercontent.com/25881154/45590026-cc32f980-b938-11e8-94eb-da2d09340157.png)

**Comment by vishalbiswas** [comment]
How much of Qt did you manage to build? And what qpa are built?

Great job!

I'm assuming the built gui packages are linked with libmesa. Otherwise you'll get library load conflicts in Nougat. libGLESv3 causes dependency liblzma to load, but the problem there is that we have liblzma from the real package in repo while android ships liblzma from p7zip.

**Comment by xeffyr** [comment]
> How much of Qt did you manage to build? And what qpa are built?

Currently, only 'qtbase' module. As QPA - either VNC or XCB (default) can be used.

> I'm assuming the built gui packages are linked with libmesa. Otherwise you'll get library load conflicts in Nougat.

OpenGL is disabled for now. I will look for such features only when I get a fully working basic tools/libs.

**Comment by xeffyr** [comment]
Ended in building `qmake` tool on device. It can't be cross-compiled properly using build system provided by Qt. But now we have] a working `qmake` for all architectures.

I need to do a few more checks and if ok - I will push *.deb packages to APT repo. Later it will be possible to enable additional features if necessary.

**Comment by xeffyr** [comment]
@sr-tream Package **qt5-base** was added.
