### ISSUE TITLE
Unable to use mpv-x

### ISSUE THREAD

**Issue by Lemon-Hacking** [termux/x11-packages#206]
Giving : 
[stats] Only Lua 5.1 and 5.2 are supported.
[stats] Could not load lua script @stats.lua
[ytdl_hook] Only Lua 5.1 and 5.2 are supported.
[ytdl_hook] Could not load lua script @ytdl_hook.lua
[osc] Only Lua 5.1 and 5.2 are supported.
[osc] Could not load lua script @osc.lua
lua5.2 is already installed using : pkg install lua52

**Comment by cargocultprog** [comment]
Confirmed. If you do not need the functions provided by those Lua scripts, then mpv will play music with these command-line options:

```
mpv --load-stats-overlay=no --osc=no --ytdl=no musicfilename.ogg
```

**Comment by xeffyr** [comment]
Closing as already fixed.
To have video output: `mpv -vo=x11 ./video.mp4`
