### ISSUE TITLE
Package rename: Xfce4

### ISSUE THREAD

**Issue by LeapofAzzam** [termux/x11-packages#210]
In some distro, the package name of Xfce4 is `xfce4`. But, in Termux, the package name is `xfce` only, without 4. Please rename the package. And also redirect the `xfce` package to `xfce4` after rename

**Comment by xeffyr** [comment]
https://github.com/termux/x11-packages/commit/a649e2314d9337b21a6bb6df3f2bc0be1e71e8e7
