### ISSUE TITLE
x2go

### ISSUE THREAD

**Issue by stefanbaur** [termux/x11-packages#211]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Comment by xeffyr** [comment]
Closing as requires perl stuff which we do not packaging:
```
perl-capture-tiny
perl-config-simple
perl-dbd-sqlite
perl-file-basedir
perl-file-readbackwards
perl-file-which
perl-switch
perl-try-tiny
```

**Comment by stefanbaur** [comment]
Hi, Sorry, I hit "Comment" too early, so I had to edit that post, while you closed it in the meantime. Is there anything we (X2Go) can do to provide a repo of our own that will work with Termux?

**Comment by xeffyr** [comment]
Proper packaging of perl modules isn't supported. While it is possible to do it for simple projects by omitting Makefile.PL and doing steps manually, this way is not suitable for complex projects.

**Comment by Grimler91** [comment]
@stefanbaur best for the users is probably if you create a script that runs the necessary steps for installing x2go on device, which I imagine would be something like:

* install dependencies through apt
* install/compile perl dependencies through clan/cpanm (some of them probably needs patches)
* compile x2go

It would then also be possible to create a deb file on device with [termux-create-repo](https://github.com/termux/termux-create-package), or similar tools, which can be distributed (but not in termux repos as we need build.sh scripts for cross compiling).
