### ISSUE TITLE
Fluxbox Fail

### ISSUE THREAD

**Issue by caltrop-3** [termux/x11-packages#218]
**Problem description**
installed x11-repo
installed Xserver XSDL in Android
installed fluxbox
made a script
  5 # fluxbox desktop
  6 # generate menu
  7 fluxbox-generate_menu
  8 # start fluxbox
  9 fluxbox &

way to numerous errors to list

let's just say that fluxbox will not run in Termux

**Steps to reproduce**
always

**Expected behavior**
a working GUI

**System information**
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.112-perf+ #1 SMP PREEMPT Fri Apr 3 09:26:39 CDT 2020 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(7) power

**Comment by xeffyr** [comment]
> way to numerous errors to list

That's completely expected output of `fluxbox` when it is being started. These "errors" are ok:

These "errors" are ok:
![Screenshot_20200527-171046_Termux](https://user-images.githubusercontent.com/25881154/83031439-391ef200-a03d-11ea-9547-d11b0de14d1e.jpg)

> let's just say that fluxbox will not run in Termux

You didn't submitted any proof on this statement.

I see that fluxbox is working:
![Screenshot_20200527-171121_VNC Viewer](https://user-images.githubusercontent.com/25881154/83031556-5f449200-a03d-11ea-95ef-59b6ad3cd545.jpg)

**Comment by xeffyr** [comment]
@caltrop-3 You have ignored my warning in https://github.com/termux/termux-app/issues/1572#issuecomment-630924168 and continuing to submit useless issues to our repositories. I'm banning for 1 month, so you'll have a lot time to learn Termux and understand what bugs are exactly and why error messages not necessarily point on bugs.
