### ISSUE TITLE
xfce4-settings update problem, not previously seen

### ISSUE THREAD

**Issue by cargocultprog** [termux/x11-packages#219]
**Problem description**

Previously installed xfce4, working no problem. But Termux pkg update fails as of June 2, 2020, due to problem with package xfce4-settings. Repeatable. Terminal code:

...
Unpacking xfce4-settings (4.15.1) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/xfce4-settings_4.15.1_arm.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/etc/xdg/xfce4/helpers.rc', which is also in package exo 0.12.11-8
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
...

**Steps to reproduce**

pkg update

This is repeatable with xfce4 installed. But if xfce4 is removed, then pkg update proceeds without problem.

**Expected behavior**

Expected pkg update without error. I have used Termux for many months, so this is not a new user problem.

**System information**

Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.111-17420370 #1 SMP PREEMPT Mon Mar 2 15:38:05 KST 2020 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510

**Comment by xeffyr** [comment]
I guess would be solved with [upcoming](https://github.com/termux/x11-packages/commit/9d73d245448ea040266369cee119582b662e018a) `exo` package update.

**Comment by xeffyr** [comment]
Try `pkg upgrade` now, `exo` v4.15.1 doesn't have the conflicting file anymore.

**Comment by starmice** [comment]
Problem persists:

`[u0_a364@localhost]:~$ pkg upgrade
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:4 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Hit:7 https://dl.bintray.com/grimler/science-packages-24 science Release
Get:8 https://dl.bintray.com/xeffyr/x11-packages x11 Release [6055 B]
Hit:8 https://dl.bintray.com/xeffyr/x11-packages x11 Release
Get:5 https://dl.bintray.com/termux/termux-packages-24 stable Release [6061 B]
Hit:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
Reading package lists... Done[[A
Building dependency tree
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 xfce4 : Depends: xfce4-settings but it is not installed
 xfce4-session : Depends: xfce4-settings but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
[u0_a364@localhost]:~$ apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  xfce4-settings
The following NEW packages will be installed:
  xfce4-settings
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
94 not fully installed or removed.
Need to get 0 B/567 kB of archives.
After this operation, 4723 kB of additional disk space will be used.
Do you want to continue? [Y/n]
(Reading database ... 30913 files and directories currently installed.)
Preparing to unpack .../xfce4-settings_4.15.1_aarch64.deb ...
Unpacking xfce4-settings (4.15.1) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/xfce4-settings_4.15.1_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/etc/xdg/xfce4/helpers.rc', which is also in package exo 0.12.11-8
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/xfce4-settings_4.15.1_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
[u0_a364@localhost]:~$`

**Comment by xeffyr** [comment]
It didn't persist. You have tried to upgrade while your installation was in broken state. You need to uninstall the xfce4 instead of doing `apt --fix-broken install` as that leaves exo on previous version:
```
'/data/data/com.termux/files/usr/etc/xdg/xfce4/helpers.rc', which is also in package exo 0.12.11-8
```
You won't be able to upgrade unless `exo` version is not v4.15.1.

**Comment by xeffyr** [comment]
I also now have installed xfce4 without issues.

**Comment by starmice** [comment]
I tried uninstalling. But no matter what option I use I keep getting the same error.
Even when I try to install something unrelated to xfce4 or exo.

**Comment by xeffyr** [comment]
@starmice You need to somehow install exo **v4.15.1**. I don't know how your installation is messed up, but unless you install the up-to-date package, it will continue to conflict.

**Comment by starmice** [comment]
Ok, I cleared the `/data/data/com.termux/files/usr/var/cache/apt/` and ran --fix-broken again and then it worked... I think maybe something in the cache was broken... Thanks for the help ;)
