### ISSUE TITLE
opencl

### ISSUE THREAD

**Issue by aponthe** [termux/x11-packages#221]
**Package description**

**Link to home page and sources**
1. Home page:https://www.khronos.org/opencl/
2. Source code:https://github.com/KhronosGroup/OpenCL-Headers

**Comment by xeffyr** [comment]
As written in https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests:
> Package should NOT require hardware graphics acceleration or in any way access to GPU hardware device.
