### ISSUE TITLE
TigerVNC not installed due to unmet dependency

### ISSUE THREAD

**Issue by BKCHI-Git** [termux/x11-packages#226]
**Problem description**
TigerVNC is cannot installed, Because of unmet dependency of some Packages.
![image](https://user-images.githubusercontent.com/55882406/93831505-ecc38600-fcad-11ea-8280-6aed6b30f770.png)

I'm using Termux with OpenSSH, so this screenshot's terminal is connected via OpenSSH.

**Steps to reproduce**
pkg install x11-repo
pkg update
pkg install tigervnc

**Expected behavior**
TigerVNC must be installed without error.
( I used it with xfce in last month, and It worked well at that time. )

**System information**

Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main

Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.10.61-14207299 #1 SMP PREEMPT Tue Aug 21 20:52:33 KST 2018 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A710L
$

**Comment by xeffyr** [comment]
Can't confirm the issue.

From your screenshot you have problems with all packages, not just x11 ones (like missing `perl` and `freetype`).

Try `apt update`.
