### ISSUE TITLE
Package Request: Xserver Xephyr

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/x11-packages#230]
**Package description**
An Xserver Xephyr (aka. Xephyr) is an Nested X Server. useful for running desktop environments/window managers in the current X session without logging out.

This is useful for trying out window managers inside XFCE session or other current window manager without having to logout the VNC session

And useful to run Desktop Environments inside PRoot treating it as Virtual Machine (not really) inside the Termux VNC Session. 

**Link to home page and sources**
1. Home page: https://www.freedesktop.org/wiki/Software/Xephyr/
2. Source code: https://gitlab.freedesktop.org/xorg/xserver.git

**Comment by Heasterian** [comment]
I'm not sure about termux, but in my experiance llvmpipe is working better on Xephyr than just Xserver XSDL or VNC (It's working fine, no errors about double-buffer).

**Comment by suhan-paradkar** [comment]
@xeffyr I was able to compile xorg-server with xephyr support ...
Should I create a PR enabling xorg-server??

P.S Xserver Xephyr is now a submodule of xorg-server... you can see that [here](https://www.freedesktop.org/wiki/Software/Xephyr/)
