### ISSUE TITLE
Package request: virtual keyboard (onboard/qvkbd/florence)

### ISSUE THREAD

**Issue by cafehaine** [termux/x11-packages#24]
**Package description**
Onboard is a virtual keyboard for X11. It would allow using the x11 packages with XSDL without a physical keyboard attached.

**Link to home page and sources**
1. Home page: https://launchpad.net/onboard
2. Source code: https://launchpad.net/onboard/+download

**Notes**
I'm suggesting Onboard since I've tried it before on my PC, but similar programs such as [qvkbd](https://github.com/KivApple/qvkbd) or any [other in this list](https://wiki.archlinux.org/index.php/List_of_applications#On-screen_keyboards) would do just fine if easier to port

**Comment by Pigpog** [comment]
Ive been trying to get Florence keyboard to work, but unfortunately I don't know much about compiling, especially not cross-compiling. Seems to just be the standard ./configure and make, so im sure someone could do it. An on screen keyboard would be lovely.

**Comment by xeffyr** [comment]
I have added 'florence' keyboard, package will be available soon. [Qvkbd](https://github.com/KivApple/qvkbd) require d-bus functionality which currently not available.

**Comment by xeffyr** [comment]
Package is now available: `pkg install florence`.

I have tested it a bit, it works. But unstable - I touched something in settings and it segfaulted. I'm leaving this issue open as we need something better than 'florence'.

**Comment by Pigpog** [comment]
Thank you thank you thank you ill try it on DWM

**Comment by Pigpog** [comment]
Hmmm.. I think it might be missing a dependency for me:

`CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "g_main_loop_quit" referenced by "libflorence-1.0.so.1" . . .`

**Comment by xeffyr** [comment]
@Pigpog Which architecture ?

**Comment by Pigpog** [comment]
armv7l

**Comment by xeffyr** [comment]
Something strange... I don't have this on AArch64/ARM.

Is package `glib` installed ?

**Comment by Pigpog** [comment]
It is. I may have messed up my libraries so ill back up everything and start fresh to confirm

**Comment by Pigpog** [comment]
reinstalled termux and installed florence, same error.

**Comment by xeffyr** [comment]
It works on ARM. I just did this on **fresh** Termux:
```
pkg upgrade
pkg install x11-repo
pkg install tigervnc fluxbox florence
```

Console:
![screenshot_20181120-212439](https://user-images.githubusercontent.com/25881154/48803974-17440100-ed1c-11e8-8933-dcb7dfe34fcb.png)

VNC:
![localhost 1 2018-11-20 23 25 59](https://user-images.githubusercontent.com/25881154/48804118-76097a80-ed1c-11e8-87e7-8d5d14111017.png)

***

Errors like `CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "g_main_loop_quit" referenced by "libflorence-1.0.so.1" . . .` usually happens due to binary incompatibility between libraries. My packages compiled against ones from https://github.com/termux/termux-packages so they may not work if you mixing packages from different sources, e.g. official packages + manually compiled.

**Comment by Pigpog** [comment]
Does uninstalling termux not delete the old usr folder?

**Comment by Pigpog** [comment]
How do i make it fresh

**Comment by xeffyr** [comment]
>Does uninstalling termux not delete the old usr folder?
Deletes of course.

I have reproduced problem on Android 5.1.1 (AVD/x86_64). Currently can be solved only by doing:
```
LD_PRELOAD=libglib-2.0.so:libgio-2.0.so florence
```

I will try to rebuild `florence` with static library instead of shared `libflorence-1.0.so.1`.

**Comment by Pigpog** [comment]
I am on 5.1.1 so that would make sense. Thank you

**Comment by Pigpog** [comment]
Works!

**Comment by twaik** [comment]
@xeffyr what do you think about adding matchbox-keyboard?

**Comment by twaik** [comment]
Cool!
