### ISSUE TITLE
Qtile

### ISSUE THREAD

**Issue by The-Dark-Phoenix** [termux/x11-packages#243]
**Description**
xmonad is a tiling window manager for X. Windows are arranged automatically to tile the screen without gaps or overlap, maximising screen use. All features of the window manager are accessible from the keyboard: a mouse is strictly optional. xmonad is written and extensible in Haskell. Custom layout algorithms, and other extensions, may be written by the user in config files. Layouts are applied dynamically, and different layouts may be used on each workspace. 

**Homepage**: https://hackage.haskell.org/package/xmonad
**Source code**: https://github.com/xmonad/xmonad

**Comment by DarkPhoenix2005** [comment]
I just found out that qtile is similar to xmonad and it's also wriiten in python.

**Comment by The-Dark-Phoenix** [comment]
i think awesome wm would be better for beginners and also it much more popular than qtile and xmonad. so i think you guys should work on that. anyways i am closing this issue now.
