### ISSUE TITLE
Xarchiver Segmentation Fault

### ISSUE THREAD

**Issue by akbarri** [termux/x11-packages#246]
**Problem description**
Working Normally before, Broken after "pkg upgrade" on 26 Dec 2020.
```
history.log :

Start-Date: 2020-12-26  00:42:46
Commandline: apt upgrade
Upgrade: dpkg:aarch64 (1.20.5-4, 1.20.5-5), coreutils:aarch64 (8.32-6, 8.32-7), harfbuzz:aarch64 (2.7.2, 2.7.3), apt:aarch64 (2.1.13, 2.1.14-2), libllvm:aarch64 (10.0.1-4, 11.0.0-1), bash:aarch64 (5.1.0-2, 5.1.0-3), termux-tools:aarch64 (0.99, 0.100), clang:aarch64 (10.0.1-4, 11.0.0-1), termux-am:aarch64 (0.3, 0.4), dash:aarch64 (0.5.11.2-4, 0.5.11.2-5), qemu-common:aarch64 (1:5.2.0-1, 1:5.2.0-2)
End-Date: 2020-12-26  00:43:06
```
I don't have any clue which Package is Root Cause.

![Screenshot_20201226-024108_VNC Viewer](https://user-images.githubusercontent.com/72637686/103141480-588f1200-4727-11eb-9979-cd5ec4819859.jpg)

**Steps to reproduce**
[Desktop environment (XFCE)](https://wiki.termux.com/wiki/Graphical_Environment#Desktop_environment_.28XFCE.29) 
pkg install xarchiver

**Expected behavior**
Apps to Run with GUI

**System information**
```
Packages CPU architecture:                              
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main                                               
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)                  
deb https://dl.bintray.com/grimler/game-packages-24 games stable                                                
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main Updatable packages:
All packages up to date                                 
Android version:
10                                                      
Kernel build information:
Linux localhost 4.14.117-19516864 #2 SMP PREEMPT Wed Oct 14 18:18:09 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A705F
```

**Comment by WMCB-Tech** [comment]
That happened the same as well, while clicking on "Archive" Menu, it causes segfaults, but launching it does not crash

**Comment by akbarri** [comment]
> That happened the same as well, while clicking on "Archive" Menu, it causes segfaults, but launching it does not crash



> That happened the same as well, while clicking on "Archive" Menu, it causes segfaults, but launching it does not crash

In my case, cannot launch at all.

**Comment by akbarri** [comment]
- Uninstall Termux Google Play builds
- Install Termux Version 0.105 (105) from F-Droid
Without Backup & Restore Process

**Comment by Yisus7u7** [comment]
I have the version of F-droid, I also fail to segment it xarchiver

**Comment by Yisus7u7** [comment]
There is a good alternative :
pkg install lxqt-archiver
