### ISSUE TITLE
x11 Environment not useable due to lacking symbol

### ISSUE THREAD

**Issue by KoraggKnightWolf** [termux/x11-packages#247]
When attempting to use vncserver -localhost it appears that the desktop environment cannot be started up due to the following issue: 
CANNOT LINK EXECUTABLE "xfce4-session": cannot locate symbol "pargo_font_family_get_face" referenced by "/data/data/com.termux/files/usr/lib/libgtk-3.so"...

The line can be found in $HOME/.vnc/localhost:1.log

1. install the x11-packages repo as per instruction on the Termux website
2. install vncserver
3. make the $HOME/.vnc/xstartup script execute the following:
  xfwm4 &
  startxfce4 &
4. run: vncserver -localhost
5. attempt to use e.g. a third party vnc app like VNC Viewer and observe how the entire desktop is just black

After a short startup time, on this specific device roughly 30-60 seconds,  one should see the desktop in the condition it was since the last time the x11 desktop environment has been started. 

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.177-18671722 #1 SMP PREEMPT Fri Aug 28 19:38:23 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A750FN

**Comment by rakslice** [comment]
I assume this is a typo for `pango_font_family_get_face`? Does the problem go away if you install the `pango` package?

**Comment by KoraggKnightWolf** [comment]
That indeed fixed it up for me, I apparently already had the pango-x package installed, installing pango instead (and thus removing pango-x) resolved my issue. Thanks a lot for pointing me in the right direction!

**Comment by xeffyr** [comment]
@KoraggKnightWolf x11-repo doesn't provide `pango-x` anymore as it had to be replaced with `pango`.

**Comment by rakslice** [comment]
In a sense this is a missing dependency, but it is covered indirectly e.g. `xfce4-session` -> `libxfce4ui` -> `gtk2` -> `pango`, so you won't run into it if your installed packages are up to date
