### ISSUE TITLE
DBus has no installation candidate error

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/x11-packages#248]
**Problem description**
When i about to install xfce4, i got this error saying:
![image](https://user-images.githubusercontent.com/65075766/103455441-4107e880-4d28-11eb-97d3-0d41d877ae1a.png)

And when i try to install dbus, it says no installation candidate

**Steps to reproduce**
1. Enable `x11-repo`
2. `pkg install xfce4`

**Expected behavior**
It should install

**System information**
I'm currently running Android x86_64 in VMware so i couldn't do copy-paste 
![image](https://user-images.githubusercontent.com/65075766/103455512-b7a4e600-4d28-11eb-86e9-485234bef403.png)

**Comment by xeffyr** [comment]
dbus has moved to main repo because needed by non-x11 package. It seems `termux.mentality.rip` has not been updated. Change mirror with `termux-change-repo`.
