### ISSUE TITLE
zenity

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#254]
It would be nice if you would add zenity to create graphical scripts in bash, please add that simple package, it would be very useful

**Comment by Yisus7u7** [comment]
![Screenshot_20210503-110045](https://user-images.githubusercontent.com/64093255/116901278-55d58980-abff-11eb-9f8c-70fe446c6fae.png)

Delete a line in the ./configure that did not allow to generate the make file, everything was going very well, but when I started building it I got this error

**Comment by suhan-paradkar** [comment]
![Screenshot_2021-05-06-16-15-53-85](https://user-images.githubusercontent.com/76830230/117286162-76634500-ae86-11eb-940a-76a83e81c007.jpg)
I was able to compile it from source with a few patches

**Comment by Yisus7u7** [comment]
If it worked for you, if it worked for you, pass the binaries 👀

**Comment by suhan-paradkar** [comment]
@Yisus7u7 its now available at x11-repo...
@xeffyr please close it

**Comment by Yisus7u7** [comment]
Thanks!
