### ISSUE TITLE
Wireshark failed capture

### ISSUE THREAD

**Issue by raphaelgolubev** [termux/x11-packages#255]
**Problem description**
When I try to start capturing wireshark gives an error message: `"Unknown message from dumpcap reading header, try to show it as a string: CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/dumpcap": library "libcap.so.2" not found"`

**Steps to reproduce**
1. `apt update && apt upgrade -y`
2. `pkg install x11-repo`
3. `apt install wireshark-gtk`
4. `pkg install xterm` (for some reason was installed aterm instead of him)
5. `apt install tigervnc`
6. `apt install tigervnc-viewer`
7. `vncserver`
8. `export DISPLAY=":1"`
9. in the application VNC Viewer we establish a connection, enter the password and enter in the console `wireshark-gtk`
10. Choose some interfaces and then press Start

**Expected behavior**
Start the capture process

**System information**
`~ $ termux-info`
`Packages CPU architecture:
aarch64
Subscribed repositories:`
`# sources.list
deb https://termux.mentality.rip/termux-packages-24/ stable main`
`# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable`
`# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable`
`# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main`
`Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf-gaf11d57 #1 SMP PREEMPT Wed Nov 4 01:23:13 CST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8T`

**Comment by kcubeterm** [comment]
Install libcap will solve issue.
