### ISSUE TITLE
Package request: Webkit

### ISSUE THREAD

**Issue by Ludea** [termux/x11-packages#258]
**Package description**

WebKit is a cross-platform web browser engine. On iOS and macOS, it powers Safari, Mail, iBooks, and many other applications.

**Link to home page and sources**
1. Home page: https://webkit.org/
2. Source code: https://github.com/WebKit/WebKit or https://svn.webkit.org/repository/webkit/

**Comment by xeffyr** [comment]
Closing since https://github.com/termux/x11-packages/pull/264 has been merged.

Note that I have renamed package `webkit` to `webkitgtk` which is original name of added package.
