### ISSUE TITLE
Qemu

### ISSUE THREAD

**Issue by bboydanyel27** [termux/x11-packages#259]
qemu-system-x86_64 bugs Downgrade for qemu 4.2.1

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Comment by WMCB-Tech** [comment]
What bugs have you encountered? please give us some more details,

**Comment by xeffyr** [comment]
5.2.x has no noticeable bugs and even has some fixes and enhancements. 4.2.x is worse in all kinds.

Removal of deprecated options is not a big.

Won't fix.

**Comment by bboydanyel27** [comment]
> @ bboydanyel27 Que bugs você encontrou? por favor nos dê mais alguns detalhes,
> 
> No meu dispositivo Android 10 aarch64, o QEMU funciona bem sem problemas (5.2.0)

the problem of qemu 5.0 only occurs on cell phones with 32bits armv7 architecture. the bugs reported in the Whatsapp group are as follows. Windows XP does not start completely hangs on login and mouse stops working. Windows 7 of the infinite black screen after login. ReactOS does not start. solutions I found was to Downgrade with qemu 4.2.1 .deb package

**Comment by xeffyr** [comment]
Neither downgrading nor providing a separate QEMU version would be done. By downgrading, you'll face another kind of issues.
