### ISSUE TITLE
Package request: eterm

### ISSUE THREAD

**Issue by Wjsfj51najdk** [termux/x11-packages#26]

**Comment by xeffyr** [comment]
Eterm has serious issues. Depending on configuration it either can't find fonts or segfaults. On default configuration it looks really weird. Just run `ps`:
![localhost 1 2018-11-14 19 19 45](https://user-images.githubusercontent.com/25881154/48499973-68e31c00-e842-11e8-801d-7023289f1e65.png)

***

### Aterm is the only working and reliable terminal emulator for Termux X11 environment.
