### ISSUE TITLE
can't install glcontext

### ISSUE THREAD

**Issue by ganesh314159** [termux/x11-packages#260]
I was trying to install moderngl and moderngl_window, they got downloaded but when it tried to install glcontext , I got following error
`Building wheels for collected packages: glcontext
  Building wheel for glcontext (setup.py) ... error               ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-f4hfa24j/glcontext_d2acc0e5b75f4259a56d6e0068de7cb2/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-f4hfa24j/glcontext_d2acc0e5b75f4259a56d6e0068de7cb2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-pb9hy6ym                                                          cwd: /data/data/com.termux/files/usr/tmp/pip-install-f4hfa24j/glcontext_d2acc0e5b75f4259a56d6e0068de7cb2/
  Complete output (54 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.9
  creating build/lib.linux-aarch64-3.9/glcontext
  copying glcontext/empty.py -> build/lib.linux-aarch64-3.9/glcontext
  copying glcontext/__init__.py -> build/lib.linux-aarch64-3.9/glcontext
  running build_ext
  building 'glcontext.x11' extension
  creating build/temp.linux-aarch64-3.9
  creating build/temp.linux-aarch64-3.9/glcontext
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.9 -c glcontext/x11.cpp -o build/temp.linux-aarch64-3.9/glcontext/x11.o -fpermissive
  glcontext/x11.cpp:86:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libx11", "glversion", NULL};
                                  ^
  glcontext/x11.cpp:86:41: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libx11", "glversion", NULL};
                                          ^
  glcontext/x11.cpp:86:50: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libx11", "glversion", NULL};
                                                   ^
  glcontext/x11.cpp:86:60: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libx11", "glversion", NULL};
                                                             ^
  glcontext/x11.cpp:473:21: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'void (GLContext *)'
      {Py_tp_dealloc, GLContext_dealloc},
                      ^~~~~~~~~~~~~~~~~
  4 warnings and 1 error generated.
  building 'glcontext.egl' extension
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.9 -c glcontext/egl.cpp -o build/temp.linux-aarch64-3.9/glcontext/egl.o -fpermissive
  glcontext/egl.cpp:82:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                  ^
  glcontext/egl.cpp:82:41: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                          ^
  glcontext/egl.cpp:82:50: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                                   ^
  glcontext/egl.cpp:82:60: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                                             ^
  glcontext/egl.cpp:82:73: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
      static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                                                          ^
  glcontext/egl.cpp:188:23: error: cannot initialize a variable of type 'EGLDeviceEXT *' (aka 'void **') with an rvalue of type 'void *'
          EGLDeviceEXT* devices = malloc(sizeof(EGLDeviceEXT) * num_devices);
                        ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  glcontext/egl.cpp:290:21: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'void (GLContext *)'
      {Py_tp_dealloc, GLContext_dealloc},
                      ^~~~~~~~~~~~~~~~~
  5 warnings and 2 errors generated.
  error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for glcontext
  Running setup.py clean for glcontext
Failed to build glcontext
Installing collected packages: glcontext
    Running setup.py install for glcontext ... |^[Oerror
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-f4hfa24j/glcontext_d2acc0e5b75f4259a56d6e0068de7cb2/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-f4hfa24j/glcontext_d2acc0e5b75f4259a56d6e0068de7cb2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-vjojuegf/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.9/glcontext
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-f4hfa24j/glcontext_d2acc0e5b75f4259a56d6e0068de7cb2/
    Complete output (54 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.9
    creating build/lib.linux-aarch64-3.9/glcontext
    copying glcontext/empty.py -> build/lib.linux-aarch64-3.9/glcontext
    copying glcontext/__init__.py -> build/lib.linux-aarch64-3.9/glcontext
    running build_ext
    building 'glcontext.x11' extension
    creating build/temp.linux-aarch64-3.9
    creating build/temp.linux-aarch64-3.9/glcontext
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.9 -c glcontext/x11.cpp -o build/temp.linux-aarch64-3.9/glcontext/x11.o -fpermissive
    glcontext/x11.cpp:86:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libx11", "glversion", NULL};
                                    ^
    glcontext/x11.cpp:86:41: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libx11", "glversion", NULL};
                                            ^
    glcontext/x11.cpp:86:50: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libx11", "glversion", NULL};
                                                     ^
    glcontext/x11.cpp:86:60: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libx11", "glversion", NULL};
                                                               ^
    glcontext/x11.cpp:473:21: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'void (GLContext *)'
        {Py_tp_dealloc, GLContext_dealloc},
                        ^~~~~~~~~~~~~~~~~
    4 warnings and 1 error generated.
    building 'glcontext.egl' extension
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.9 -c glcontext/egl.cpp -o build/temp.linux-aarch64-3.9/glcontext/egl.o -fpermissive
    glcontext/egl.cpp:82:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                    ^
    glcontext/egl.cpp:82:41: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                            ^
    glcontext/egl.cpp:82:50: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                                     ^
    glcontext/egl.cpp:82:60: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                                               ^
    glcontext/egl.cpp:82:73: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        static char * keywords[] = {"mode", "libgl", "libegl", "glversion", "device_index", NULL};
                                                                            ^
    glcontext/egl.cpp:188:23: error: cannot initialize a variable of type 'EGLDeviceEXT *' (aka 'void **') with an rvalue of type 'void *'
            EGLDeviceEXT* devices = malloc(sizeof(EGLDeviceEXT) * num_devices);
                          ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    glcontext/egl.cpp:290:21: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'void (GLContext *)'
        {Py_tp_dealloc, GLContext_dealloc},
                        ^~~~~~~~~~~~~~~~~
    5 warnings and 2 errors generated.
    error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-f4hfa24j/glcontext_d2acc0e5b75f4259a56d6e0068de7cb2/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-f4hfa24j/glcontext_d2acc0e5b75f4259a56d6e0068de7cb2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-vjojuegf/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.9/glcontext Check the logs for full command output.`
  , please help me to install glcontext on termux!

**Comment by xeffyr** [comment]
I do not provide here support for side (not added to x11-repo) software, sorry.

Btw, I guess, your error should be fixable by doing proper type casting, though I won't do the patching on my own. Or you can try gcc from https://github.com/its-pointless/its-pointless.github.io/ - gcc usually less strict about coding issues than clang.
