### ISSUE TITLE
undefined reference to lzma with webkit2gtk

### ISSUE THREAD

**Issue by Ludea** [termux/x11-packages#267]
**Problem description**

When building a rust project with webkit2gtk, I get `note: /data/data/com.termux/files/usr/bin/ld: /system/lib64/libunwindstack.so: undefined reference to `Crc64GenerateTable'` and with lzma function too.

* Bugs of outdated packages are NOT ACCEPTED.
* Bugs of legacy (Android 5/6) packages are NOT ACCEPTED.

**Steps to reproduce**

clone webkit and build it on device.

**Expected behavior**

Sucessfull build

**System information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# x11-repo (sources.list.d/x11.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.19.81-perf+ #1 SMP PREEMPT Mon Dec 21 22:45:36 CST 2020 aarch64 Android
Device manufacturer:
OnePlus
Device model:
AC2003
```

**Comment by xeffyr** [comment]
Nothing related to x11 packages or webkit2gtk. Something either injected system libraries into linking path.

Make sure you don't have LD_LIBRARY_PATH set and your build scripts do not involve libs from /system/lib(64).

**Comment by Ludea** [comment]
With `unset LD_LIBRARY_PATH` still have issue

**Comment by Ludea** [comment]
I have to link only $TERMUX_PREFIX lib ?
If I link `/system/lib64/liblzma.so` I get `library "libGL.so" not found` whereas I link `/system/lib64/libOpenSLES.so`

**Comment by leapofazzam123** [comment]
> Make sure you don't have LD_LIBRARY_PATH set and your build scripts do not involve libs from /system/lib(64).

This might be related to #390

**Comment by xeffyr** [comment]
@leapofazzam123 Nope, that's due to Android's *private* variant of libOpenSLES.so.

For successful linking, a variant from NDK sysroot should be used instead.
