### ISSUE TITLE
X11/keysym.h 

### ISSUE THREAD

**Issue by srampv** [termux/x11-packages#27]
this package supports golang automated testing 

**Package description**
I am trying to install golang  https://github.com/go-vgo/robotgo which needs this package

**Link to home page and sources**
1. Home page: https://github.com/go-vgo/robotgo
2. Source code: https://github.com/go-vgo/robotgo

**Comment by srampv** [comment]
here is error I get when I am trying to install golang package using termux

![screenshot_20181116-152354_termux](https://user-images.githubusercontent.com/6702943/48652421-496c0080-e9b4-11e8-9486-01b8879c14bc.jpg)

**Comment by xeffyr** [comment]
I don't see any reason to have it available via x11-packages repository. It can be easily installed via `go get`:
```
pkg upgrade
pkg install clang golang xorgproto libx11-dev libxtst-dev libpng-dev libxcb-dev libxkbcommon-dev libxi-dev
go get github.com/go-vgo/robotgo
```

It have printed some warnings and I got file `~/go/pkg/android_arm64/github.com/go-vgo/robotgo.a`.
