### ISSUE TITLE
Thonny

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#270]
**Package description**
Thonny is a simple python ide available in all distros 

**Link to home page and sources**
1. Home page:
https://thonny.org/
2. Source code:
https://github.com/thonny/thonny

**Comment by WMCB-Tech** [comment]
The only problem is that it is a python-based program, and it's dependencies so it should be Installable via pip, and it won't be packaged in Termux repos unless there's a problem with it

**Comment by xeffyr** [comment]
https://github.com/thonny/thonny/blob/master/requirements.txt

In https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests I have shown my position about python packages. Porting python package will imply porting of dependencies, but in case some of them it's a total headache.

**Comment by Yisus7u7** [comment]
![Screenshot_20210326-121508](https://user-images.githubusercontent.com/64093255/112668857-fb415480-8e2c-11eb-8de5-fc69a54ae1be.png)
With a few editions, thonny run in termux

**Comment by Yisus7u7** [comment]
![Screenshot_20210326-122036](https://user-images.githubusercontent.com/64093255/112669509-cc77ae00-8e2d-11eb-8748-acc4f15a3c55.png)
![Screenshot_20210326-122051](https://user-images.githubusercontent.com/64093255/112669547-d8637000-8e2d-11eb-816c-d10a0ff8adaf.png)
Thonny runs now smoothly, :3, have a good day

**Comment by WMCB-Tech** [comment]
Looks good, i might try that

**Comment by Yisus7u7** [comment]
Well yes, it is very great, it has a python package manager with graphical interface, it gives you details and possible bug fixes, it has a very good debug, it is very good, to a that does not work very excellent the auto completed words, I do not 
know why, but at the moment it is satisfactory
![Screenshot_20210326-124637](https://user-images.githubusercontent.com/64093255/112734279-c5769b80-8f12-11eb-961b-dc7f6c0eac2c.png)
