### ISSUE TITLE
pyglet | d-failure

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#275]
**Problem description**
Hi, I'm trying to run some pyglet programs, install pyglet using pip and it worked, but when you ran the program I get segmentation failure 
![Screenshot_20210401-103306](https://user-images.githubusercontent.com/64093255/113318886-865f9600-92d6-11eb-90fe-274d3331b52e.png)

**System information**

Application version:                                            0.107                                                           Packages CPU architecture:                                      arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable       # unstable-repo (sources.list.d/unstable.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk unstable main
# x11-repo (sources.list.d/x11.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4 x11 main
Updatable packages:
ruby/stable 3.0.0 arm [upgradable from: 2.7.2]
Android version:
8.0.0
Kernel build information:                                       Linux localhost 3.18.71-perf-gb847930 #1 SMP PREEMPT Fri Sep 27 14:15:01 CDT 2019 armv7l Android
Device manufacturer:
motorola
Device model:
moto e5 cruise

**Comment by xeffyr** [comment]
Few ideas why it can fail:
* Variable `DISPLAY` is not set for some reason.
* Requires GLX extension but VNC server doesn't support it.
* There is a some missing functionality in OpenGL implementation.

Please note that OpenGL support in X11 packages for Termux is limited.

As pyglet is not a Termux package, I'm closing this issue.
