### ISSUE TITLE
You can't run proot apps with xhost

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#278]
**Problem description**
Hello, I'm using termux x11 with xfce4, I want to see how to launch a chroot app on this desktop, I followed tutorials from arch wiki and other pages and it doesn't work I get these errors :
![Screenshot_20210408-154202](https://user-images.githubusercontent.com/64093255/114094382-de237180-9881-11eb-9a27-0316cc5f4341.png)
![Screenshot_20210408-154210](https://user-images.githubusercontent.com/64093255/114094417-e5e31600-9881-11eb-9c89-36baf2b64b63.png)
Why does it happen?

**Comment by xeffyr** [comment]
You are specifying wrong DISPLAY. VNC server runs on `:1`, not the `:1.0`. It also not "traditional" Xorg server.

**Comment by Yisus7u7** [comment]
Also, I tried :1, it gives error equally

**Comment by Yisus7u7** [comment]
![Screenshot_20210408-160820](https://user-images.githubusercontent.com/64093255/114096701-b5e94200-9884-11eb-8c57-a30e699adbd3.png)
![Screenshot_20210408-160815](https://user-images.githubusercontent.com/64093255/114096749-c39ec780-9884-11eb-81ca-5831715e723b.png)

**Comment by Yisus7u7** [comment]
![Screenshot_20210408-162226](https://user-images.githubusercontent.com/64093255/114098235-b256ba80-9886-11eb-9ff7-b7433c7f5baa.png)
Ya no, me guie de #167
