### ISSUE TITLE
Bleachbit

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#289]
Bleachbit is an app to remove cache and junk from system, it would be very useful to remove junk cache from termux, python, among others, 

source code:

https://github.com/bleachbit/bleachbit

**Comment by xeffyr** [comment]
This won't be packaged. Please read packaging policy: https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests

Bleachbit is a Python package and also depends on another Python package `python-gobject`.

**Comment by Yisus7u7** [comment]
Oh, okay, but it would be nice if you added an app to manage junk files and cache

**Comment by Yisus7u7** [comment]
A and, sorry to leave the topic, I saw that they added new packages, already install some, but there are packages that when downloading I get ip not found, and they do not download, why?
