### ISSUE TITLE
Synaptic

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#290]
**Package description**
Synaptic is a graphic package manager Very popular, as I read in the documentation it only depends on gtk and apt, and those packages are available in termux 
**Link to home page and sources**
1. Home page: 
https://www.nongnu.org/synaptic/
2. Source code: https://github.com/mvo5/synaptic

**Comment by Yisus7u7** [comment]
Try to compile it, and from what I saw, the build does not carry any problems, the only error is the following : Android: Distribution not supported; I think it would be time to edit the source code and chat it to work in termux, unfortunately I don't know much about c++ 😅

**Comment by Yisus7u7** [comment]
![Screenshot_20220403-101909](https://user-images.githubusercontent.com/64093255/161451190-995b6946-57e7-48f5-92e8-e79d4fb1036e.png)
![Screenshot_20220403-170937](https://user-images.githubusercontent.com/64093255/161451191-34dead6a-4de0-4d9c-8493-effae01d3efc.png)

@xtkoba E achieved that Synaptic starts without root, but there is still a problem, you can not install any package, I already reviewed all the code and did not find how to disable the root for the installation of packages. 

Could you review and see if you can compile it?, adding this package to Termux would be excellent.

**Comment by xtkoba** [comment]
@Yisus7u7 I'm sorry I cannot for now. Thanks!

**Comment by Yisus7u7** [comment]
#732
