### ISSUE TITLE
xhydra

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#291]
xhydra is a very popular password auditing tool available on all Linux distributions, what and compiled into a deb arm package and worked successfully :
![Screenshot_20210503-103610](https://user-images.githubusercontent.com/64093255/116898181-b19e1380-abfb-11eb-811b-8460a0e8d71d.png)
![Screenshot_20210503-103550](https://user-images.githubusercontent.com/64093255/116898187-b2cf4080-abfb-11eb-8cff-406e9d286ae2.png)
The only problem is that I had to script with the parameter cd $PREFIX/bin, Since if xhydra was running out of there, it would give a Patch error.

Source code : 

https://github.com/vanhauser-thc/thc-hydra

**Comment by xeffyr** [comment]
> xhydra is a very popular password auditing tool

Please, no **auditing**, **hacking**, **cracking**, **phishing** tools in my repositories!

**Comment by xeffyr** [comment]
https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests
> Packages must NOT be phishing or pentesting tools. This does not apply for tools with double purpose like Nmap.

**Comment by Yisus7u7** [comment]
Okay, I didn't know, I apologize for bothering 😅
