### ISSUE TITLE
Error opening xfce4-terminal 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#293]
**Problem description**
Hello, after the update, the terminal does not want to open me, I use xfce4, do you know what is happening please? Look:

![Screenshot_20210506-140212](https://user-images.githubusercontent.com/64093255/117351888-e0262380-ae73-11eb-852e-7d59605312fd.png)
![Screenshot_20210506-140205](https://user-images.githubusercontent.com/64093255/117351901-e3211400-ae73-11eb-8bc6-b80b6e1f5014.png)

**Comment by xeffyr** [comment]
Nothing to do with SESSION_MANAGER variable. It seems `libvte` is broken.

**Comment by Yisus7u7** [comment]
Oh, okay, please how do I fix it? 🥺☹️

**Comment by xeffyr** [comment]
```
pkg upgrade
```

**Comment by Yisus7u7** [comment]
Ok, tanks you!
