### ISSUE TITLE
Xmessage doesn't work 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#300]
**Problem description**
When trying to use xmessage, I get this error:

![Screenshot_20210507-150048](https://user-images.githubusercontent.com/64093255/117502656-6fe7d280-af45-11eb-9396-bcd49c57d66b.png)

**Comment by suhan-paradkar** [comment]
It requires libxawas a dependency.. I think...

**Comment by suhan-paradkar** [comment]
Proceed this way...
```
wget https://gitlab.freedesktop.org/xorg/lib/libxaw/-/archive/master/libxaw-master.tar.gz
tar -xvf libxaw-master.tar.gz
cd libxaw-master/
autoreconf --verbose --force --install
./configure --prefix=$PREFIX
make && make install
```

**Comment by Yisus7u7** [comment]
I already did, and no, it gives the same mistake

**Comment by xeffyr** [comment]
Try `pkg upgrade`.
