### ISSUE TITLE
Hardware acceleration inside Termux

### ISSUE THREAD

**Issue by twaik** [termux/x11-packages#31]
We can use GLES inside termux with output to Xserver even if the server does not support it. 
@NotKit did it using lihybris. We do not need libhybris to access libEGL.so or libGLESv2.so. 
The idea is simple: we have some library that wraps libEGL functions. When program tries to eglGetDisplay() on X11 window the wrapper creates the android native window and binds it to X11 window. If xserver does not support drihybris extension it dumps native window image to shmem and sends it to xserver. 

To make it possible inside Termux we will need to use Gralloc or to use GraphicBuffer some way. Also we will need some android headers. Android supports AHardwareBuffers that can be used for this purpose, but it is available only for O+ devices. And that's the main problem. @xeffyr  Can we somehow solve it?

Source code: https://github.com/NotKit/libhybris/tree/x11/hybris/egl/platforms/x11

**Comment by twaik** [comment]
Looks like the native library loaded from java activity (or native activity) can not be linked to libhardware or libgui ( https://android.googlesource.com/platform/bionic/+/d6ee917/linker/linker.cpp#173 ). But I did not check if the library loaded from elf executable can. I'll check it out.

**Comment by szmarczak** [comment]
Even if that would require a Magsik module / root, it would be a great achievement anyway IMO.

**Comment by szmarczak** [comment]
@xeffyr So I guess it's a no go?

**Comment by twaik** [comment]
Hi there. I found an app VMOS. It implements Android container inside APK. It works very fast including graphics. If there anyone who has idea about how they manage gralloc native buffers and windows and/or GLES, please, contact me.

**Comment by khanhduytran0** [comment]
> Hi there. I found an app VMOS. It implements Android container inside APK. It works very fast including graphics. If there anyone who has idea about how they manage gralloc native buffers and windows and/or GLES, please, contact me.

@twaik VMOS seems to use [Anbox](https://github.com/anbox/anbox/issues/1108).

**Comment by xeffyr** [comment]
@khanhduytran0 Even if it uses Anbox, then heavily modded variant.

Normal Anbox versions do not run on Android without root and custom kernel. Android lacks functionality necessary for running LXC container.

**Comment by khanhduytran0** [comment]
Actually, OpenGL ES can be accessed from Termux environment using pbuffer surface. If you load gl4es shared library in `LD_PRELOAD` or `dlopen()`, you could see that gl4es's hardware test successful. ~~maybe you will reply that pbuffer hardware acceleration would not be in termux dev roadmap~~

**Comment by suhan-paradkar** [comment]
@khanhduytran0 I guess gl4es can be easily included.....

**Comment by khanhduytran0** [comment]
> @khanhduytran0 I guess gl4es can be easily included.....

well just build from source...

Another option is Mesa3D Zink for Vulkan-supported devices, but it is slow.
