### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by Proffy01** [termux/x11-packages#312]
![IMG-20210509-WA0044.jpg](https://user-images.githubusercontent.com/83601865/117584818-f566b080-b106-11eb-96ae-695df71258a9.jpg)

**What command can i give to rectify this "no such file or directory in the image"** please contact soon

**Comment by xeffyr** [comment]
That's shell usage issue. Please learn shell scripting or at least check the project's [README](https://github.com/0xarman/T-Phish).
