### ISSUE TITLE
Plank

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#319]
Plank is a beautiful, simple dock 

**Link to home page and sources**
1. Home page:
https://launchpad.net/plank
2. Source code:
https://github.com/ricotz/plank

**Comment by suhan-paradkar** [comment]
Will try...

**Comment by Yisus7u7** [comment]
Try compiling, but plank relies on libgnomemenu3 to work

**Comment by Yisus7u7** [comment]
Plank depends on things that are very difficult to port termux, therefore the best replacement is Cairo-dock

https://github.com/termux/x11-packages/pull/505

**Comment by MRJ-Badshah** [comment]
How use  ca

> Plank depends on things that are very difficult to port termux, therefore the best replacement is Cairo-dock
> 
> #505

How use Cairo-dock

**Comment by Yisus7u7** [comment]
![Screenshot_20211205-081124](https://user-images.githubusercontent.com/64093255/144747954-38d76674-5731-4211-bbaf-72400f342d2f.png)

`cairo-dock -c  &`
