### ISSUE TITLE
Arc-theme

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#333]
**Package description**

Arc-theme is a very popular gtk2/gtk3 theme available on all Linux distros, it has a friendly and modern look. 

And tried to compile it? 

Yes, build it successfully, and make a deb package with the content, luckily arc theme does not need to be compiled for several specific architectures. 

Build an earlier version, as the latest ones request dependencies not yet available in termux. 

![Screenshot_20210518-224432](https://user-images.githubusercontent.com/64093255/118754342-7a9b4500-b82c-11eb-9db9-d787a3b67fba.png)

![Screenshot_20210518-225216](https://user-images.githubusercontent.com/64093255/118754373-8b4bbb00-b82c-11eb-876d-afe78ae36db0.png)

**Link to home page and sources**
1. Source code: https://github.com/jnsh/arc-theme

**Comment by suhan-paradkar** [comment]
Well, arc-theme depends on sassc, which is deprecated...
