### ISSUE TITLE
xfce4-appmenu-plugin and xfce4-windowck-plugin

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#341]
They are add-ons that improve the aesthetics of xfce4, if they are possible to compile but as in termux is not available intltool, it can not be compiled from the cell phone, please add the packages. 
**Link to home page and sources**
1. Source code : 
(xfce4-windowck-plugin) 
https://github.com/cedl38/xfce4-windowck-plugin

2. Source code: 
(xfce4-appmenu-plugin) 
https://github.com/vaurelios/xfce4-appmenu-plugin

**Comment by suhan-paradkar** [comment]
I will try to add these to the existing PR

**Comment by Yisus7u7** [comment]
https://askubuntu.com/questions/66181/how-do-i-enable-the-globalmenu-appmenu-on-xfce-or-lxde

**Comment by Yisus7u7** [comment]
Well, but xfce4-appmenu-plugin I think if it would be worth bringing it, since its appearance is very good, 

pd: compile xfce4-dev-tools in termux for arm, but lacks intltool
