### ISSUE TITLE
How to set font in aterm?

### ISSUE THREAD

**Issue by HoshiYamazaki** [termux/x11-packages#35]
I get this error while using i3 under XServer XSDL:

> aterm: can't load font "7x14"

So I want to change fonts to powerline since I have ZSH with agnoster theme.
How I can do that?
Thanks!

**Comment by xeffyr** [comment]
> aterm: can't load font "7x14"

This is absolutely normal as we don't have `7x14` font. It just will use a different font then if the default one is not found.

I have replaced default `7x14` with a `6x13` so warning will disappear. Do `pkg upgrade`.

> So I want to change fonts to powerline since I have ZSH with agnoster theme.
How I can do that?

You can't. Aterm uses Xorg fonts which are in PCF format. Xorg does not provide powerline fonts.

Existing fonts can be viewed by using command `xlsfonts` from package `xorg-xlsfonts`.
To set a different Aterm font, pick a string from the list obtained from executing `xlsfonts` and pass as `-fn` argument to `aterm`. Example:
```
aterm -fn -bitstream-terminal-medium-r-normal--18-140-100-100-c-110-iso8859-1
```
