### ISSUE TITLE
Please add xfce4-notifyd daemon 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#351]
@xeffyr 
I was making an app when suddenly I came up with the magnificent idea of sending notifications to the termux desktop, but unfortunately, xfce4 of termux does not support this action, only lxqt does it, this is serious, since it is an essential package, can you add it? 
**Link to home page **
1. Home page:
https://docs.xfce.org/apps/notifyd/start

**Comment by Yisus7u7** [comment]
@suhan-paradkar I need it.  🥺 :v

**Comment by Yisus7u7** [comment]
@suhan-paradkar

**Comment by Yisus7u7** [comment]
._.

**Comment by suhan-paradkar** [comment]
xfce4 notiyd daemon currently has a few cross compilation issues...

**Comment by Yisus7u7** [comment]
Ah ok, then I'll look for some notification service that can be compiled In Termux

**Comment by Yisus7u7** [comment]
Avaliable now

`pkg install xfce4-notifyd`
