### ISSUE TITLE
pygobject

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#352]
@xeffyr 

I'm sure you don't accept the packaging of python dependencies, but I'd like, if possible, of course, to bring this package, it's widely used and supports the gtk API.

Their installation from pip fails, and well I know they don't do this but they would appreciate the possibility of them adding the package

**Comment by suhan-paradkar** [comment]
Bud... It requires gobject-introspection...

**Comment by Yisus7u7** [comment]
Yes, I know

**Comment by Yisus7u7** [comment]
@suhan-paradkar I tried to compile it and this is the error I get :

2 warnings generated.
[110/163] Generating gir-glib with a custom command
FAILED: gir/GLib-2.0.gir
/data/data/com.termux/files/home/gobject-introspection/build/build/tools/g-ir-scanner --output=gir/GLib-2.0.gir --no-libtool --quiet --reparse-validate --add-include-path /data/data/com.termux/files/home/gobject-introspection/build/build/gir --add-include-path /data/data/com.termux/files/home/gobject-introspection/gir --identifier-prefix=G --symbol-prefix=g --symbol-prefix=glib --c-include=glib.h --namespace=GLib --nsversion=2.0 --library=glib-2.0 --library=gobject-2.0 --external-library --pkg=glib-2.0 --cflags-begin -I/data/data/com.termux/files/usr/include/glib-2.0 -I/data/data/com.termux/files/usr/lib/glib-2.0/include -DGLIB_COMPILATION -D__G_I18N_LIB_H__ -DGETTEXT_PACKAGE=Dummy --cflags-end /data/data/com.termux/files/usr/include/glib-2.0/gobject/glib-types.h /data/data/com.termux/files/usr/lib/glib-2.0/include/glibconfig.h /data/data/com.termux/files/usr/include/glib-2.0/glib-unix.h /data/data/com.termux/files/usr/include/glib-2.0/glib/galloca.h /data/data/com.termux/files/usr/include/glib-2.0/glib/garray.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gasyncqueue.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gatomic.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbacktrace.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbase64.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbitlock.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbookmarkfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbytes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gcharset.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gchecksum.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gconvert.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdataset.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdate.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdatetime.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdir.h /data/data/com.termux/files/usr/include/glib-2.0/glib/genviron.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gerror.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gfileutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ggettext.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghash.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghmac.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghook.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghostutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n-lib.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n.h /data/data/com.termux/files/usr/include/glib-2.0/glib/giochannel.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gkeyfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/glist.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmacros.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmain.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmappedfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmarkup.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmem.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmessages.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gnode.h /data/data/com.termux/files/usr/include/glib-2.0/glib/goption.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gpattern.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gpoll.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gprimes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gprintf.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gqsort.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gquark.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gqueue.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grand.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grcbox.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grefcount.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grefstring.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gregex.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gscanner.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gsequence.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gshell.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gslice.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gslist.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gspawn.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstdio.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstrfuncs.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstring.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstringchunk.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtestutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gthread.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gthreadpool.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtimer.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtimezone.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtrashstack.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtree.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtypes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gunicode.h /data/data/com.termux/files/usr/include/glib-2.0/glib/guri.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/guuid.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gvariant.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gvarianttype.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gversion.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gversionmacros.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gwin32.h ../../gir/glib-2.0.c
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/gobject-introspection/build/build/tools/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/data/data/com.termux/files/home/gobject-introspection/build/build/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/data/data/com.termux/files/home/gobject-introspection/build/build/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/data/data/com.termux/files/home/gobject-introspection/build/build/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ImportError: dlopen failed: cannot locate symbol "PyExc_RuntimeError" referenced by "/data/data/com.termux/files/home/gobject-introspection/build/build/giscanner/_giscanner.cpython-39.so"...
ninja: build stopped: subcommand failed.
➜  build git:(master)

**Comment by suhan-paradkar** [comment]
Thats where gobject-introspection is currently stuck....

**Comment by Yisus7u7** [comment]
Ok bro

**Comment by suhan-paradkar** [comment]
I guess this issue can be closed...
Pygobject can now be directly installed from pip.....

**Comment by Yisus7u7** [comment]
Hmm..

**Comment by Yisus7u7** [comment]
I don't load the gtk module on installation....
