### ISSUE TITLE
Xfce4-theme-manager 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#353]
Xfce4-theme-manager is an app to edit and change themes in a faster and simpler way, it is app well preinstalled in Xubuntu (the Linux distro that has xfce4), I compiled it in termux and you have to edit some things in it, but if it works 

![Screenshot_20210602-144020](https://user-images.githubusercontent.com/64093255/120542753-1a221100-c3b1-11eb-924a-5f5ae08eb85a.png)

**Link to home page and sources**
2. Source code:
https://github.com/KeithDHedger/Xfce-Theme-Manager

**Comment by suhan-paradkar** [comment]
Can you specify the files that you needed to edit?

**Comment by Yisus7u7** [comment]
I'm not a programmer in C++, or else it wouldn't help, but the app doesn't detect gtk themes, course topics, and window button themes, but icon themes do detect them

**Comment by suhan-paradkar** [comment]
May be some linking issues..

**Comment by Yisus7u7** [comment]
Well, I're left with that. 😅 But the package would be nice to add it, since it offers an easier way to customize xfce4 for the user

**Comment by WMCB-Tech** [comment]
It is kinda redundant, Xfce provides the way of customizing themes, but if that Xfce theme manager has more features than the classic Xfce appearance settings, then it could be added

**Comment by Yisus7u7** [comment]
![Screenshot_20210529-155446](https://user-images.githubusercontent.com/64093255/120650160-1d65dd00-c443-11eb-8aaf-bc2995864971.png)

@WMCB-Tech Yes, I know, and of course you have more options, on my part I still would not be necessary since it will handle xfce4 perfectly, but on the part of the common user it would be of great help

**Comment by Yisus7u7** [comment]
Available now

`pkg install xfce-theme-manager`
