### ISSUE TITLE
Tkinter does not display the images in the window 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#357]
**Problem description***
Tkinter does not load the images, it comes out blank, as if the image exists but is not displayed, why this bug? 

But the icon if you load it...

![Screenshot_20210611-193734](https://user-images.githubusercontent.com/64093255/121760380-1482a480-caf0-11eb-9f79-e916dc3f8ced.png)
![Screenshot_20210611-193745](https://user-images.githubusercontent.com/64093255/121760382-15b3d180-caf0-11eb-8f25-d0a5a1bcf1d8.png)

**Comment by suhan-paradkar** [comment]
To display images you need to `pip install pillow`
for gtk3
or `pip install PIL` for gtk2

**Comment by Yisus7u7** [comment]
Tkinter already brings its own image import module, I don't see why use external libraries... 

The bug from that module, Tk.image

**Comment by suhan-paradkar** [comment]
> Tkinter already brings its own image import module, I don't see why use external libraries...
> 
> The bug from that module, Tk.image

See this example...
https://stackoverflow.com/questions/10133856/how-to-add-an-image-in-tkinter
