### ISSUE TITLE
tint2

### ISSUE THREAD

**Issue by AspirusFromScratch** [termux/x11-packages#359]
**Package Discription:**
tint2 is a simple panel/taskbar made for modern X window managers. It was specifically made for Openbox but it should also work with other window managers (GNOME, KDE, XFCE etc.).
I am requesting this to be added to the repo because it is a really good panel for openbox and it is easy to configure with a GUI
**Link to source:**
[Source Code at Gitlab](https://gitlab.com/o9000/tint2)

**Comment by suhan-paradkar** [comment]
> **Package Discription:**
> tint2 is a simple panel/taskbar made for modern X window managers. It was specifically made for Openbox but it should also work with other window managers (GNOME, KDE, XFCE etc.).
> I am requesting this to be added to the repo because it is a really good panel for openbox and it is easy to configure with a GUI
> **Link to source:**
> [Source Code at Gitlab](https://gitlab.com/o9000/tint2)

Well... I could build it on my device.....
tho it needs some patches.....
will open a PR when I am free

**Comment by Yisus7u7** [comment]
Good that, tint2 would increase the functionaliad of openbox and bspwm, to a one that I keep trying with plank... 

Unfortunately plank requires libgnomemenu3 to compile, so I can't so far.

**Comment by Yisus7u7** [comment]
The build fails me at 52%...

**Comment by suhan-paradkar** [comment]
> The build fails me at 52%...

Thats what I said... it requires patches

**Comment by Yisus7u7** [comment]
Yes

**Comment by layaachmad** [comment]
compiled it
![Screenshot_2021-08-16-10-45-56-035_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/86137443/129508858-474d890e-3b2b-4add-a3c5-9908caba0727.jpg)

**Comment by Yisus7u7** [comment]
Oh, awesome!

**Comment by layaachmad** [comment]
> > The build fails me at 52%...
> 
> Thats what I said... it requires patches

It's doesn't need patches to compile

**Comment by layaachmad** [comment]
tint2 is now available in termux
You may install it

```
pkg install tint2
```

**Comment by Yisus7u7** [comment]
@xeffyr close
