### ISSUE TITLE
Tiger vnc does not detect the password 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#360]
@xeffyr @suhan-paradkar
This error happened today when I updated the termux app to its latest version, after having installed all the tigervnc and lxqt packages, I get this error when starting vncserver:

Tue Jun 15 14:25:31 2021
 SVncAuth:    neither Password nor PasswordFile params set
 SConnection: AuthFailureException: Authentication failure: No password
              configured for VNC Auth
 VNCSConnST:  closing 127.0.0.1::44473: Authentication failure: Authentication
              failure: No password configured for VNC Auth
 EncodeManager: Framebuffer updates: 0
 EncodeManager:   Total: 0 rects, 0 pixels
 EncodeManager:          0 B (1:nan ratio)
 Connections: closed: 127.0.0.1::44473
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:nan ratio)

Tue Jun 15 14:25:32 2021
 Connections: accepted: 127.0.0.1::44474
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Tue Jun 15 14:25:34 2021
 VNCSConnST:  closing 127.0.0.1::44474: Clean disconnection
 EncodeManager: Framebuffer updates: 0
 EncodeManager:   Total: 0 rects, 0 pixels
 EncodeManager:          0 B (1:nan ratio)
 TcpSocket:   unable to get peer name for socket
 Connections: closed: ::0
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:nan ratio)

It won't let you access the vnc server, what will have happened? 

Help please.

**Comment by xeffyr** [comment]
Check what's in your `~/.vnc` directory. Maybe erase it and reconfigure `vncserver` again.

**Comment by Yisus7u7** [comment]
I tried, it doesn't work

**Comment by Yisus7u7** [comment]
I tried deleting that, also use the command `vncpasswd` And I still haven't worked.

**Comment by Yisus7u7** [comment]
Ready it e solved, it is a somewhat strange error..
