### ISSUE TITLE
Wrong Checksum for curl while building

### ISSUE THREAD

**Issue by Yonle** [termux/x11-packages#378]
# Problem description
Recently, Curl SHA256SUM Value just updated. This causing `build-packages.sh` Failed to do it's job.

# Steps to reproduce
In Termux Package building Container, do:
```bash
./build-package.sh somepackage
```

# Expected behavior
![Screenshot_2021_0706_164058](https://user-images.githubusercontent.com/63401712/124583659-81822380-de7d-11eb-946d-5b3bb686e560.png)

**Comment by kcubeterm** [comment]
It has fixed after updating ca-certificates. Try again it should work now.

**Comment by Yonle** [comment]
Let's see. Re-running Github Action...
