### ISSUE TITLE
Package request : RedNoteBook

### ISSUE THREAD

**Issue by glykos** [termux/x11-packages#38]
**Package description**
RedNotebook is a modern desktop journal. It lets you format, tag and search your entries. You can also add pictures, links and customizable templates, spell check your notes, and export to plain text, HTML, Latex or PDF.

I do not have a clue whether some of the requirements are satisfiable at all (for example GtkSourceView). 

**Link to home page and sources**
1. Home page: https://rednotebook.sourceforge.io/
2. Source code: https://github.com/jendrikseipp/rednotebook

**Comment by xeffyr** [comment]
> I do not have a clue whether some of the requirements are satisfiable at all (for example GtkSourceView).

Main problem here is that *rednotebook* is a python package with dependencies like `python-gobject`.
