### ISSUE TITLE
lxappearance

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#382]
**Package description**

lxappearance It is a theme selector independent of the desktop that you use it, it is highly functional, simple and useful, it is perfect to combine with fluxbox, bspwm, i3, openbox or any other WM, I even dare say that it is better than xfce4-aparience 

Works Very well:

![Screenshot_20210714-150925](https://user-images.githubusercontent.com/64093255/125701002-81f30315-22f2-4288-b005-c0f08e394e64.png)

Please add the package 

I won't do it myself because I have to accept that I don't understand, and I don't know how the termux build environment is used. 

**Link to home page and sources**
1. Home page: lxde.org
2. Source code: https://github.com/lxde/lxappearance

**Comment by Yisus7u7** [comment]
@suhan-paradkar It's all yours, it doesn't require patches, I don't think it's hard for you to make the build.sh :)

**Comment by suhan-paradkar** [comment]
Wii try

**Comment by Yisus7u7** [comment]
Thanks

**Comment by Yisus7u7** [comment]
Closed by #384
