### ISSUE TITLE
Cannot link executable "mate-session": library "libXtst.so.6" not found

### ISSUE THREAD

**Issue by Learndev-student** [termux/x11-packages#386]
Error starting mate-session.
![Screenshot_2021-07-17-13-51-49-812_com realvnc viewer android](https://user-images.githubusercontent.com/74010866/126031347-007ada71-9842-44a3-a667-d3882bb3931a.jpg)

**Comment by suhan-paradkar** [comment]
Looks like it needs to be revised to link against newer libx11...

**Comment by Learndev-student** [comment]
Thanks for resolving the issue.
