### ISSUE TITLE
Xfce constantly crashes

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/x11-packages#389]
Xfce crashes with the error:
```
(xfwm4:11639): xfwm4-WARNING **: 15:12:57.623: Unsupported GL renderer (Mesa X11).

(xfsettingsd:11651): xfsettingsd-CRITICAL **: 15:12:57.823: Stored Xfconf properties disable all outputs, aborting.

(Thunar:11664): thunar-WARNING **: 15:12:58.921: Name 'org.xfce.FileManager' lost on the message dbus.

(Thunar:11664): thunar-WARNING **: 15:12:58.922: Name 'org.freedesktop.FileManager1' lost on the message dbus.
fish: Job 1, 'xfce4-session' terminated by signal SIGSEGV (Address boundary error)
```

I always seeing this error whenever xfce crashes, and xfce keeps crashing on my device. i just recently upgraded my device to android 11 probably this might be a cause? i even disabled various battery optimizations and wakelock held

**Steps to reproduce**
1. Install Xfce
2. Launch X11 Server (xsdl or tigervnc)
3. Wait until Xfce closed unexpectedly and becomes blackscreen (if vnc)
4. Check if having the same logs as mine

**Expected behavior**
It shouldn't close it from time to time unexpectedly

**System information**
```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ #1 SMP PREEMPT Tue Jun 22 11:10:36 CST 2021 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1933
```

**Comment by xeffyr** [comment]
Does it worked before `pkg up` on same Android version (11)?

**Comment by WMCB-Tech** [comment]
It works properly when i'm on 10, it didn't crash frequently

**Comment by xeffyr** [comment]
@WMCB-Tech Did you perform `pkg upgrade` recently?

**Comment by WMCB-Tech** [comment]
Yes i did, i even perform fresh install recently to try fixing this problem. but still persists

**Comment by WMCB-Tech** [comment]
this may be a bit off-topic but apparently `adb` is getting killed as well. apprently it keeps disconncting when putting termux in background, maybe this would be an issue with low memory killer that would kill xfce as well?


https://user-images.githubusercontent.com/65075766/126732793-6b907d35-690c-4382-81b8-4433e9eb0b46.mp4

**Comment by xeffyr** [comment]
> maybe this would be an issue with low memory killer that would kill xfce as well?

Nothing to do with LMK. Some manufacturers fighting against background services to make their devices have "longer battery life". Change ROM, preferably to AOSP or Lineage OS, or live with that.

Maybe same case with XFCE. I don't use these packages, so assumed something was broken after dependency updates. Will test it today.

**Comment by xeffyr** [comment]
Yes, segmentation fault happens because `dbus-daemon` has been killed. Was able to reproduce it by manually killing dbus processes as otherwise it works perfectly.

**Comment by WMCB-Tech** [comment]
so apparently `dbus-daemon` it is being killed by android, caused xfce to crash

**Comment by WMCB-Tech** [comment]
i solved it by disabling killer apps via adb that would have killed `dbus-daemon` by any means. disabled and it works again! i can now use xfce again

**Comment by suhan-paradkar** [comment]
Looks like an issue only with oppo android 11 phoned

**Comment by Yonle** [comment]
I think this issue can closed for now?

**Comment by WMCB-Tech** [comment]
Yes
