### ISSUE TITLE
Qt: missing pkg-config files

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [termux/x11-packages#39]
**Problem description**
I'm not able to compile wxWidgets with Qt toolkit.

**Steps to reproduce**
1. Install Qt dev package
2. Run `./configure --enable-unicode --with-qt`

**Expected behavior**
It correctly finds Qt.

**Additional information**
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.71-perf-gb710f0e #1 SMP PREEMPT Mon Oct 8 12:34:52 CEST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.1.0
Device manufacturer:
bq
Device model:
Aquaris X Pro

wxWidgets uses `pkg-config Qt5Core` and the other pkg-config files from Qt.

(And finally: I didn't use the templates in my other issues because GitHub doesn't show them in mobile version.)

**Comment by xeffyr** [comment]
They are installed, but in wrong package:
```
$ dpkg -L qt5-declarative-dev | grep pkgconfig
/data/data/com.termux/files/usr/lib/pkgconfig
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Core.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Network.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Sql.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Xml.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Gui.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Widgets.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Test.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Concurrent.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5PrintSupport.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5X11Extras.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Qml.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Quick.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5QuickTest.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5QuickWidgets.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5Help.pc
/data/data/com.termux/files/usr/lib/pkgconfig/Qt5UiTools.pc
```

> (And finally: I didn't use the templates in my other issues because GitHub doesn't show them in mobile version.)

Okay.

**Comment by xeffyr** [comment]
Updated packages are available for AArch64. Other architectures will be soon.
