### ISSUE TITLE
qt-creator x86_64: plugin depends on non-existent library

### ISSUE THREAD

**Issue by xeffyr** [termux/x11-packages#391]
**Problem description**

In x86_64 build of `qt-creator` package, `libClangTools.so` depends on non-existent library `libc++.so.1`.

**Expected behavior**

It should depend on `libc++_shared.so` just like the aarch64 build variant.

**Comment by librehat** [comment]
Interesting, I feel like I've seen similar issues elsewhere. Might need to force linking against `libc++_shared.so`

**Comment by librehat** [comment]
I don't have a testing device so can you verify whether it's fixed?

**Comment by xeffyr** [comment]
Yes, it is properly linked now.
