### ISSUE TITLE
Package request : tightvncserver

### ISSUE THREAD

**Issue by Learndev-student** [termux/x11-packages#395]
**Package description**
It's a somewhat similar to ```tigervnc``` but is different in ways that it renders more quality in graphics that ```tigervnc```.

**Link to home page and sources**
1. Home page:https://www.tightvnc.com/
2. Source code:https://www.tightvnc.com/download-old.php

**Comment by Learndev-student** [comment]
![Screenshot_2021-07-27-12-40-36-174_com realvnc viewer android](https://user-images.githubusercontent.com/74010866/127111465-815a556b-ca89-4000-b497-e563c6483d15.jpg)
Tightvnc


![Screenshot_2021-07-27-12-31-18-228_com realvnc viewer android](https://user-images.githubusercontent.com/74010866/127111532-696c7d34-c3e8-43c8-9307-21f30fce254c.jpg)
Tigervnc

**Comment by Yonle** [comment]
Seems like you're using `Automatic` quality mode. Try tap `i` button at VNC viewer and set the quality mode as high. As it shows Low quality in Auto mode. 

Also i don't think that tightvnc can solve some major problem.

**Comment by xeffyr** [comment]
Yes, you just need to enable "high quality" in VNC viewer. Nothing specific to `tigervnc` regarding quality.

**Comment by Learndev-student** [comment]
Ok , thanks. I was actually unknown from that.
