### ISSUE TITLE
Kivy Package request

### ISSUE THREAD

**Issue by kmAyushkm** [termux/x11-packages#399]
Please add support for kivy package.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/3209

Not every package could be requested: https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests

**Comment by Yisus7u7** [comment]
Termux does not accept python packages, unless their use is strictly necessary or useful

**Comment by Yisus7u7** [comment]
Besides, kivy requires opengl and other unavailable dependencies, accelerated graphics and many other things more
