### ISSUE TITLE
vim-gtk not starting.

### ISSUE THREAD

**Issue by masterjavaofficial** [termux/x11-packages#404]
**Problem description**

```vim-gtk``` says ```libcanberra.so.0``` link library not found on arm 32 bit.

**Steps to reproduce**

I subscribed to ```x11-repo```, then installed ```xfce4```, ```xfce4-*``` (additional packages), ```tigervnc``` and other related packages. Then installed ```vim-gtk```. After that, I started vncserver in the proper way, viewing it in VNC Viewer app. Now as I open ```xfce4-terminal``` and hit ```vim```, it says **CANNOT LINK EXECUTABLE "vim": library "libcanberra.so.0" not found**

**Expected behavior**

```vim-gtk``` should open with its gtk interface.

**System information**

Application version:
0.117
Packages CPU architecture:
arm                                               Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable                                   # x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-ge92ac2c #1 SMP PREEMPT Mon May 17 22:07:35 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A

**Comment by Yisus7u7** [comment]
run:

`pkg install libcanberra`

to fix this i will correct the package in a few minutes

**Comment by xeffyr** [comment]
Is going to be fixed by https://github.com/termux/x11-packages/commit/ec629aa751fdc873aad71bf5eeec5d479683507c.
