### ISSUE TITLE
dwm warning no locale support 

### ISSUE THREAD

**Issue by fadliCode** [termux/x11-packages#410]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**System information**

**Comment by xeffyr** [comment]
Locales are not supported in Termux.

**Comment by fadliCode** [comment]
Can you tell me how use dwm on termux

**Comment by xeffyr** [comment]
You need to setup a graphical environment as per https://wiki.termux.com/wiki/Graphical_Environment.

Example of launching dwm (assuming all required packages installed):
```
vncserver
export DISPLAY=:1
dwm &
```

Everything else (i. e. using dwm) is on your own. I never used dwm.
