### ISSUE TITLE
[Bug]: Failed to install both qemu-system-x86_64 and qemu-utils at the same time.

### ISSUE THREAD

**Issue by Yonle** [termux/x11-packages#429]
### Problem description

When i'm trying to install both `qemu-system-x86_64` and `qemu-utils` at the same time with apt, Dpkg conflicts occurs

### What steps will reproduce the bug?

Do `apt install qemu-system-x86-64 qemu-utils`

### What is the expected behavior?

```
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/qemu-utils_1%3a6.1.0-1_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/include/qemu-plugin.h', which is also in package qemu-system-x86-64 1:6.1.0
```

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
# game-repo (sources.list.d/game.list)
deb https://deb.kcubeterm.me/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://deb.kcubeterm.me/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://deb.kcubeterm.me/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://deb.kcubeterm.me/termux-root root stable
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ #1 SMP PREEMPT Fri May 28 23:13:48 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1820

```

**Comment by WMCB-Tech** [comment]
You can specify `-o Dpkg::Options::="--force-overwrite"` as a workaround

**Comment by suhan-paradkar** [comment]
Looks like package conflict.. need to add to `TERMUX_PKG_RM_AFTER_INSTALL`

**Comment by LMEToken** [comment]
I have the same problem waiting for a solution

**Comment by LMEToken** [comment]
apt-get -o Dpkg::Options::="--force-overwrite" install qemu-utils

**Comment by Yonle** [comment]
Well. The solution is adding `-o Dpkg::Options::="--force-overwrite"` options. However, this issue will remains open. 

I also see some of package has some of dependencies issue that i can't explain one by one.
