### ISSUE TITLE
[Bug]: OpenGL segmentation fault

### ISSUE THREAD

**Issue by AbdullahBinJahed** [termux/x11-packages#430]
### Problem description

i installed the mesa and mesa-demos then checked the mesa-demos file by ```pkg files mesa-demo``` then tried to run one in vnc, but got sigsevg address out of bound error ...
here's screenshots ...
![Screenshot_2021-09-06-23-54-50-455_com realvnc viewer android](https://user-images.githubusercontent.com/39275638/132252338-3f72fba0-f861-40dc-be38-8c120c5d48d1.jpg)
![Screenshot_2021-09-06-23-57-10-561_com realvnc viewer android](https://user-images.githubusercontent.com/39275638/132252353-0a1cf713-318b-4765-b6df-49bdf7052de3.jpg)

### What steps will reproduce the bug?

```pkg i mesa mesa-demos```
```cd $PREFIX/bin```
```./overlay``` or just run any files by mesa-demos

### System information

termux-info:
```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
apt/stable 2.3.9 arm [upgradable from: 2.3.8]
bison/stable 3.8.1 arm [upgradable from: 3.7.6]
curl/stable 7.79.0 arm [upgradable from: 7.78.0]
dash/stable 0.5.11.5 arm [upgradable from: 0.5.11.4]
golang/stable 3:1.17.1-3 arm [upgradable from: 3:1.16.7-1]
grep/stable 3.7-1 arm [upgradable from: 3.6]
gzip/stable 1.11-3 arm [upgradable from: 1.10-4]
harfbuzz/stable 2.9.1 arm [upgradable from: 2.9.0-1]
imagemagick/stable 7.1.0.7 arm [upgradable from: 7.1.0.5]
less/stable 590 arm [upgradable from: 563]
libass/stable 0.15.2 arm [upgradable from: 0.15.1]
libcurl/stable 7.79.0 arm [upgradable from: 7.78.0]
libdav1d/stable 0.9.2 arm [upgradable from: 0.9.1]
libexif/stable 0.6.23 arm [upgradable from: 0.6.22]
libjpeg-turbo/stable 2.1.1 arm [upgradable from: 2.1.0]
libprotobuf/stable 2:3.18.0 arm [upgradable from: 2:3.17.3]
ncurses-ui-libs/stable 6.2.20200725-5 arm [upgradable from: 6.2.20200725-4]
ncurses-utils/stable 6.2.20200725-5 arm [upgradable from: 6.2.20200725-4]
ncurses/stable 6.2.20200725-5 arm [upgradable from: 6.2.20200725-4]
neovim/stable 0.5.0-1 arm [upgradable from: 0.5.0]
nodejs/stable 16.9.1-2 arm [upgradable from: 14.15.4-2]
pulseaudio/stable 14.2-5 arm [upgradable from: 14.2-4]
termux-keyring/stable 2.3 all [upgradable from: 2.0]
termux-tools/stable 0.136 all [upgradable from: 0.134-1]
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Wed May 27 17:13:44 WIB 2020 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 6
```

**Comment by Yisus7u7** [comment]
I can confirm that I have the same error, my cell phone is also armv7l

**Comment by AbdullahBinJahed** [comment]
> Wrong repo, belongs to https://github.com/termux/x11-packages.

right ... didn't noticed ... do i have to do it again ?
any way to just move it there ?

**Comment by AbdullahBinJahed** [comment]
native compiling mesa library also didn't solved it

**Comment by xeffyr** [comment]
Yes, that's `mesa-demos` utility issues and not of the mesa library.

https://github.com/termux/x11-packages/issues/394#issuecomment-886960971

**Comment by AbdullahBinJahed** [comment]
> Yes, that's `mesa-demos` utility issues and not of the mesa library.
> 
> [#394 (comment)](https://github.com/termux/x11-packages/issues/394#issuecomment-886960971)

someone did helped me with native compiling mesa ... but I don't know if it worked or not .. 
How to check it ? can you give me a minimal source code to check wheather OpenGL works or not ?
also is there some way to contact you ? like messenger , discord, whatsapp, telegram or anything ?

**Comment by Yisus7u7** [comment]
> > Yes, that's `mesa-demos` utility issues and not of the mesa library.
> > [#394 (comment)](https://github.com/termux/x11-packages/issues/394#issuecomment-886960971)
> 
> someone did helped me with native compiling mesa ... but I don't know if it worked or not .. How to check it ? can you give me a minimal source code to check wheather OpenGL works or not ? also is there some way to contact you ? like messenger , discord, whatsapp, telegram or anything ?

Try compiling this:

https://github.com/davidanthonygardner/glxgears

**Comment by AbdullahBinJahed** [comment]
> Yes, that's `mesa-demos` utility issues and not of the mesa library.
> 
> [#394 (comment)](https://github.com/termux/x11-packages/issues/394#issuecomment-886960971)

got some new errors eyyy ... 😃

![Screenshot_2021-09-29-06-24-46-806_com termux](https://user-images.githubusercontent.com/39275638/135182932-292a9786-a2d8-4de2-802a-8984e8fc20d7.jpg)

**Comment by xeffyr** [comment]
Closed in favor of https://github.com/termux/x11-packages/issues/394.
