### ISSUE TITLE
[Bug]: Pulse audio not working

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#434]
### Problem description

Today I reinstalled my termux, and I realized that any music player (mpv, cmus, audacious) that uses pulseaudio, does not work, the song gets stuck and nothing is heard. 

### What steps will reproduce the bug?

![Screenshot_20210916-183025](https://user-images.githubusercontent.com/64093255/133701683-b90b2f3b-eaa9-420d-8a86-53cb15d35351.png)

Any app that plays music doesn't work, gets stuck and doesn't play anything. 

### What is the expected behavior?

@xeffyr I don't know what error it is, nothing is printed on the console that shows error. 

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.me/termux-packages-24 stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.71-perf-gb847930 #1 SMP PREEMPT Fri Sep 27 14:15:01 CDT 2019 armv7l Android
Device manufacturer:
motorola
Device model:
moto e5 cruise

```

**Comment by NoNameMan1231** [comment]
do ypu start a pulse server?

**Comment by NoNameMan1231** [comment]
do you start a pulse server?

**Comment by Yisus7u7** [comment]
It was fixed when I restarted my phone.
