### ISSUE TITLE
[Package]: xwinwrap

### ISSUE THREAD

**Issue by ELWAER-M** [termux/x11-packages#437]
### Package description

xwinwrap allows to stick most of the apps to your desktop background.

### Source code URL

https://github.com/ujjwal96/xwinwrap

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Yisus7u7** [comment]
I finished compiling the package and it works, in a few minutes I will add it.

**Comment by Yisus7u7** [comment]
![Screenshot_20210922-114448](https://user-images.githubusercontent.com/64093255/134386386-0998aae5-705d-4d3f-b20d-6a95bc5d957d.png)
