### ISSUE TITLE
[Bug]: bochs

### ISSUE THREAD

**Issue by ghost** [termux/x11-packages#447]
### Problem description

When Bochs goes into **32-bit** mode (from 16-bit OS / BIOS) (**on an ARMHF device, since there is no problem on an ARM64 device**), Bochs throws a "Bus error" error.

### What steps will reproduce the bug?

1. Install Bochs on 32-bit ARM device (or install 32-bit firmware for 64-bit device, eg. Galaxy J4 2018 official firmware).
2. Try to install any OS with "bochs-latest" or SeaBIOS BIOS (or use "legacy BIOS" and try to install any 32-bit OS).
3. Bochs is broken!

### What is the expected behavior?

Bochs is launch OS and working.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 3.18.140-19180804 #1 SMP PREEMPT Thu Jun 24 18:55:07 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J400F
```

**Comment by xeffyr** [comment]
What's the point of leaving bug report and then deleting GitHub account?

Closing & locking the issue now.
