### ISSUE TITLE
package request : xrdp

### ISSUE THREAD

**Issue by zefklop** [termux/x11-packages#46]
I'd like to use RDP instead of VNC to remotely connect to my phone. xrdp and xorgxrdp would allow me to do that.

**Package description**
xrdp provides a graphical login to remote machines using Microsoft Remote Desktop Protocol (RDP). xrdp accepts connections from a variety of RDP clients: FreeRDP, rdesktop, NeutrinoRDP and Microsoft Remote Desktop Client (for Windows, Mac OS, iOS and Android).
See https://github.com/neutrinolabs/xrdp/blob/devel/README.md for details

RDP transport is encrypted using TLS by default.

**Link to home page and sources**
https://github.com/neutrinolabs/xrdp/blob/devel/README.md
https://github.com/neutrinolabs/xrdp

**Comment by xeffyr** [comment]
Package added.

**Comment by xeffyr** [comment]
Note that only **xrdp** is supported in Termux.
Package **xorgrdp** won't be available as we don't use *real* xorg server like on desktop linux distribution.

**Comment by shakim24** [comment]
I'm trying to install xrdp in termux but don't know any of the commands that will properly install it, "apt install xrdp" gives me a error about dependencies.  I'm assuming it needs the proper dependencies.
