### ISSUE TITLE
[Package]: update lxqt

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#492]
### Package description

Lxqt just released its version 1.0.0

### Home page URL

lxqt.org

### Source code URL

https://github.com/lxqt

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

An added many improvements and new things

**Comment by NoNameMan1231** [comment]
note: this pr should closed now
