### ISSUE TITLE
Prefer xterm to aterm

### ISSUE THREAD

**Issue by Giugv77yk** [termux/x11-packages#5]
Can you add xterm back to x11.thanks

**Comment by xeffyr** [comment]
@Giugv77yk Which features you need from **xterm** ? Or you use something that require xterm and only it ?

There is a reason that it was removed: it just not working properly (older versions) or not working at all (newer versions, e.g. v337). If I provide a stripped down version of Xterm, you probably won't see a difference between it and aterm.

**Comment by Giugv77yk** [comment]
Yeah sir. I use airgeddon and it need xterm.
And aterm has blank screen in vnc viewer.

**Comment by Giugv77yk** [comment]
Ok sir.Thanks for your explanation.
