### ISSUE TITLE
Package request: wkhtmltopdf

### ISSUE THREAD

**Issue by gribja** [termux/x11-packages#51]
**Description:**
wkhtmltopdf converts HTML to PDF using Webkit.

**Additional links:**
* https://wkhtmltopdf.org
* https://github.com/wkhtmltopdf/wkhtmltopdf

**Comment by tathastu871** [comment]
The official source says latest version supports arm64 and is easily getting installed with pip3 but problem is even after succesfull installation when trying to use it in python it says executable not found

**Comment by Yisus7u7** [comment]
![Screenshot_20211215-124321](https://user-images.githubusercontent.com/64093255/146237780-cc06fd4d-1cba-45b7-8ac9-a4b21a18a92c.png)

@gribja Done.

**Comment by Yisus7u7** [comment]
@xeffyr close this.
