### ISSUE TITLE
Packages dependent on glib from `parole` to `zentiy` are broken

### ISSUE THREAD

**Issue by thunder-coding** [termux/x11-packages#520]
### Problem description

After updating glib in termux-packages, I triggered block rebuilds of packages dependent on glib here but some of them are failing due to shared-mime-info is broken. This needs some serious attention. From https://www.linuxquestions.org/questions/slackware-14/regression-on-current-with-shared-mime-info-4175702872/, it seems to require old meson to build. Also some of the other packages which aren't dependent on shared-mime-info can be built and uploaded locally. I currently don't have access to the aptly key, so this is out of my hand. Probably @Grimler91 and @xeffyr can take care of them.

### What steps will reproduce the bug?

.

### What is the expected behavior?

.

### System information

Unrelated

**Comment by xeffyr** [comment]
So it just `shared-mime-info` being a blocker of other package builds?

**Comment by thunder-coding** [comment]
> So it just `shared-mime-info` being a blocker of other package builds?

Hopefully, it seems to be the case seeing the previous 2 CI runs. I didn't try building the packages locally on my desktop though.

**Comment by Yisus7u7** [comment]
> > So it just `shared-mime-info` being a blocker of other package builds?
> 
> Hopefully, it seems to be the case seeing the previous 2 CI runs. I didn't try building the packages locally on my desktop though.

I'm not sure, but the glib update brought a lot of bugs, xfce4-panel doesn't work, I even compiled the package on my device and it still didn't work.

i installed the old version of glib on my device and everything is working normally so i think glib has problems on this as well.

**Comment by Yisus7u7** [comment]
@thunder-coding 
many packages got working again when I downgraded glib version (all my packages are up to date) so there may be glib issues too
