### ISSUE TITLE
[Bug]: otter-browser failing to launch

### ISSUE THREAD

**Issue by RazyRabbit** [termux/x11-packages#521]
### Problem description

CANNOT LINK EXECUTABLE "otter-browser": cannot localte symbol "__eqtf2" referenced by "/data/data/com.termux/files/usr/lib/libQt5Core.so.5.12.11"...

### What steps will reproduce the bug?

pkg install otter-browser -y
otter-browser

### What is the expected behavior?

The browser must start

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.87-22307827 #1 SMP PREEMPT Mon Aug 23 10:32:18 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N981B
```

**Comment by das-rob3rt** [comment]
Same here. Plus the whole xfce4 is unable to work properly. Even the xfce4-terminal is down.

**Comment by das-rob3rt** [comment]
![Screenshot_20211213-130432.png](https://user-images.githubusercontent.com/29014642/145755467-c13cab8a-ebfa-48ca-aa92-29f2de7f5cd1.png)

Update: I think we are facing the exact same problem here.

![Screenshot_20211213-130449.png](https://user-images.githubusercontent.com/29014642/145755486-a5506055-f99f-44ab-9efd-7c2436d3c1c3.png)

The Xfce4 desktop is not working properly, possible massive loading failures like above.

Hope someone gets this fixed. 🙏

**Comment by Yisus7u7** [comment]
> Same here. Plus the whole xfce4 is unable to work properly. Even the xfce4-terminal is down.

Update your packages

**Comment by Yisus7u7** [comment]
#522

**Comment by das-rob3rt** [comment]
> > Same here. Plus the whole xfce4 is unable to work properly. Even the xfce4-terminal is down.
> 
> Update your packages

Yeah sure, but already with the latest packages.

**Comment by junrenshi** [comment]
Yes, the same issue here after running "pkg upgrade".  Now apps like xpdf, lyx stop working.  Termux-packages seems to be too aggressive in upgrading low-level libraries.  Hope the issue can be fixed soon.

**Comment by Grimler91** [comment]
> Now apps like xpdf, lyx stop working. Termux-packages seems to be too aggressive in upgrading low-level libraries. Hope the issue can be fixed soon.

We are ~10 persons volunteering our spare time to maintain (currently) ~1400 packages. Checking for ABI breakage, and in that case bumping (and fix new build failures) all dependent packages instantly for every library update is not realistic. What we need is issue reports (as here) and/or PRs to bump packages (and fix potential build issues) when something is broken.

@thunder-coding is working on updating the packages that have issues: https://github.com/termux/x11-packages/pull/523

**Comment by das-rob3rt** [comment]
> > Now apps like xpdf, lyx stop working. Termux-packages seems to be too aggressive in upgrading low-level libraries. Hope the issue can be fixed soon.
> 
> We are ~10 persons volunteering our spare time to maintain (currently) ~1400 packages. Checking for ABI breakage, and in that case bumping (and fix new build failures) all dependent packages instantly for every library update is not realistic. What we need is issue reports (as here) and/or PRs to bump packages (and fix potential build issues) when something is broken.
> 
> @thunder-coding is working on updating the packages that have issues: #523

Thank you guys, your efforts are really appreciated by us users. :)
