### ISSUE TITLE
terminal-xfce4 closes when opened

### ISSUE THREAD

**Issue by AnGelXoG** [termux/x11-packages#537]
### Problem description

**the xfce4 terminal closes when opened, I do not know what the problem would be since it affects kermit terminal since they both close on April they do not show any error is the weirdest thing : l**

### What steps will reproduce the bug?

terminals are closed

### What is the expected behavior?

Q work xd

### System information

termux-info:

```

```

**Comment by Yisus7u7** [comment]
@xeffyr 

https://github.com/termux/x11-packages/issues/293

The error is the same as that old problem, apparently libvte is broken again, you have to downgrade the version or see what the problem is.

**Comment by xtkoba** [comment]
Would anyone please post the `strace` output of `xfce4-terminal` for a failed case?

Not sure if related but I found something: https://github.com/mviereck/x11docker/issues/346

**Comment by ivam3** [comment]
@xtkoba on wayland the therminal window just flashed , but on Termux drop the follow error message :
![Screenshot_20211216-183153_Termux](https://user-images.githubusercontent.com/27752315/146469124-ffa1c463-38a9-45fb-9575-7baed1cdd6db.jpg)

**Comment by xtkoba** [comment]
The standard output/error are of no use here.

**Comment by xtkoba** [comment]
It is true that downgrading `libvte` to 0.62.2 probably "fix" the issue. But we ought to investigate the reason as to why 0.64.2 interacts messily with `xfce4-terminal` in preparation for the future. Thus `strace` is still wanted.

**Comment by StevenAlexander44** [comment]
Do I have to rebuild the package libvte to be able to use the xfce4 terminal?

**Comment by xtkoba** [comment]
Apparently the build failed for aarch64 in #540. Now rebuilding.

**Comment by StevenAlexander44** [comment]
How do I install the patch?

**Comment by xtkoba** [comment]
@StevenAlexander44 You can download pre-built binary from https://github.com/termux/x11-packages/actions/runs/1604984431.

**Comment by StevenAlexander44** [comment]
Oh man that's beautiful- thank you so much

**Comment by Mrp1r4t3** [comment]
![Screenshot_20211221_170508](https://user-images.githubusercontent.com/57308381/146902768-03bd36fa-fdef-4126-a263-ac8c1f0f53b4.jpg)
Alternative 😂
