### ISSUE TITLE
[Bug]: java.lang.UnsatisfiedLinkError: no splashscreen in system library path: /data/data/com.termux/files/usr/opt/openjdk/lib 

### ISSUE THREAD

**Issue by ivam3** [termux/x11-packages#555]
### Problem description

I was tried to run a java file in .jar, the first time it worked but after closing it no longer worked. 
I have tried different options of the "java" command such as -Xm256m, other one's as shown in the image, I have added the libraries from $PREFIX/lib to $PREFIX/opt/openjdk/lib and I have even downgraded java at 8 and 9 versions, obtaining the same result.

### What steps will reproduce the bug?

java -jar -Djava.library.path=$LD_LIBRARY_PATH --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED burpsuite.jar

### System information
![Screenshot_20211222-002356_TermuxWayland](https://user-images.githubusercontent.com/27752315/147047935-b4f045b4-dd66-45c5-b1fe-d38f7419ed80.jpg)

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22602103 #1 SMP PREEMPT Fri Oct 15 00:57:06 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A305G
```

**Comment by xtkoba** [comment]
Apparently `libsplashscreen.so` is not bundled in the current `openjdk-17` package. This library file is assumed to be built and installed unless configured with `--enable-headless-only`. We need to investigate the build log to see what has happend.

**Comment by xtkoba** [comment]
This is to blame: https://github.com/termux/openjdk-mobile-termux/commit/d7e158fc8e4b4d96ac28e739ddd9c643af067b57

**Comment by ivam3** [comment]
Thank you so much @xtkoba ... I'll be waiting for the update
