### ISSUE TITLE
[Bug]: MATE DE - mate-session does not start - missing libs - CRITICAL

### ISSUE THREAD

**Issue by nathaneltitane** [termux/x11-packages#559]
### Problem description

installed a frash graphical termux setup foloowing the termux wiki graphical guide.

when starting mate-session manually or via vnc, mate-session complains about missing lib
ˋˋˋ
mate-session &
[2] 25119
~ $ CANNOT LINK EXECUTABLE "mate-session": library "libXtst.so.6" not found: needed by main executable
~ $
ˋˋˋ

### What steps will reproduce the bug?

pkg update
pkg install *-repo
pkg install tigervnc
pkg install mate-* marco

### What is the expected behavior?

mate-session should load and start?

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-22501734 #1 SMP PREEMPT Thu Oct 7 17:52:58 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T970
```

**Comment by xtkoba** [comment]
Should be worked around by installing `libxtst` (manually).
