### ISSUE TITLE
i3status 'battery' and 'ethernet' config categories broken/not found - CRITICAL

### ISSUE THREAD

**Issue by nathaneltitane** [termux/x11-packages#567]
### Problem description

i3status config manual recommendation shows a category to enable tracking battery status and other hardware such as ethernet.

my config uses exactly the items prescribed by the manual and they used to work in older versions under termux - they no longer do, where i3status exit with status 1 and complains of 'battery' and 'ethernet' not being valid

same configuration works flawlessly under a proot container using any ubuntu distro.

### What steps will reproduce the bug?

install termux (fresh)
pkg install i3 i3status

run vnc session and load i3 as wm

### What is the expected behavior?

i3status should fetch relevant dirs and show information without exit status or crash.

see configs at:

https://raw.githubusercontent.com/nathaneltitane/terminal/master/i3wm/i3/config
https://raw.githubusercontent.com/nathaneltitane/terminal/master/i3wm/i3status/config

output:

![Screenshot_20211229-222241_Termux](https://user-images.githubusercontent.com/5674757/147719172-321eb2cf-1c67-4e74-9f32-97437e7a5a16.png)

### System information

termux-info:

```
[ termux ] >_ $ termux-info
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-22501734 #1 SMP PREEMPT Thu Oct 7 17:52:58 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T970

```

**Comment by xeffyr** [comment]
Intended behavior. https://github.com/termux/x11-packages/blob/master/packages/i3status/i3status-2.13_Makefile.am.patch

**Comment by nathaneltitane** [comment]
@xeffyr I understand your concern, but the data is actually plainly accessible even while using 'cat'

The output used to work back on android 10 I believe... unless android has nothing to do with this change in behavior?

**Comment by xeffyr** [comment]
![Screenshot_20211230-161632](https://user-images.githubusercontent.com/25881154/147759815-81c2bc38-7af6-4a95-9e83-810b8d6d7aa6.png)

I hope I shouldn't explain that Android is fragmented and you may get different results.

**Comment by nathaneltitane** [comment]
> ![Screenshot_20211230-161632](https://user-images.githubusercontent.com/25881154/147759815-81c2bc38-7af6-4a95-9e83-810b8d6d7aa6.png)
> 
> I hope I shouldn't explain that Android is fragmented and you may get different results. On `battery`:
> * Sysfs is accessible only with root. See above.
> * Android uses a different sysfs layout for `battery`, unlike laptops.
> 
> I've disabled all modules that had issues.
> 
> > How do you explain being able to get all the other information then
> 
> Not all information requires sysfs access.

![Screenshot_20211230-132607_Termux.png](https://user-images.githubusercontent.com/5674757/147778659-8c00c987-c66f-4852-be63-62e325bc16ff.png)

**Comment by xeffyr** [comment]
![Screenshot_20211231-103513](https://user-images.githubusercontent.com/25881154/147812672-e8254cad-f3c3-4196-be28-8497bd74bc67.png)
