### ISSUE TITLE
[Package]: SDL debug build

### ISSUE THREAD

**Issue by undefinedmain** [termux/x11-packages#590]
### Package description

It looks like the current version of sdl2 has a bug, and in order to help figure out what the problem is, I need an SDL version compiled for debugging.

### Home page URL

https://www.libsdl.org/

### Source code URL

https://github.com/libsdl-org/SDL/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried to compile everything myself, but it gives the following errors:

ld.lld: error: undefined symbol: SDL_IsAndroidTablet
>>> referenced by SDL.c:575 (src/SDL.c:575)
>>>               build/.libs/SDL.o:(SDL_IsTablet_REAL)

ld.lld: error: undefined symbol: __android_log_write
>>> referenced by SDL_log.c:401 (src/SDL_log.c:401)
>>>               build/.libs/SDL_log.o:(SDL_LogOutput)

ld.lld: error: undefined symbol: SDL_AndroidShowToast_REAL
>>> referenced by SDL_dynapi_procs.h:0 (src/dynapi/SDL_dynapi_procs.h:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_AndroidRequestPermission_REAL
>>> referenced by SDL_dynapi_procs.h:0 (src/dynapi/SDL_dynapi_procs.h:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_GetAndroidSDKVersion_REAL
>>> referenced by SDL_dynapi_procs.h:0 (src/dynapi/SDL_dynapi_procs.h:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)
>>> referenced by SDL_gamecontroller.c:516 (src/joystick/SDL_gamecontroller.c:516)
>>>               build/.libs/SDL_gamecontroller.o:(SDL_PrivateGetControllerMappingForGUID)

ld.lld: error: undefined symbol: SDL_AndroidBackButton_REAL
>>> referenced by SDL_dynapi_procs.h:0 (src/dynapi/SDL_dynapi_procs.h:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_IsDeXMode_REAL
>>> referenced by SDL_dynapi_procs.h:0 (src/dynapi/SDL_dynapi_procs.h:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_IsChromebook_REAL
>>> referenced by SDL_dynapi_procs.h:0 (src/dynapi/SDL_dynapi_procs.h:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_IsAndroidTV_REAL
>>> referenced by SDL_dynapi_procs.h:0 (src/dynapi/SDL_dynapi_procs.h:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_AndroidGetExternalStoragePath_REAL
>>> referenced by SDL_dynapi.c:0 (src/dynapi/SDL_dynapi.c:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_AndroidGetExternalStorageState_REAL
>>> referenced by SDL_dynapi.c:0 (src/dynapi/SDL_dynapi.c:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_AndroidGetInternalStoragePath_REAL
>>> referenced by SDL_dynapi.c:0 (src/dynapi/SDL_dynapi.c:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)
>>> referenced by SDL_rwops.c:783 (src/file/SDL_rwops.c:783)
>>>               build/.libs/SDL_rwops.o:(SDL_RWFromFile_REAL)
>>> referenced by SDL_gamecontroller.c:1633 (src/joystick/SDL_gamecontroller.c:1633)
>>>               build/.libs/SDL_gamecontroller.o:(SDL_GameControllerInitMappings)

ld.lld: error: undefined symbol: SDL_AndroidGetActivity_REAL
>>> referenced by SDL_dynapi.c:0 (src/dynapi/SDL_dynapi.c:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: SDL_AndroidGetJNIEnv_REAL
>>> referenced by SDL_dynapi.c:0 (src/dynapi/SDL_dynapi.c:0)
>>>               build/.libs/SDL_dynapi.o:(initialize_jumptable)

ld.lld: error: undefined symbol: Android_JNI_FileOpen
>>> referenced by SDL_rwops.c:797 (src/file/SDL_rwops.c:797)
>>>               build/.libs/SDL_rwops.o:(SDL_RWFromFile_REAL)

ld.lld: error: undefined symbol: Android_JNI_FileClose
>>> referenced by SDL_rwops.c:0 (src/file/SDL_rwops.c:0)
>>>               build/.libs/SDL_rwops.o:(SDL_RWFromFile_REAL)

ld.lld: error: undefined symbol: Android_JNI_FileWrite
>>> referenced by SDL_rwops.c:0 (src/file/SDL_rwops.c:0)
>>>               build/.libs/SDL_rwops.o:(SDL_RWFromFile_REAL)

ld.lld: error: undefined symbol: Android_JNI_FileRead
>>> referenced by SDL_rwops.c:0 (src/file/SDL_rwops.c:0)
>>>               build/.libs/SDL_rwops.o:(SDL_RWFromFile_REAL)

ld.lld: error: undefined symbol: Android_JNI_FileSeek
>>> referenced by SDL_rwops.c:0 (src/file/SDL_rwops.c:0)
>>>               build/.libs/SDL_rwops.o:(SDL_RWFromFile_REAL)

ld.lld: error: undefined symbol: Android_JNI_FileSize
>>> referenced by SDL_rwops.c:0 (src/file/SDL_rwops.c:0)
>>>               build/.libs/SDL_rwops.o:(SDL_RWFromFile_REAL)

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xtkoba** [comment]
Closing as outdated.
