### ISSUE TITLE
[Bug]: xorg-xserver / xorg-xserver- xvfb cannot install

### ISSUE THREAD

**Issue by nathaneltitane** [termux/x11-packages#596]
### Problem description

attempting to install xorg-xserver-xvfb and xorg-xserver, whatever the order is, ends up in dpkg error:

![Screenshot_20220202-224929_Termux](https://user-images.githubusercontent.com/5674757/152278291-f6ef9d48-d2b8-4171-b23a-c349f9b2c6c6.jpg)

### Steps to reproduce the behavior.

in whichever order, on a clean install of termux:

pkg install xorg-server-xvfb
pkg install xorg-xserver

### What is the expected behavior?

both packages should install and not error out

### System information

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)                                               deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:                                                                All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.19.113-23197409 termux/termux-app#1 SMP PREEMPT Tue Dec 21 19:32:04 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N986W

**Comment by nathaneltitane** [comment]
@Grimler91 not to be pushy, but what are the odds this gets fixed shortly?

**Comment by Grimler91** [comment]
You can overwrite the file if you are in a hurry: https://askubuntu.com/questions/56761/force-apt-get-to-overwrite-file-installed-by-another-package

**Comment by nathaneltitane** [comment]
> You can overwrite the file if you are in a hurry: https://askubuntu.com/questions/56761/force-apt-get-to-overwrite-file-installed-by-another-package

Oh! good to know :)

 Not in a hurry paticularly, just wondered if the issue was trivial or not.

What can cause such problems btw? If it the package config itself?

**Comment by Grimler91** [comment]
> Not in a hurry paticularly, just wondered if the issue was trivial or not.

Should be fairly trivial, but I am not familiar enough with x11-packages to know what the proper fix is:

* Solution 1: xorg-server and xorg-server-xvfb should conflict with each other
* Solution 2: common files, like Xserver.1.gz, should be removed from xorg-server-xvfb

> What can cause such problems btw? If it the package config itself?

If two packages decides to create files in the same place with the same name, then there will be a conflict. 
In this case the packages are built from the same source archive, so probably there are many common files and the two packages cannot be installed at the same time (which would mean solution 1 is the way to go)

**Comment by nathaneltitane** [comment]
> > Not in a hurry paticularly, just wondered if the issue was trivial or not.
> 
> Should be fairly trivial, but I am not familiar enough with x11-packages to know what the proper fix is:
> 
> * Solution 1: xorg-server and xorg-server-xvfb should conflict with each other
> * Solution 2: common files, like Xserver.1.gz, should be removed from xorg-server-xvfb
> 
> > What can cause such problems btw? If it the package config itself?
> 
> If two packages decides to create files in the same place with the same name, then there will be a conflict. In this case the packages are built from the same source archive, so probably there are many common files and the two packages cannot be installed at the same time (which would mean solution 1 is the way to go)

I do agree witht the logic here, though, looking at the source of the conflict, namely a manual document, if the documentation is either pulled from the same source or is concurrent (package-wise) but identical in content, it should be replaced as it would not be cause for concern in te package'S actual operation.

I believe ubuntu apt / apt-get / dpkg manages to do so (I cannot recall for the life of me which package could server as a good example) where it lists the 'replacement' of manuals and libraries from newly installed version by package X - then restores prior on uninstall.
