### ISSUE TITLE
pck update/upgrade W: GPG error: ... E: The ... disabled by default.

### ISSUE THREAD

**Issue by RalfWerner** [termux/x11-packages#61]
Hi Leonid - my or your bug?
```
$ pkg upgrade
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
Get:3 https://dl.bintray.com/xeffyr/x11-packages x11 Release [6055 B]
Get:4 https://dl.bintray.com/xeffyr/x11-packages x11 Release.gpg [821 B]
Hit:5 https://its-pointless.github.io/files termux InRelease
Ign:4 https://dl.bintray.com/xeffyr/x11-packages x11 Release.gpg
0% [5 InRelease gpgv 2060 B]
Reading package lists... Done
W: GPG error: https://dl.bintray.com/xeffyr/x11-packages x11 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 45F2964132545795
E: The repository 'https://dl.bintray.com/xeffyr/x11-packages x11 Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
Ps is there progress in magick (display) with X11?

**Comment by xeffyr** [comment]
a. You did something wrong when enabling repository.
b. You did partial upgrade. Do `pkg upgrade` - this one should install updated x11-repo and termux-keyring packages.

**Comment by xeffyr** [comment]
If you haven't read contributing guide, I'll post here information about "user errors":

> Important: do not submit bug reports about third-party, self-compiled and **outdated packages**. These issues will be considered as "spam". **Same goes for corrupted configuration files and questions like "help me, I don't know how to use package"**.

\- means that **I'm** not accepting any reports about OUTDATED packages. You didn't upgrade x11-packages and/or installed termux-keyring - your problem.
