### ISSUE TITLE
[Package]: plank

### ISSUE THREAD

**Issue by T-Dynamos** [termux/x11-packages#611]
### Package description

Plank is meant to be the simplest dock on the planet. The goal is to provide
just what a dock needs and absolutely nothing more. It is, however, a library
which can be extended to create other dock programs with more advanced features.

### Home page URL

https://launchpad.net/plank

### Source code URL

https://github.com/ricotz/plank

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Just add it i want it

**Comment by Yisus7u7** [comment]
Requires libraries incompatible with termux, use cairo-dock instead 

![Screenshot_20220220-235735](https://user-images.githubusercontent.com/64093255/154892014-3ec4dbe8-a5e7-44a1-a8cd-520dcf732f62.png)

`pkg install cairo-dock-core`

**Comment by T-Dynamos** [comment]
Thanks
