### ISSUE TITLE
mesa: Update to a newer version

### ISSUE THREAD

**Issue by xtkoba** [termux/x11-packages#614]
https://github.com/termux/x11-packages/blob/e7670e683d504aa780978bc69d3faa2bedcd0aa1/packages/mesa/build.sh#L5

This is no longer a reason we stick to mesa 17.3.x as `pthread_barrier_t` has been introduced since Android API 24.

Blocks #613.

**Comment by Yisus7u7** [comment]
I have table compiled from the source with support vulkan and zink drivers, unfortunately that compilation I do not think will work in the termux build environment

**Comment by Yisus7u7** [comment]
@xtkoba You can get the patches [here](https://github.com/suhan-paradkar/tewmux-disabled/releases/tag/mesa-hw-v2)

I hope that helps you

**Comment by DLC01** [comment]
> I have mesa compiled from the source with support vulkan and zink drivers, unfortunately that compilation I do not think will work in the termux build environment
> 
> It also requires that the phone has vulkan support.

The issue with building it on ci is that it cannot find the `llvm-config` executable and maybe some linking issues at the end which can be fixed by making it link to the ndk stub `libvulkan.so`
