### ISSUE TITLE
[Bug]: Cannot start XWayland

### ISSUE THREAD

**Issue by d4rky-pl** [termux/x11-packages#618]
### Problem description

When installing Xwayland on a fresh Termux installation, it does not start correctly due to a missing `openssl` dependency:

```
~/.../downloads/termux-x11 $ termux-x11
$XDG_RUNTIME_DIR is unset.
Exporting default value (/data/data/com.termux/files/usr/tmp).
termux-x11 is already running
Starting Xwayland
argv[0] = /data/data/com.termux/files/usr/bin/Xwayland
2F 64 61 74 61 2F 64 61  74 61 2F 63 6F 6D 2E 74  |  /data/data/com.t
65 72 6D 75 78 2F 66 69  6C 65 73 2F 75 73 72 2F  |  ermux/files/usr/
62 69 6E 2F 58 77 61 79  6C 61 6E 64              |  bin/Xwayland
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/Xwayland": cannot find "libcrypto.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/usr/bin/Xwayland"
~/.../downloads/termux-x11 $
```

It seems that the latest update might be the culprit because I was able to set it up already few days ago and now it no longer works

### What steps will reproduce the bug?

On fresh install:

```
pkg install x11-repo
pkg install xwayland termux-x11 # only installing repo version of termux-x11 for dependencies
dpkg -i termux-x11.deb # latest artifact from this repository
termux-x11
```

### What is the expected behavior?

The `openssl` library is a dependency to `xwayland` and installing the latter installs the former as well.

### System information

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.190-22554634-abT865XXS5CUL1 #2 SMP PREEMPT Mon Dec 6 09:36:39 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T865
```

**Comment by thunder-coding** [comment]
Can you please fill in the bug report template when filing bugs. 

Anyways, try updating your packages `pkg up`. If it doesn't succeeded you need to follow https://github.com/termux/termux-packages/issues/9050's instructions on recovering from a broken environment

**Comment by d4rky-pl** [comment]
@thunder-coding apologies, when adding this issue from my tablet it did not show me that there's a template report to fill. I've updated the ticket with the solution to the problem

**Comment by xtkoba** [comment]
> The openssl library is a dependency to xwayland and installing the latter installs the former as well.

The dependency is not automatically upgraded. We have dozens of similar issues for other libraries, most notably for `libc++`.

**Comment by xtkoba** [comment]
I have a template for that: *Update your `blahblah` package.* It is just that blahblah becomes openssl in this specific case. I would have put it and immediately closed the issue.

If you want the situation to change, then please <a href="https://github.com/termux/termux-packages/discussions/new">open a new discussion</a>.

**Comment by Grimler91** [comment]
So, looks like packages are up to date based on termux-info in first post, and if that is true then maybe `pkg upgrade` doesn't help.

Error
```
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/Xwayland": cannot find "libcrypto.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/usr/bin/Xwayland"
```
looks very much like libcrypto.so from openssl is missing though, which shouldn't really be possible. 
Maybe [termux-x11](https://github.com/termux/termux-x11) is messing up the environment? If running `Xwayland` works fine on its own then open an issue in https://github.com/termux/termux-x11 instead.

**Comment by Grimler91** [comment]
Probably same issue as in https://github.com/termux/termux-packages/issues/9174#issuecomment-1054064548 (unless rebuild of xwayland fixed it?)

**Comment by xtkoba** [comment]
With the combination of `openssl_1.1.1l_aarch64` (which I have reserved locally) and `openssl-tool_3.0.1_aarch64` I get the following:

```
$ openssl
CANNOT LINK EXECUTABLE "openssl": cannot find "libssl.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/usr/bin/openssl"
Aborted
```

So I believe this should be fixed by updating `openssl` package, and that this is not the same as the `mpv` case.

But yeah, I should have waited for a response from the author: *Update your `openssl` package, and PLEASE report back if the situation changes OR NOT.*

**Comment by truboxl** [comment]
Verneed[0] is likely SONAME issue

Possible to print `ldd $PREFIX/bin/XWayland`?

**Comment by d4rky-pl** [comment]
The problem happens on completely fresh install of Termux. Running `pkg upgrade` does solve the problem. I guess I was not expecting freshly bootstrapped environment to have packages that require upgrading to work.

**Comment by Grimler91** [comment]
> I guess I was not expecting freshly bootstrapped environment to have packages that require upgrading to work.

Fully fresh environment should work fine, but when you do 
```
pkg install x11-repo
pkg install xwayland termux-x11
```
without running `pkg upgrade` you get a mix of old package (openssl in this case) versions and new ones (xwayland, termux-x11), and there's no guarantee they work together
