### ISSUE TITLE
pck update/upgrade/install x11-repo W: GPG error: ... E: The ... disabled by default.

### ISSUE THREAD

**Issue by RalfWerner** [termux/x11-packages#62]
Ok one more with template
**Problem description**
see issue **name** (**E:**)

**Steps to reproduce**
```
$ pkg upgrade;# or pkg install x11-repo
```
**Expected behavior**
**_update/upgrate_** without errors! following the complete log:
```
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
Get:3 https://dl.bintray.com/xeffyr/x11-packages x11 Release [6055 B]
Get:4 https://dl.bintray.com/xeffyr/x11-packages x11 Release.gpg [821 B]
Hit:5 https://its-pointless.github.io/files termux InRelease
Ign:4 https://dl.bintray.com/xeffyr/x11-packages x11 Release.gpg
0% [5 InRelease gpgv 2060 B]
Reading package lists... Done
W: GPG error: https://dl.bintray.com/xeffyr/x11-packages x11 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 45F2964132545795
E: The repository 'https://dl.bintray.com/xeffyr/x11-packages x11 Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
**Additional information**
Post output of command `termux-info`. 
See; https://github.com/its-pointless/gcc_termux/issues/52 and regarding display: https://github.com/termux/x11-packages/issues/49
Depending on problem, additional information may be requested: **_is something missing above?_**

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
## How many duplicates will you post ? I have answered you already !

a. You did something wrong when enabling repository.
b. You did partial upgrade. Do pkg upgrade - this one should install updated x11-repo and termux-keyring packages.

**Comment by xeffyr** [comment]
If you haven't read contributing guide, I'll post here information about "user errors":

> Important: do not submit bug reports about third-party, self-compiled and **outdated packages**. These issues will be considered as "spam". **Same goes for corrupted configuration files and questions like "help me, I don't know how to use package"**.

\- means that **I'm** not accepting any reports about OUTDATED packages. You didn't upgrade x11-packages and/or installed termux-keyring - your problem.

**Comment by xeffyr** [comment]
**I don't care about user-generated errors. I don't have to teach people how they should update/install/configure software. I'm only maintainer of this repository. Now good question: why I should deal with user-generated errors ???**

**Comment by xeffyr** [comment]
By the way, there many people use this repository, not only you @RalfWerner. But only you reported this "bug". Did you know the answer why only you have it ?

**Comment by xeffyr** [comment]
Finally, if you have "trouble" with installing termux-keyring package, why not to download it with wget and install with dpkg ?
