### ISSUE TITLE
[Question]: Enable SDL2 OpenGL Support?

### ISSUE THREAD

**Issue by mguinhos** [termux/x11-packages#624]
We already have Mesa3D, why can't we enable SDL2 X11 OpenGL Support (GLX)?

**Comment by xtkoba** [comment]
Why don't you submit a PR yourself if it should be as easy as replacing `--disable-blahblah` with `--enable-blahblah`?

**Comment by RazyRabbit** [comment]
> Why don't you submit a PR yourself if it should be as easy as replacing `--disable-blahblah` with `--enable-blahblah`?

I'm trying to compile it in my termux first

**Comment by thunder-coding** [comment]
> I'm trying to compile it in my termux first
I'm currently without any computer
All of my development must be on mobile

You can make use of CI. start with a draft PR on your fork and enable actions for your repository

**Comment by RazyRabbit** [comment]
![Screenshot_20220303-061105_VNC Viewer.jpg](https://user-images.githubusercontent.com/43307018/156533327-30afb3bd-7304-40d1-8769-9aa5a08d7f80.jpg)

iT WORKS! GREAT!

**Comment by RazyRabbit** [comment]
![Screenshot_20220303-064017_VNC Viewer.jpg](https://user-images.githubusercontent.com/43307018/156538302-754f1fed-8e92-45c4-9d1b-634ed25848b7.jpg)

KIVY WORKS WELL!!

**Comment by RazyRabbit** [comment]
Doing more testing, and later i will start a PR

**Comment by RazyRabbit** [comment]
Waiting to test with #614
