### ISSUE TITLE
_integer64 [Bug]: V1.5 to V2.02

### ISSUE THREAD

**Issue by Hagimei** [termux/x11-packages#627]
### Problem description

ALL VERSIONS 1.5 to 2.02 releases critical bug found in processing information
_integer64 and _Unsigned _Integer64
Err discovered that _Integer64's MATH is not accurate no matter the length in digits that are environmentally controlled.
Using _Integer64  V.S. Double.. The math looses data and becomes corrupt.. V 1.2 is the only accurate _integer64 algorithm that functions correctly. 
0000000020 2824096036 5167042394 7251286016 <- Using Double
0000000020 2824089600 7599867904 7251286016 <- Using _Integer64 and _Unsigned Integer64
Each set of numbers should match using either function should match since this is using basic math
to exceed * 20,282,409,603,651,670,423,947,251,286,016 *
USAGE:
Dim shared X ( 2, 1000) as _Integer64
The only Release that is accurate is ( V1.2 ) and all other releases contains the same error using _Integer64

### What steps will reproduce the bug?

And basic math formulas that exceeds 8 digits while multiplying

### What is the expected behavior?

Expected behaviors are to compare both 
Double and _Integer64 or _Unsigned _Integer64
Numbers are continuously incorrect

### System information

termux-info:

Laptop HP ENVY x360  16Gig Ram, 8Core 16Thread 4tb ssd drive ( Ryzen 7 4000 Series ) HP

**Comment by Hagimei** [comment]
[xtkoba](https://github.com/xtkoba)
I find that you closing this issue as ( INVALID ) does an extreme injustice to the whole of ( QB64 ) community. This is an extreme bug that relates to math in which the entire core of (QB64) is based on. I am a MATHEMATICIAN and my position as a Military Tactician relies heavily on math and projections...
Open the software in question or contact me direct ( W3L0N1@Aol.com ).. This is a critical err in all releases after 1.2 to 2.02 that must be addressed.....   I DEMAND YOUR ATTENTION, not your excusable whim to dismiss this address as not warranted... I can walk you through this process because the software that I am working on is for work.

**Comment by Grimler91** [comment]
@Hagimei Your report doesn't make any sense. It doesn't seem to be related to termux. I don't see any package name mentioned (_integer64 or qb64 are not termux packages), and from your "termux-info" it doesn't seem to be a termux device.

>  I DEMAND YOUR ATTENTION

Wow, rude.
