### ISSUE TITLE
[Bug]: Parole media player not working

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#628]
### Problem description

Since gstreamer was updated, parole does not play videos

### What steps will reproduce the bug?

The gst-libav drivers are not loaded, and when trying to compile them from the cell phone it is not possible to do so, the compilation fails, with the previous version of gstreamer this did not happen ... 

### What is the expected behavior?

![Screenshot_20220306-115754](https://user-images.githubusercontent.com/64093255/156933405-c5e42577-ee79-4f20-b0ea-5e11f19bf92c.png)

### System information

termux-info:

```
Application version:
0.118.0+b2986de
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.71-perf-gb847930 #1 SMP PREEMPT Fri Sep 27 14:15:01 CDT 2019 armv7l Android
Device manufacturer:
motorola
Device model:
moto e5 cruise

```

**Comment by 2096779623** [comment]
try downgrading to an older version.

**Comment by Yisus7u7** [comment]
https://github.com/termux/termux-packages/commit/6d2ad5831892c32356c3c0439eccf0ab6334e188
