### ISSUE TITLE
Linker and programs cannot find sdl2 library 

### ISSUE THREAD

**Issue by BlueTheBZR** [termux/x11-packages#633]
### Problem description

I was already working with sdl2 on termux and everything went well, after a week or so i update sdl2 to version 2.0.20.

For some reason after the update, my old projects cannot be executed anymore, and trying to make new ones is impossible, clang only shows me this error message:

```
ld.lld: error: unable to find library -lSDL2
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```
I tried using `pkg-config` or directly using `-I` and `-L` linker arguments, but nothing works.

I also tried uninstalling and re installing sdl2, but i got the same results, any advice? This is only happening with sdl2, other packages link properly, and everything is up to date.

Architecture: aarch64.

### What steps will reproduce the bug?

Just try to link sdl2 to a program:

`clang filename.c -o output -lSDL2`

### System information

termux-info:

```

```

**Comment by mguinhos** [comment]
@xtkoba 
Qemu still doesnt works.

```
CANNOT LINK EXECUTABLE "qemu-system-x86_64": library "libSDL2-2.0.so.0" not found: needed by main executable
```
