### ISSUE TITLE
bspwm: Using hardcoded path `/tmp`

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/x11-packages#658]
Just like what [here](https://www.reddit.com/r/termux/comments/gqi3j5/bspwm_problems_with_tmp_folder/frsyidq?utm_medium=android_app&utm_source=share&context=3) and [here](https://www.reddit.com/r/termux/comments/gqi3j5/bspwm_problems_with_tmp_folder/frukmfn?utm_medium=android_app&utm_source=share&context=3) said , we won't able to start bspwm because `/tmp` is not accessible.  I think we should write a patch to solve this issue

**Comment by xtkoba** [comment]
Seems like just a matter of porting. Note that currently we do not package `bspwm` in our official repos. What is this issue for? Is this a packaging request?

**Comment by NoNameMan1231** [comment]
Does it include in the official repo?

**Comment by xtkoba** [comment]
> Bspwm is included in the official repo

Oops, that's right! Then we should fix it.

**Comment by NoNameMan1231** [comment]
@xtkoba  can i patch it at next day? Because I'm busy now
