### ISSUE TITLE
Package request:koreader

### ISSUE THREAD

**Issue by zaoqi** [termux/x11-packages#66]
**Package description**
An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats

**Link to home page and sources**
1. Home page:http://koreader.rocks/
2. Source code:https://github.com/koreader/koreader

**Comment by zaoqi** [comment]
armhf: https://github.com/koreader/koreader/releases/download/v2019.02/koreader-kobo-arm-kobo-linux-gnueabihf-v2019.02.zip
`./luajit reader.lua` can run it

**Comment by buribu** [comment]
This package has been available on F-Droid since September last year...

![Screenshot_20200306-232515](https://user-images.githubusercontent.com/782908/76135057-47dba700-6002-11ea-88de-1d0cb78703b8.png)

**Comment by Yisus7u7** [comment]
But he wants the package for the termux graphics server, not as an application

**Comment by buribu** [comment]
@Yisus7u7  There is a reasonable alternative:

https://pypi.org/project/epy-reader/
