### ISSUE TITLE
[Feature] Add "libgtk-3-dev" package support

### ISSUE THREAD

**Issue by diyism** [termux/x11-packages#691]
### Feature description

I can't find the "libgtk-3-dev" in termux, can you support it without proot a debian?

### Additional information

In my debian system:
```
$ apt-cache policy libgtk-3-dev
libgtk-3-dev:
  Installed: 3.24.23-1
  Candidate: 3.24.33-1
```
In termux:
```
$ apt-cache policy libgtk*
libgtk2:
  Installed: (none)
  Candidate: (none)
  Version table:
libgtk3:
  Installed: (none)
  Candidate: (none)
  Version table:
```

**Comment by xtkoba** [comment]
We do not prefix `lib` to package names in x11 repo. The `gtk3` package is what you want.

**Comment by Yisus7u7** [comment]
@diyism

Termux includes the libraries, header files and other objects in a single package, termux does not usually fragment the package as it should, so the package you need is "gtk3, in it comes the headers, libraries and other necessary things.

**Comment by diyism** [comment]
Sorry for bothering you again, I've "pkg install gtk-3.0", but I still can't figure out what's wrong with gtk-3.0,
I'm compiling phpsciter in termux, after I run "make", it complaints:
```
/data/data/com.termux/files/home/phpsciter/lib/window/win-lnx/php-window-linux.cc:70:30: error: no matching function for call to 'gtk_widget_get_toplevel'
    return hwnd ? GTK_WINDOW(gtk_widget_get_toplevel(hwnd)): nullptr;
                             ^~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/include/gtk-3.0/gtk/gtkwindow.h:40:57: note: expanded from macro 'GTK_WINDOW'
#define GTK_WINDOW(obj)                 (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_WINDOW, GtkWindow))
                                                                      ^~~
/data/data/com.termux/files/usr/include/glib-2.0/gobject/gtype.h:501:80: note: expanded from macro 'G_TYPE_CHECK_INSTANCE_CAST'
#define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
                                                                               ^~~~~~~~
/data/data/com.termux/files/usr/include/glib-2.0/gobject/gtype.h:2417:57: note: expanded from macro '_G_TYPE_CIC'
    ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
                                                        ^~
/data/data/com.termux/files/usr/include/gtk-3.0/gtk/gtkwidget.h:997:14: note: candidate function not viable: cannot convert argument of incomplete type 'LPVOID' (aka 'void *') to 'GtkWidget *' (aka '_GtkWidget *') for 1st argument
GtkWidget*   gtk_widget_get_toplevel    (GtkWidget      *widget);
```
Everything is OK in my debian, but it just won't work in termux, any hint?

**Comment by Yisus7u7** [comment]
@diyism I don't know much about gtk with C, but in my case gtk works perfectly with Rust.

![Screenshot_20220406-163441](https://user-images.githubusercontent.com/64093255/162075509-2424eb3f-2c1f-485c-a601-ef209b696b2f.png)

**Comment by diyism** [comment]
> @diyism I don't know much about gtk with C, but in my case gtk works perfectly with Rust.
> 
> ![Screenshot_20220406-163441](https://user-images.githubusercontent.com/64093255/162075509-2424eb3f-2c1f-485c-a601-ef209b696b2f.png)

OK, I think it's phpsciter's problem, and now I'm using go-webview now, it seems everything is ok.

**Comment by Yisus7u7** [comment]
> OK, I think it's phpsciter's problem, and now I'm using go-webview now, it seems everything is ok.

Ok
