### ISSUE TITLE
Need of vulkan

### ISSUE THREAD

**Issue by Wetitpig** [termux/x11-packages#71]
I am now working on shrinking the image of `termux/package-builder`. Actually, is the Vulkan API provided by the Android NDK required in order to build these packages? Thanks!

**Comment by xeffyr** [comment]
No, graphics used in x11 packages is "hardware independent" currently.
Also, I'm using a [custom](https://github.com/termux/x11-packages/blob/master/Dockerfile) docker image since I need tools that are not available in `termux/package-builder`.
