### ISSUE TITLE
Qemu

### ISSUE THREAD

**Issue by d3nish** [termux/x11-packages#72]
How can I run a x86 based `ld` binary with qemu available in this repo.

My problems:
1. I'm unable to resolve shared libs needed.
2. When I try to sed it then it shows invalid PT_ENTRYP

What I need?
Some help and a proper way to achieve this.

**Comment by xeffyr** [comment]
https://proot-me.github.io

> chroot + mount --bind + binfmt_misc equivalent

> PRoot uses QEMU user-mode to execute programs built for a CPU architecture incompatible with the host one. From users' point-of-view, guest programs handled by QEMU user-mode are executed transparently, that is, just like host programs. To enable this feature users just have to specify which instance of QEMU user-mode they want to use with the option -q:

> proot -R /mnt/armslack-12.2/ -q qemu-arm $ cat /etc/motd Welcome to ARMedSlack Linux 12.2
