### ISSUE TITLE
Aterm not working

### ISSUE THREAD

**Issue by d3nish** [termux/x11-packages#73]
aterm -tr -fg white -bg blue +sb
Doesn't works
Expected behavior
transparent background with Blue color

**Comment by xeffyr** [comment]
Thanks for pointing on this. I'll try to fix, but unfortunately I have no idea why this happens as all necessary options are enabled (transparency,fading,NeXT scrollbar,.Xdefaults).

**Comment by xeffyr** [comment]
It is not a Termux-specific bug. Desktop build of Aterm is also affected.
