### ISSUE TITLE
[Question] Compiling Rust packages. 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#738]
I have a question about compiling Rust packages, I don't see things like managing the installation prefix and things like that in the Cargo.toml file

So, how do I compile a common package created in rust?, termux configures it automatically? Or you have to do steps such example:

```bash

function_example(){
    cargo build --release
    install -Dm700 -t ${TERMUX_PREFIX}/bin ./output-file
}
 
```

**Comment by MrAdityaAlok** [comment]
Build system can configure on its own if package has `Config.toml` in `TERMUX_PKG_SRCDIR`. And `TERMUX_PKG_BUILD_IN_SRC=true` is set.

If you want to override:
```bash
TERMUX_PKG_BUILD_IN_SRC=true
termux_step_make(){
      termux_setup_rust
      cargo build --jobs "${TERMUX_MAKE_PROCESSES}" --target "${CARGO_TARGET_NAME}" --release
}
termux_step_make_install(){
      install -Dm755 -t "${TERMUX_PREFIX}"/bin/<executable_name> target/"${CARGO_TARGET_NAME}"/release/<executable_name>
}

**Comment by Yisus7u7** [comment]
@MrAdityaAlok  Thanks!

**Comment by MrAdityaAlok** [comment]
You are always welcome!
