### ISSUE TITLE
[Package Request] dmenu

### ISSUE THREAD

**Issue by Merith-TK** [termux/x11-packages#74]
Works in tandem with i3, as it is in the default configs for i3
**Package description**
It is a basic application launcher that works well with i3, and is installed along side i3 alot of the time on alot of distro's

**Link to home page and sources**
1. Home page: https://tools.suckless.org/dmenu/
2. Source code: https://tools.suckless.org/dmenu/

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with this command:
```
pkg install dmenu
```
