### ISSUE TITLE
[Package]: Idle3 (python)

### ISSUE THREAD

**Issue by T-DynamosFans** [termux/x11-packages#743]
### Package description

Pure python idle in tkinter

### Home page URL

https://github.com/python/cpython/tree/main/Lib/idlelib

### Source code URL

https://github.com/python/cpython/tree/main/Lib/idlelib

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

![Screenshot_2022-04-10-10-15-52-951_com realvnc viewer android](https://user-images.githubusercontent.com/96837234/162601915-2cff5512-0d62-46ae-9c58-dce3f408e382.jpg)

**Comment by xtkoba** [comment]
`python-tkinter`

**Comment by Yisus7u7** [comment]
@T-DynamosFans

```bash

pkg install python-tkinter

idle
```
