### ISSUE TITLE
[Package]: Vs code, g++, openjdk

### ISSUE THREAD

**Issue by anshiq** [termux/x11-packages#757]
### Package description

Please add some development tools like vscode, g++ & openjdk.

### Home page URL

https://code.visualstudio.com/

### Source code URL

https://code.visualstudio.com/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by wmcbtech30** [comment]
We already have `clang` which points to `g++` as a symlink and `openjdk` 17. but we will not package vs code and it's friends, unless you have an objection i'll reopen this issue. closing

**Comment by anshiq** [comment]
Is there any way I could personally install vs code in my termux, please help me by giving some hinds and steps.
