### ISSUE TITLE
[Package Request] vim-gtk

### ISSUE THREAD

**Issue by duzhaokun123** [termux/x11-packages#79]
**Package description**

gui for vim

**Link to home page and sources**
1. Home page:[https://vim.org](https://vim.org)
2. Source code: [https://github.com/vim/vim](https://github.com/vim/vim/)

~~**Patch**~~
~~libsm: [https://gitlab.freedesktop.org/xorg/lib/libsm](https://gitlab.freedesktop.org/xorg/lib/libsm)~~

~~to fix libsm-dev~~

**Building**

```sh
./configure --with-features=huge \
--enable-multibyte \
--enable-rubyinterp=yes \
--enable-python3interp=yes \
--with-python-config-dir=/data/data/com.termux/files/usr/lib/python3.7/config-3.7m/ \
--enable-perlinterp=yes \
--enable-luainterp=yes \
--enable-gui=gtk3 \
--enable-cscope \
--prefix=/data/data/com.termux/files/usr \
--with-lua-prefix=/data/data/com.termux/files/usr

make
```

**Comment by duzhaokun123** [comment]
It works and support Chinese

![vim-gui @ gdrive](https://drive.google.com/file/d/1phIeKzgLEa5eCnMYQgmFyzWIuemFssJA/view?usp=sharing)

**Comment by xeffyr** [comment]
Package is now available.

Use this command to install it:
```
pkg install vim-gtk
```

**Comment by adilakavov1204** [comment]
I tried to install vim-pkg via pkg install vim-gtk but i get response "Unable to locate package vim-gtk"

**Comment by xeffyr** [comment]
@adilakavov1204 Because you don't have x11-repo enabled.
https://github.com/termux/x11-packages#how-to-enable-this-repository
