### ISSUE TITLE
[Package Request]gobject-introspection

### ISSUE THREAD

**Issue by duzhaokun123** [termux/x11-packages#81]
**Package description**

GObject introspection is a middleware layer between C libraries (using GObject) and language bindings, cf.

**Link to home page and sources**
1. Home page: [https://gi.readthedocs.io/](https://gi.readthedocs.io/)

2. Source code: `git clone https://gitlab.gnome.org/GNOME/gobject-introspection.git`

**Comment by LeapofAzzam-backup** [comment]
Any news?

**Comment by suhan-paradkar** [comment]
gobject-introspection is now available....
@xeffyr please close this

**Comment by Yisus7u7** [comment]
I still have the same error, I do not detect the gtk module with python3:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/gtk.py", line 6, in <module>
    gi.require_version('Gtk', '3.0')
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

**Comment by leapofazzam123** [comment]
> I still have the same error, I do not detect the gtk module with python3:
> 
> Traceback (most recent call last):
> File "/data/data/com.termux/files/home/gtk.py", line 6, in
> gi.require_version('Gtk', '3.0')
> File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/gi/**init**.py", line 126, in require_version
> raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Gtk not available

Me too

**Comment by Yisus7u7** [comment]
It is because there are 2 missing packages, it's time to wait to see what they say
