### ISSUE TITLE
404 for https://termux-x11.ml x11 Release

### ISSUE THREAD

**Issue by feklee** [termux/x11-packages#83]
Just wanted to upgrade Termux, which I haven't done probably in months. Now I get an error related to temux-x11 not being found:

    $ pkg upgrade
    Hit:1 https://termux.net stable InRelease
    Hit:2 https://grimler.se root InRelease
    Ign:3 https://termux-x11.ml x11 InRelease
    Err:4 https://termux-x11.ml x11 Release
      404
    Reading package lists... Done
    E: The repository 'https://termux-x11.ml x11 Release' does no longer have a Release file.                     
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.              
    N: See apt-secure(8) manpage for repository creation and user configuration details.  

I see a 404. *Is this a temporary outage? Is there an issue with my configuration?*

**Comment by xeffyr** [comment]
> Just wanted to upgrade Termux, which I haven't done probably in months.

Mamy things changed in past months.
https://termux-x11.ml/2019/01/28/repository-is-now-stored-on-bintray/

**Comment by CodyBontecou** [comment]
> > Just wanted to upgrade Termux, which I haven't done probably in months.
> 
> Many things changed in past months.
> https://termux-x11.ml/2019/01/28/repository-is-now-stored-on-bintray/

I am running into this issue as well. Tried a reinstall but no success. Can't seem to read the above article, a bit of direction would be much appreciated.
