### ISSUE TITLE
XFCE Desktop

### ISSUE THREAD

**Issue by DannyKurniawan642** [termux/x11-packages#84]
I Need Desktop XFCE4

**Comment by duzhaokun123** [comment]
[https://github.com/Hax4us/termux-x](https://github.com/Hax4us/termux-x)

**Comment by DannyKurniawan642** [comment]
Thx

**Comment by xeffyr** [comment]
XFCE4 is available via metapackage `xfce`:
```
pkg install xfce
```

**Comment by abhishek1245** [comment]
Fire Fox xfce4
