### ISSUE TITLE
file conflict between xorg-mkfontdir and xorg-mkfontscale

### ISSUE THREAD

**Issue by smaslovski** [termux/x11-packages#91]
**Problem description**

While installing xterm with the dependencies I got this error:

$ pkg install xterm
........
 Preparing to unpack .../14-xorg-mkfontdir_1.0.7-6_all.deb ...
Unpacking xorg-mkfontdir (1.0.7-6) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-PvdZeh/14-xorg-mkfontdir_1.0.7-6_all.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/share/man/man1/mkfontdir.1.gz', which is also in package xorg-mkfontscale 1.2.1

**Steps to reproduce**

$ pkg install xterm

**Expected behavior**

A package must not owerwrite files from another package.

**System information**

$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.71-15759240 #1 SMP PREEMPT Thu Apr 4 14:01:51 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-T820

**Comment by smaslovski** [comment]
The reason is that xorg-mkfontscale errorneously includes mkfontdir executable and its man page.

**Comment by xeffyr** [comment]
xorg-mkfontscale now provides mkfontdir too.
Package xorg-mkfontdir is no longer needed.

**Comment by xeffyr** [comment]
Should be fixed now.
