### ISSUE TITLE
library "libXext.so.6" not found

### ISSUE THREAD

**Issue by smaslovski** [termux/x11-packages#92]
**Problem description**

After installing xterm and its dependencies:

$ xterm
CANNOT LINK EXECUTABLE "aterm": library "libXext.so.6" not found
Aborted

**Steps to reproduce**

1) install xterm (it installs aterm, in fact)
2) run xterm or aterm

**Expected behavior**

Package libxext should have a simlink libXext.so pointing to libXext.so.6 (the actual library)

**System information**

$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.71-15759240 #1 SMP PREEMPT Thu Apr 4 14:01:51 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-T820

**Comment by smaslovski** [comment]
And more of the same stuff:

$ cd ../usr/lib
$ ln -s libXext.so libXext.so.6
$ xterm
CANNOT LINK EXECUTABLE "aterm": library "libXau.so.6" not found
Aborted
$ ln -s libXau.so libXau.so.6
$ xterm
CANNOT LINK EXECUTABLE "aterm": library "libXdmcp.so.6" not found
Aborted
$ ln -s libXdmcp.so libXdmcp.so.6
$ xterm    =>  OK

**Comment by xeffyr** [comment]
Should be fixed now.
