### ISSUE TITLE
Fluxbox no longer working in Android 5

### ISSUE THREAD

**Issue by IntyLab** [termux/x11-packages#97]
It was last working yesterday.  When I ran my X startup script this morning, which launches my Window Manager, I got this error:

CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "fluxbox"...

Fortunately, I still have TWM, and I was able to revert to that.

**Comment by IntyLab** [comment]
This morning, the same thing happened with emacs: working yesterday, "cannot link executable" error today.  Fortunately, I was able to get emacs working again by running pkg reinstall (and then I had to run pkg install emacs-x again, but that's no big deal).  I tried pkg reinstall fluxbox, but I still can't run it.  I don't know if that helps.  Maybe I'm missing a dependency?

**Comment by xeffyr** [comment]
Fixed.

**Comment by IntyLab** [comment]
Perfect.  I just verified it's working.  Thank you.
