### ISSUE TITLE
Obmenu

### ISSUE THREAD

**Issue by vpervenditti** [termux/x11-packages#99]
**Package description**
Obmenu is a menu editor designed for openbox. It's easy to use, allowing to get the most out of the powerful Openbox menu system, while hiding the xml layout from the user.
It also (optionally) installs a bunch of dynamic menus (pipe menus), such as Gnome menus or a quick-navigator.

**Link to home page and sources**
1. Home page: http://obmenu.sourceforge.net/
2. Source code: https://sourceforge.net/projects/obmenu/files/obmenu/1.0/obmenu-1.0.tar.gz/download?use_mirror=vorboss&download=

**Comment by xeffyr** [comment]
It is a python package that requires pygtk.
Unlikely to be available as we do not package python modules.

**Comment by vpervenditti** [comment]
an alternative?
